import { readFileSync } from '../../helpers/test-filesystem';
import { describe, expect, it } from 'vitest';
import {
  buildTwoRoomFixtures, TWO_ROOM_ADVENTURER_ID, TWO_ROOM_CLOCK, TWO_ROOM_GOBLIN_ID,
  TWO_ROOM_SEED,
} from '../../../src/vtt/handoff/fixtures/two-room';
import { sceneSnapshotSchema } from '../../../src/vtt/handoff/v1/contracts';
import { generateTwoRoomFixtureFiles } from '../../../tools/vtt-handoff/generate-fixtures';

if (process.env.VTT_HANDOFF_GENERATE === '1') {
  generateTwoRoomFixtureFiles({ check: false });
}

describe('real-engine two-room handoff fixture', () => {
  it('pins source topology, identities, seed, clock, and secret-free state independently', () => {
    const { source } = buildTwoRoomFixtures();
    expect(source.seed).toBe(TWO_ROOM_SEED);
    expect(source.clock).toBe(TWO_ROOM_CLOCK);
    expect(source.state.bounds).toEqual({ columns: 12, rows: 8 });
    expect(source.state.blockedCells).toHaveLength(7);
    expect(source.state.blockedCells.every((cell) => cell.column === 5 && cell.row !== 4)).toBe(true);
    expect(source.state.worldObjects.map((object) => object.kind).sort()).toEqual(['barrier', 'cover', 'cover', 'door', 'light-source']);
    expect(source.state.combatants.map((entry) => entry.profile.id)).toEqual([TWO_ROOM_ADVENTURER_ID, TWO_ROOM_GOBLIN_ID]);
    expect(source.state.dmNotes).toEqual([]);
    expect(source.state.hiddenCombatants).toEqual([]);
    expect(source.playerBindings.map((binding) => binding.seatId)).toEqual(['player:adventurer', 'player:goblin']);
  });

  it('pins door references, token centres, audience lights, and seat differences', () => {
    const { snapshots } = buildTwoRoomFixtures();
    expect(snapshots.sourceRevision).toBe(0);
    expect(snapshots.dm.tokens.map((token) => ({ name: token.name, x: token.x, y: token.y }))).toEqual([
      { name: 'Adventurer', x: 2, y: 4 }, { name: 'Goblin', x: 8, y: 4 },
    ]);
    const door = snapshots.dm.doors[0];
    expect(snapshots.dm.walls.some((wall) => wall.id === door?.wallId)).toBe(true);
    expect(snapshots.dm.lights.map((light) => light.id)).toContain('light:environment:region:two-room-torch-bright');
    expect(snapshots.players.every((player) => player.snapshot.lights.every((light) => !light.id.startsWith('light:environment:')))).toBe(true);
    expect(snapshots.players[0]?.snapshot.tokens).not.toEqual(snapshots.players[1]?.snapshot.tokens);
    for (const snapshot of [snapshots.dm, ...snapshots.players.map((player) => player.snapshot)]) {
      expect(sceneSnapshotSchema.safeParse(snapshot).success).toBe(true);
    }
  });

  it('keeps tracked generated bytes equal only in addition to independent invariants', () => {
    const generated = buildTwoRoomFixtures();
    expect(JSON.parse(readFileSync('fixtures/scenes/two-room.v1.json', 'utf8'))).toEqual(generated.source);
    expect(JSON.parse(readFileSync('fixtures/scenes/two-room.snapshots.v1.json', 'utf8'))).toEqual(generated.snapshots);
    expect(() => generateTwoRoomFixtureFiles({ check: true })).not.toThrow();
  });
});
