import { readFileSync } from '../../helpers/test-filesystem';
import { describe, expect, it } from 'vitest';
import {
  buildTwoRoomFixtures,
} from '../../../src/vtt/handoff/fixtures/two-room';
import { sceneSnapshotSchema } from '../../../src/vtt/handoff/v1/contracts';
import { generateTwoRoomFixtureFiles } from '../../../tools/vtt-handoff/generate-fixtures';

describe('real-engine two-room handoff fixture', () => {
  it('pins source topology, identities, seed, clock, and secret-free state independently', () => {
    const { source } = buildTwoRoomFixtures();
    expect(source.seed).toBe(603_020_001);
    expect(source.clock).toBe('2026-09-09T12:00:00.000Z');
    expect(source.state.bounds).toEqual({ columns: 12, rows: 8 });
    expect(source.state.blockedCells).toEqual([
      { column: 5, row: 0 }, { column: 5, row: 1 }, { column: 5, row: 2 },
      { column: 5, row: 3 }, { column: 5, row: 5 }, { column: 5, row: 6 },
      { column: 5, row: 7 },
    ]);
    expect(source.state.worldObjects.map((object) => [object.id, object.kind])).toEqual([
      ['object:two-room-door', 'door'],
      ['object:two-room-barrel', 'cover'],
      ['object:two-room-table', 'cover'],
      ['object:two-room-pillar', 'cover'],
      ['object:two-room-torch', 'light-source'],
    ]);
    expect(source.state.combatants.map((entry) => entry.profile.id))
      .toEqual(['combatant:two-room-adventurer', 'combatant:two-room-goblin']);
    expect(source.state.tokens.map((token) => token.id))
      .toEqual(['token:two-room-adventurer', 'token:two-room-goblin']);
    expect(source.state.dmNotes).toEqual([]);
    expect(source.state.hiddenCombatants).toEqual([]);
    expect(source.playerBindings.map((binding) => binding.seatId)).toEqual(['player:adventurer', 'player:goblin']);
  });

  it('pins door references, token centres, audience lights, and seat differences', () => {
    const { snapshots } = buildTwoRoomFixtures();
    expect(snapshots.sourceRevision).toBe(0);
    expect(snapshots.dm.tokens.map((token) => ({ id: token.id, label: token.label, x: token.x, y: token.y }))).toEqual([
      { id: 'token:two-room-adventurer', label: 'Adventurer', x: 2, y: 4 },
      { id: 'token:two-room-goblin', label: 'Goblin', x: 8, y: 4 },
    ]);
    const door = snapshots.dm.doors[0];
    expect(snapshots.dm.walls.some((wall) => wall.id === door?.wallId)).toBe(true);
    expect(snapshots.dm.lights.map((light) => light.id)).toContain('light:environment:region:two-room-torch-bright');
    expect(snapshots.players.every((player) => player.snapshot.lights.every((light) => !light.id.startsWith('light:environment:')))).toBe(true);
    expect(snapshots.players[0]?.snapshot.tokens).not.toEqual(snapshots.players[1]?.snapshot.tokens);
    for (const snapshot of [snapshots.dm, ...snapshots.players.map((player) => player.snapshot)]) {
      expect(sceneSnapshotSchema.safeParse(snapshot).success).toBe(true);
    }
  });

  it('exercises every logical asset identity with honest fallback telemetry', () => {
    const { snapshots } = buildTwoRoomFixtures();
    const assetIds = new Set([
      ...snapshots.dm.tiles.map((entry) => entry.assetId),
      ...snapshots.dm.props.map((entry) => entry.assetId),
      ...snapshots.dm.tokens.map((entry) => entry.assetId),
      ...snapshots.dm.walls.flatMap((entry) => entry.assetId === undefined ? [] : [entry.assetId]),
      ...snapshots.dm.doors.flatMap((entry) => entry.assetId === undefined ? [] : [entry.assetId]),
    ]);
    expect([...assetIds].sort()).toEqual([
      'door.wood', 'prop.barrel', 'prop.pillar', 'prop.table', 'prop.torch',
      'tile.stone.floor', 'token.adventurer', 'token.goblin', 'wall.stone',
    ]);
    expect(snapshots.dmAssetFallbacks).toEqual([]);
    expect(snapshots.players.map((entry) => entry.assetFallbacks)).toEqual([[], []]);
  });

  it('keeps tracked generated bytes equal only in addition to independent invariants', () => {
    const generated = buildTwoRoomFixtures();
    expect(JSON.parse(readFileSync('fixtures/scenes/two-room.v1.json', 'utf8'))).toEqual(generated.source);
    expect(JSON.parse(readFileSync('fixtures/scenes/two-room.snapshots.v1.json', 'utf8'))).toEqual(generated.snapshots);
    expect(() => generateTwoRoomFixtureFiles({ check: true })).not.toThrow();
  });
});
