import type { EffectPayload } from '../effects';
import { damageType } from '../values';
import type {
  EffectData,
  ScaledDice,
  SpellComponentsData,
  SpellDefinition,
} from './types';

const V: SpellComponentsData = { verbal: true, somatic: false, material: null };
const VS: SpellComponentsData = { verbal: true, somatic: true, material: null };
const S: SpellComponentsData = { verbal: false, somatic: true, material: null };
const S_M_WEAPON: SpellComponentsData = {
  verbal: false,
  somatic: true,
  material: {
    text: 'a weapon with which you have proficiency and that is worth 1+ CP',
    consumed: false,
  },
};

function material(text: string, consumed = false): SpellComponentsData {
  return { verbal: true, somatic: true, material: { text, consumed } };
}

function materialWith(
  text: string,
  flags: { readonly verbal: boolean; readonly somatic: boolean },
  consumed = false,
): SpellComponentsData {
  return { ...flags, material: { text, consumed } };
}

function dice(
  baseCount: number,
  sides: number,
  options: {
    readonly modifier?: number;
    readonly perSlotCount?: number;
    readonly perSlotModifier?: number;
    readonly cantripUpgrade?: boolean;
  } = {},
): ScaledDice {
  return {
    baseCount,
    sides,
    modifier: options.modifier ?? 0,
    perSlotCount: options.perSlotCount ?? 0,
    perSlotModifier: options.perSlotModifier ?? 0,
    cantripUpgrade: options.cantripUpgrade ?? false,
  };
}

function effect(
  payload: EffectPayload,
  options: {
    readonly target?: 'self' | 'targets';
    readonly concentration?: boolean;
    readonly durationRounds?: number | null;
    readonly expiresAt?: EffectData['expiresAt'];
    readonly repeatedSave?: EffectData['repeatedSave'];
    readonly durationRoundsPerSlot?: number;
  } = {},
): EffectData {
  return {
    payload,
    target: options.target ?? 'targets',
    concentration: options.concentration ?? false,
    durationRounds: options.durationRounds ?? 1,
    expiresAt: options.expiresAt ?? 'source_start',
    ...(options.repeatedSave === undefined ? {} : { repeatedSave: options.repeatedSave }),
    ...(options.durationRoundsPerSlot === undefined ? {} : { durationRoundsPerSlot: options.durationRoundsPerSlot }),
  };
}

const cantripDamage = (baseCount: number, sides: number): ScaledDice =>
  dice(baseCount, sides, { cantripUpgrade: true });

/**
 * First 4b-i executable batch. Every value below is pinned independently in
 * tests/unit/combat/spells.test.ts against the cited bundled-SRD lines.
 */
export const IMPLEMENTED_SPELL_DEFINITIONS: readonly SpellDefinition[] = [
  {
    id: 'acid-splash', name: 'Acid Splash', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:37-51',
    castingTime: 'action', components: VS,
    targeting: { kind: 'area', rangeFeet: 60, shape: 'sphere', baseSizeFeet: 5, sizePerSlotFeet: 0 },
    operation: { kind: 'save_damage', ability: 'dexterity', onSuccess: 'none', damageType: damageType('Acid'), dice: cantripDamage(1, 6), riderOnFailure: null, pushFeetOnFailure: 0 },
  },
  {
    id: 'chill-touch', name: 'Chill Touch', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:1066',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: false },
    operation: { kind: 'attack_damage', attackKind: 'melee', damageType: damageType('Necrotic'), dice: cantripDamage(1, 10), rider: effect({ kind: 'cannot_regain_hit_points' }) },
  },
  {
    id: 'dancing-lights', name: 'Dancing Lights', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:1906',
    castingTime: 'action', components: material('a bit of phosphorus'),
    targeting: { kind: 'utility', rangeFeet: 120 },
    operation: { kind: 'utility', effect: { kind: 'light_source', brightFeet: 0, dimFeet: 10, maximumLights: 4, moveFeetPerBonusAction: 60 }, concentration: true, durationRounds: 10 },
  },
  {
    id: 'elementalism', name: 'Elementalism', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:2630',
    castingTime: 'action', components: VS,
    targeting: { kind: 'utility', rangeFeet: 30 },
    operation: { kind: 'utility', effect: { kind: 'minor_magic', spell: 'Elementalism', options: ['beckon_air', 'beckon_earth', 'beckon_fire', 'beckon_water', 'sculpt_element'], maximumActive: 1 }, concentration: false, durationRounds: null },
  },
  {
    id: 'fire-bolt', name: 'Fire Bolt', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:3184-3200',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 120, willing: false },
    operation: { kind: 'attack_damage', attackKind: 'ranged', damageType: damageType('Fire'), dice: cantripDamage(1, 10), rider: null },
  },
  {
    id: 'guidance', name: 'Guidance', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:4000',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'ability_check_modifier', count: 1, sides: 4, sign: 1, skill: 'chosen_when_cast' }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'light', name: 'Light', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:4816',
    castingTime: 'action', components: { verbal: true, somatic: false, material: { text: 'a firefly or phosphorescent moss', consumed: false } },
    targeting: { kind: 'utility', rangeFeet: 5 },
    operation: { kind: 'utility', effect: { kind: 'light_source', brightFeet: 20, dimFeet: 20, maximumLights: 1, moveFeetPerBonusAction: 0 }, concentration: false, durationRounds: 600 },
  },
  {
    id: 'mage-hand', name: 'Mage Hand', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:4931',
    castingTime: 'action', components: VS,
    targeting: { kind: 'utility', rangeFeet: 30 },
    operation: { kind: 'utility', effect: { kind: 'conjured_hand', maximumDistanceFeet: 30, moveFeetPerAction: 30, carryPounds: 10 }, concentration: false, durationRounds: 10 },
  },
  {
    id: 'mending', name: 'Mending', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:5322',
    castingTime: 'minute', components: material('two lodestones'),
    targeting: { kind: 'utility', rangeFeet: 5 },
    operation: { kind: 'utility', effect: { kind: 'object_repair', maximumBreakFeet: 1, restoresMagic: false }, concentration: false, durationRounds: null },
  },
  {
    id: 'message', name: 'Message', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:5341',
    castingTime: 'action', components: { verbal: false, somatic: true, material: { text: 'a copper wire', consumed: false } },
    targeting: { kind: 'single', rangeFeet: 120, willing: false },
    operation: { kind: 'utility', effect: { kind: 'communication_link', rangeFeet: 120, permitsReply: true, blockedByMagicalSilence: true }, concentration: false, durationRounds: 1 },
  },
  {
    id: 'minor-illusion', name: 'Minor Illusion', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:5420',
    castingTime: 'action', components: { verbal: false, somatic: true, material: { text: 'a bit of fleece', consumed: false } },
    targeting: { kind: 'utility', rangeFeet: 30 },
    operation: { kind: 'utility', effect: { kind: 'illusion', modes: ['sound', 'image'], maximumCubeFeet: 5 }, concentration: false, durationRounds: 10 },
  },
  {
    id: 'poison-spray', name: 'Poison Spray', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:5925',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 30, willing: false },
    operation: { kind: 'attack_damage', attackKind: 'ranged', damageType: damageType('Poison'), dice: cantripDamage(1, 12), rider: null },
  },
  {
    id: 'prestidigitation', name: 'Prestidigitation', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:6034',
    castingTime: 'action', components: VS,
    targeting: { kind: 'utility', rangeFeet: 10 },
    operation: { kind: 'utility', effect: { kind: 'minor_magic', spell: 'Prestidigitation', options: ['sensory', 'fire_play', 'clean_or_soil', 'minor_sensation', 'magic_mark', 'minor_creation'], maximumActive: 3 }, concentration: false, durationRounds: 600 },
  },
  {
    id: 'ray-of-frost', name: 'Ray of Frost', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:6427',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 60, willing: false },
    operation: { kind: 'attack_damage', attackKind: 'ranged', damageType: damageType('Cold'), dice: cantripDamage(1, 8), rider: effect({ kind: 'movement_modifier', speedDeltaFeet: -10 }) },
  },
  {
    id: 'resistance', name: 'Resistance', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:6540',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'damage_reduction', damageType: 'chosen_when_cast', count: 1, sides: 4, oncePerTurn: true }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'sacred-flame', name: 'Sacred Flame', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:6645',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 60, willing: false },
    operation: { kind: 'save_damage', ability: 'dexterity', onSuccess: 'none', damageType: damageType('Radiant'), dice: cantripDamage(1, 8), riderOnFailure: null, pushFeetOnFailure: 0 },
  },
  {
    id: 'shocking-grasp', name: 'Shocking Grasp', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:7006',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: false },
    operation: { kind: 'attack_damage', attackKind: 'melee', damageType: damageType('Lightning'), dice: cantripDamage(1, 8), rider: effect({ kind: 'opportunity_attacks_disabled' }) },
  },
  {
    id: 'spare-the-dying', name: 'Spare the Dying', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:7181',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 30, willing: true },
    operation: { kind: 'stabilize' },
  },
  {
    id: 'thaumaturgy', name: 'Thaumaturgy', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:7842',
    castingTime: 'action', components: V,
    targeting: { kind: 'utility', rangeFeet: 30 },
    operation: { kind: 'utility', effect: { kind: 'minor_magic', spell: 'Thaumaturgy', options: ['altered_eyes', 'booming_voice', 'fire_play', 'invisible_hand', 'phantom_sound', 'tremors'], maximumActive: 3 }, concentration: false, durationRounds: 10 },
  },
  {
    id: 'true-strike', name: 'True Strike', level: 0,
    source: 'docs/srd/source/spell-descriptions.txt:8079',
    castingTime: 'action', components: S_M_WEAPON,
    targeting: { kind: 'single', rangeFeet: 5, willing: false },
    operation: { kind: 'weapon_attack', extraDamage: dice(0, 6, { cantripUpgrade: true }), extraDamageType: damageType('Radiant') },
  },
  {
    id: 'bane', name: 'Bane', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:670',
    castingTime: 'action', components: material('a drop of blood'),
    targeting: { kind: 'multiple', rangeFeet: 30, baseMaximum: 3, additionalPerSlot: 1 },
    operation: { kind: 'save_effect', ability: 'charisma', rollMode: 'normal', effect: effect({ kind: 'd20_test_modifier', tests: ['attack_roll', 'saving_throw'], count: 1, sides: 4, sign: -1 }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'charm-person', name: 'Charm Person', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:1046',
    castingTime: 'action', components: VS,
    targeting: { kind: 'multiple', rangeFeet: 30, baseMaximum: 1, additionalPerSlot: 1 },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'advantage', effect: effect({ kind: 'condition', condition: 'Charmed' }, { durationRounds: 600 }) },
  },
  {
    id: 'bless', name: 'Bless', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:824',
    castingTime: 'action', components: material('a Holy Symbol worth 5+ GP'),
    targeting: { kind: 'multiple', rangeFeet: 30, baseMaximum: 3, additionalPerSlot: 1 },
    operation: { kind: 'effect', effect: effect({ kind: 'd20_test_modifier', tests: ['attack_roll', 'saving_throw'], count: 1, sides: 4, sign: 1 }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'burning-hands', name: 'Burning Hands', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:924',
    castingTime: 'action', components: VS,
    targeting: { kind: 'area', rangeFeet: 0, shape: 'cone', baseSizeFeet: 15, sizePerSlotFeet: 0 },
    operation: { kind: 'save_damage', ability: 'dexterity', onSuccess: 'half', damageType: damageType('Fire'), dice: dice(3, 6, { perSlotCount: 1 }), riderOnFailure: null, pushFeetOnFailure: 0 },
  },
  {
    id: 'cure-wounds', name: 'Cure Wounds', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:1895',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'healing', dice: dice(2, 8, { perSlotCount: 2 }), addSpellcastingModifier: true },
  },
  {
    id: 'false-life', name: 'False Life', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:2930',
    castingTime: 'action', components: material('a drop of alcohol'),
    targeting: { kind: 'self' },
    operation: { kind: 'temporary_hit_points', dice: dice(2, 4, { modifier: 4, perSlotModifier: 5 }) },
  },
  {
    id: 'guiding-bolt', name: 'Guiding Bolt', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:4011',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 120, willing: false },
    operation: { kind: 'attack_damage', attackKind: 'ranged', damageType: damageType('Radiant'), dice: dice(4, 6, { perSlotCount: 1 }), rider: effect({ kind: 'attack_roll_mode_modifier', mode: 'advantage', appliesTo: 'next_attack_against_target' }) },
  },
  {
    id: 'healing-word', name: 'Healing Word', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:4169',
    castingTime: 'bonus_action', components: V,
    targeting: { kind: 'single', rangeFeet: 60, willing: true },
    operation: { kind: 'healing', dice: dice(2, 4, { perSlotCount: 2 }), addSpellcastingModifier: true },
  },
  {
    id: 'inflict-wounds', name: 'Inflict Wounds', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:4593',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: false },
    operation: { kind: 'save_damage', ability: 'constitution', onSuccess: 'half', damageType: damageType('Necrotic'), dice: dice(2, 10, { perSlotCount: 1 }), riderOnFailure: null, pushFeetOnFailure: 0 },
  },
  {
    id: 'magic-missile', name: 'Magic Missile', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:5033',
    castingTime: 'action', components: VS,
    targeting: { kind: 'multiple', rangeFeet: 120, baseMaximum: 3, additionalPerSlot: 1 },
    operation: { kind: 'magic_missiles', baseDarts: 3, additionalPerSlot: 1, damageType: damageType('Force'), dice: dice(1, 4, { modifier: 1 }) },
  },
  {
    id: 'shield', name: 'Shield', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:6937',
    castingTime: 'reaction', components: VS,
    targeting: { kind: 'self' },
    operation: { kind: 'effect', effect: effect({ kind: 'shield_defense', armorClassBonus: 5, magicMissileImmune: true }, { target: 'self', durationRounds: 1 }) },
  },
  {
    id: 'shield-of-faith', name: 'Shield of Faith', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:6956',
    castingTime: 'bonus_action', components: material('a prayer scroll'),
    targeting: { kind: 'single', rangeFeet: 60, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'armor_class_modifier', amount: 2 }, { concentration: true, durationRounds: 100 }) },
  },
  {
    id: 'thunderwave', name: 'Thunderwave', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:7868',
    castingTime: 'action', components: VS,
    targeting: { kind: 'area', rangeFeet: 0, shape: 'cube', baseSizeFeet: 15, sizePerSlotFeet: 0 },
    operation: { kind: 'save_damage', ability: 'constitution', onSuccess: 'half', damageType: damageType('Thunder'), dice: dice(2, 8, { perSlotCount: 1 }), riderOnFailure: null, pushFeetOnFailure: 10 },
  },
  {
    id: 'alarm', name: 'Alarm', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:70',
    castingTime: 'minute', ritual: true, components: material('a bell and silver wire'),
    targeting: { kind: 'area', rangeFeet: 30, shape: 'cube', baseSizeFeet: 20, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'alarm_ward', placement: 'selected_when_cast', maximumCubeFeet: 20, audibleRangeFeet: 60, mentalRangeFeet: 5280 }, concentration: false, durationRounds: 4800 },
  },
  {
    id: 'chromatic-orb', name: 'Chromatic Orb', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:1079',
    castingTime: 'action', components: material('a diamond worth 50+ GP'),
    targeting: { kind: 'single', rangeFeet: 90, willing: false },
    operation: { kind: 'attack_damage', attackKind: 'ranged', damageType: [damageType('Acid'), damageType('Cold'), damageType('Fire'), damageType('Lightning'), damageType('Poison'), damageType('Thunder')], dice: dice(3, 8, { perSlotCount: 1 }), rider: null },
  },
  {
    id: 'color-spray', name: 'Color Spray', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:1193',
    castingTime: 'action', components: material('a pinch of colorful sand'),
    targeting: { kind: 'area', rangeFeet: 0, shape: 'cone', baseSizeFeet: 15, sizePerSlotFeet: 0 },
    operation: { kind: 'save_effect', ability: 'constitution', rollMode: 'normal', effect: effect({ kind: 'condition', condition: 'Blinded' }, { durationRounds: 2, expiresAt: 'source_end' }) },
  },
  {
    id: 'command', name: 'Command', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:1209',
    castingTime: 'action', components: V,
    targeting: { kind: 'multiple', rangeFeet: 60, baseMaximum: 1, additionalPerSlot: 1 },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'normal', effect: effect({ kind: 'commanded_action', options: ['approach', 'drop', 'flee', 'grovel', 'halt'] }, { durationRounds: 1, expiresAt: 'target_end' }) },
  },
  {
    id: 'comprehend-languages', name: 'Comprehend Languages', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:1304',
    castingTime: 'action', ritual: true, components: material('a pinch of soot and salt'),
    targeting: { kind: 'self' },
    operation: { kind: 'utility', effect: { kind: 'language_comprehension', secondsPerPage: 60, decodesSecretMessages: false }, concentration: false, durationRounds: 600 },
  },
  {
    id: 'create-or-destroy-water', name: 'Create or Destroy Water', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:1797',
    castingTime: 'action', components: material('a mix of water and sand'),
    targeting: { kind: 'area', rangeFeet: 30, shape: 'cube', baseSizeFeet: 30, sizePerSlotFeet: 5 },
    operation: { kind: 'utility', effect: { kind: 'environmental_water', placement: 'selected_when_cast', gallons: 10, gallonsPerSlot: 10, cubeFeet: 30, cubeFeetPerSlot: 5 }, concentration: false, durationRounds: null },
  },
  {
    id: 'detect-evil-and-good', name: 'Detect Evil and Good', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:2068',
    castingTime: 'action', components: VS,
    targeting: { kind: 'self' },
    operation: { kind: 'utility', effect: { kind: 'detection_sense', detects: 'creature_types_and_hallow', radiusFeet: 30 }, concentration: true, durationRounds: 100 },
  },
  {
    id: 'detect-magic', name: 'Detect Magic', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:2085',
    castingTime: 'action', ritual: true, components: VS,
    targeting: { kind: 'self' },
    operation: { kind: 'utility', effect: { kind: 'detection_sense', detects: 'magic', radiusFeet: 30 }, concentration: true, durationRounds: 100 },
  },
  {
    id: 'detect-poison-and-disease', name: 'Detect Poison and Disease', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:2103',
    castingTime: 'action', ritual: true, components: material('a yew leaf'),
    targeting: { kind: 'self' },
    operation: { kind: 'utility', effect: { kind: 'detection_sense', detects: 'poison_and_disease', radiusFeet: 30 }, concentration: true, durationRounds: 100 },
  },
  {
    id: 'disguise-self', name: 'Disguise Self', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:2185',
    castingTime: 'action', components: VS,
    targeting: { kind: 'self' },
    operation: { kind: 'utility', effect: { kind: 'appearance_illusion', maximumHeightChangeFeet: 1, investigationAgainstSpellDc: true }, concentration: false, durationRounds: 600 },
  },
  {
    id: 'expeditious-retreat', name: 'Expeditious Retreat', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:2810',
    castingTime: 'bonus_action', components: VS,
    targeting: { kind: 'self' },
    operation: { kind: 'effect', effect: effect({ kind: 'bonus_action_dash', immediateDash: true }, { target: 'self', concentration: true, durationRounds: 100 }) },
  },
  {
    id: 'feather-fall', name: 'Feather Fall', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:2964',
    castingTime: 'reaction', components: materialWith('a small feather or piece of down', { verbal: true, somatic: false }),
    targeting: { kind: 'multiple', rangeFeet: 60, baseMaximum: 5, additionalPerSlot: 0 },
    operation: { kind: 'effect', effect: effect({ kind: 'falling_protection', descentFeetPerRound: 60, preventsLandingDamage: true }, { durationRounds: 10 }) },
  },
  {
    id: 'find-familiar', name: 'Find Familiar', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:2979',
    castingTime: 'hour', ritual: true, components: material('burning incense worth 10+ GP', true),
    targeting: { kind: 'utility', rangeFeet: 10 },
    operation: { kind: 'utility', effect: { kind: 'summoned_familiar', forms: ['Bat', 'Cat', 'Frog', 'Hawk', 'Lizard', 'Octopus', 'Owl', 'Rat', 'Raven', 'Spider', 'Weasel', 'other CR 0 Beast'], telepathyFeet: 100 }, concentration: false, durationRounds: null, stateful: true },
  },
  {
    id: 'floating-disk', name: 'Floating Disk', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:3335',
    castingTime: 'action', ritual: true, components: material('a drop of mercury'),
    targeting: { kind: 'utility', rangeFeet: 30 },
    operation: { kind: 'utility', effect: { kind: 'floating_disk', diameterFeet: 3, heightFeet: 3, capacityPounds: 500, followDistanceFeet: 20, maximumDistanceFeet: 100 }, concentration: false, durationRounds: 600 },
  },
  {
    id: 'fog-cloud', name: 'Fog Cloud', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:3396',
    castingTime: 'action', components: VS,
    targeting: { kind: 'area', rangeFeet: 120, shape: 'sphere', baseSizeFeet: 20, sizePerSlotFeet: 20 },
    operation: { kind: 'utility', effect: { kind: 'obscured_area', placement: 'selected_when_cast', radiusFeet: 20, obscurement: 'heavy', dispersedByStrongWind: true }, concentration: true, durationRounds: 600 },
  },
  {
    id: 'grease', name: 'Grease', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:3883',
    castingTime: 'action', components: material('a bit of pork rind or butter'),
    targeting: { kind: 'area', rangeFeet: 60, shape: 'cube', baseSizeFeet: 10, sizePerSlotFeet: 0 },
    operation: { kind: 'save_effect', ability: 'dexterity', rollMode: 'normal', effect: effect({ kind: 'condition', condition: 'Prone' }, { durationRounds: 10, expiresAt: 'target_end' }) },
  },
  {
    id: 'hideous-laughter', name: 'Hideous Laughter', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:4294',
    castingTime: 'action', components: material('a tart and a feather'),
    targeting: { kind: 'multiple', rangeFeet: 30, baseMaximum: 1, additionalPerSlot: 1 },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'normal', effect: effect({ kind: 'condition_bundle', conditions: ['Prone', 'Incapacitated'] }, { concentration: true, durationRounds: 10, expiresAt: 'target_end' }) },
  },
  {
    id: 'ice-knife', name: 'Ice Knife', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:4430',
    castingTime: 'action', components: materialWith('a drop of water or a piece of ice', { verbal: false, somatic: true }),
    targeting: { kind: 'single', rangeFeet: 60, willing: false },
    operation: { kind: 'attack_then_save_damage', attackKind: 'ranged', attackDamageType: damageType('Piercing'), attackDice: dice(1, 10), saveAbility: 'dexterity', saveDamageType: damageType('Cold'), saveDice: dice(2, 6, { perSlotCount: 1 }), onSaveSuccess: 'none', burstShape: 'sphere', burstRadiusFeet: 5 },
  },
  {
    id: 'identify', name: 'Identify', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:4476',
    castingTime: 'minute', ritual: true, components: material('a pearl worth 100+ GP'),
    targeting: { kind: 'utility', rangeFeet: 5 },
    operation: { kind: 'utility', effect: { kind: 'magic_identification', identifiesPropertiesChargesAndSpells: true }, concentration: false, durationRounds: null },
  },
  {
    id: 'illusory-script', name: 'Illusory Script', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:4495',
    castingTime: 'minute', ritual: true, components: materialWith('ink worth 10+ GP', { verbal: false, somatic: true }, true),
    targeting: { kind: 'utility', rangeFeet: 5 },
    operation: { kind: 'utility', effect: { kind: 'illusory_script', truesightReadsHiddenMessage: true }, concentration: false, durationRounds: 144000 },
  },
  {
    id: 'jump', name: 'Jump', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:4710',
    castingTime: 'bonus_action', components: material('a grasshopper\'s hind leg'),
    targeting: { kind: 'multiple', rangeFeet: 5, baseMaximum: 1, additionalPerSlot: 1 },
    operation: { kind: 'effect', effect: effect({ kind: 'jump_movement', jumpFeet: 30, movementCostFeet: 10, usesPerTurn: 1 }, { durationRounds: 10 }) },
  },
  {
    id: 'longstrider', name: 'Longstrider', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:4904',
    castingTime: 'action', components: material('a pinch of dirt'),
    targeting: { kind: 'multiple', rangeFeet: 5, baseMaximum: 1, additionalPerSlot: 1 },
    operation: { kind: 'effect', effect: effect({ kind: 'movement_modifier', speedDeltaFeet: 10 }, { durationRounds: 600 }) },
  },
  {
    id: 'mage-armor', name: 'Mage Armor', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:4920',
    castingTime: 'action', components: material('a piece of cured leather'),
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'base_armor_class', base: 13, addsDexterityModifier: true, requiresUnarmored: true }, { durationRounds: 4800 }) },
  },
  {
    id: 'protection-from-evil-and-good', name: 'Protection from Evil and Good', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:6337',
    castingTime: 'action', components: material('a flask of Holy Water worth 25+ GP', true),
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'creature_type_protection', creatureTypes: ['Aberration', 'Celestial', 'Elemental', 'Fey', 'Fiend', 'Undead'] }, { concentration: true, durationRounds: 100 }) },
  },
  {
    id: 'purify-food-and-drink', name: 'Purify Food and Drink', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:6369',
    castingTime: 'action', ritual: true, components: VS,
    targeting: { kind: 'area', rangeFeet: 10, shape: 'sphere', baseSizeFeet: 5, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'food_purification', placement: 'selected_when_cast', radiusFeet: 5, removesPoisonAndRot: true }, concentration: false, durationRounds: null },
  },
  {
    id: 'ray-of-sickness', name: 'Ray of Sickness', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:6456',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 60, willing: false },
    operation: { kind: 'attack_damage', attackKind: 'ranged', damageType: damageType('Poison'), dice: dice(2, 8, { perSlotCount: 1 }), rider: effect({ kind: 'condition', condition: 'Poisoned' }, { durationRounds: 2, expiresAt: 'source_end' }) },
  },
  {
    id: 'sanctuary', name: 'Sanctuary', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:6662',
    castingTime: 'bonus_action', components: material('a shard of glass from a mirror'),
    targeting: { kind: 'single', rangeFeet: 30, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'sanctuary', saveAbility: 'wisdom' }, { durationRounds: 10 }) },
  },
  {
    id: 'silent-image', name: 'Silent Image', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:7042',
    castingTime: 'action', components: material('a bit of fleece'),
    targeting: { kind: 'area', rangeFeet: 60, shape: 'cube', baseSizeFeet: 15, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'image_illusion', placement: 'selected_when_cast', maximumCubeFeet: 15, movableByMagicAction: true, investigationAgainstSpellDc: true }, concentration: true, durationRounds: 100 },
  },
  {
    id: 'sleep', name: 'Sleep', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:7103',
    castingTime: 'action', components: material('a pinch of sand or rose petals'),
    targeting: { kind: 'area', rangeFeet: 60, shape: 'sphere', baseSizeFeet: 5, sizePerSlotFeet: 0 },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'normal', effect: effect({ kind: 'sleep_sequence', initial: 'Incapacitated', failedRepeat: 'Unconscious' }, { concentration: true, durationRounds: 10, expiresAt: 'target_end' }), excludeCaster: true },
  },
  {
    id: 'unseen-servant', name: 'Unseen Servant', level: 1,
    source: 'docs/srd/source/spell-descriptions.txt:8131',
    castingTime: 'action', ritual: true, components: material('a bit of string and of wood'),
    targeting: { kind: 'utility', rangeFeet: 60 },
    operation: { kind: 'utility', effect: { kind: 'unseen_servant', armorClass: 10, hitPoints: 1, strength: 2, moveFeetPerBonusAction: 15, maximumDistanceFeet: 60 }, concentration: false, durationRounds: 600 },
  },
  {
    id: 'acid-arrow', name: 'Acid Arrow', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:20',
    castingTime: 'action', components: material('powdered rhubarb leaf'),
    targeting: { kind: 'single', rangeFeet: 90, willing: false },
    operation: { kind: 'attack_damage_over_time', attackKind: 'ranged', damageType: damageType('Acid'), initialDice: dice(4, 4, { perSlotCount: 1 }), missDamage: 'half_initial', laterDice: dice(2, 4, { perSlotCount: 1 }), laterTiming: 'target_end' },
  },
  {
    id: 'aid', name: 'Aid', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:53',
    castingTime: 'action', components: material('a strip of white cloth'),
    targeting: { kind: 'multiple', rangeFeet: 30, baseMaximum: 3, additionalPerSlot: 0 },
    operation: { kind: 'hit_point_maximum_increase', baseAmount: 5, additionalPerSlot: 5 },
  },
  {
    id: 'alter-self', name: 'Alter Self', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:101',
    castingTime: 'action', components: VS,
    targeting: { kind: 'self' },
    operation: { kind: 'utility', effect: { kind: 'form_alteration', options: ['aquatic_adaptation', 'change_appearance', 'natural_weapons'], naturalWeaponCount: 1, naturalWeaponSides: 6 }, concentration: true, durationRounds: 600 },
  },
  {
    id: 'arcane-lock', name: 'Arcane Lock', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:479',
    castingTime: 'action', components: material('gold dust worth 25+ GP', true),
    targeting: { kind: 'utility', rangeFeet: 5 },
    operation: { kind: 'utility', effect: { kind: 'arcane_lock', passwordRangeFeet: 5, passwordUnlockRounds: 10 }, concentration: false, durationRounds: null, stateful: true },
  },
  {
    id: 'arcanists-magic-aura', name: 'Arcanist’s Magic Aura', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:527',
    castingTime: 'action', components: material('a small square of silk'),
    targeting: { kind: 'utility', rangeFeet: 5 },
    operation: { kind: 'utility', effect: { kind: 'magic_aura', options: ['mask', 'false_aura'], permanentAfterDailyCastings: 30 }, concentration: false, durationRounds: 14400 },
  },
  {
    id: 'augury', name: 'Augury', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:595',
    castingTime: 'minute', ritual: true, components: material('specially marked sticks, bones, cards, or other divinatory tokens worth 25+ GP'),
    targeting: { kind: 'self' },
    operation: { kind: 'utility', effect: { kind: 'augury', forecastMinutes: 30, noAnswerChancePerExtraCastingPercent: 25 }, concentration: false, durationRounds: null },
  },
  {
    id: 'blindness-deafness', name: 'Blindness/Deafness', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:859',
    castingTime: 'action', components: V,
    targeting: { kind: 'multiple', rangeFeet: 120, baseMaximum: 1, additionalPerSlot: 1 },
    operation: { kind: 'save_effect', ability: 'constitution', rollMode: 'normal', effect: effect({ kind: 'condition_choice', conditions: ['Blinded', 'Deafened'] }, { durationRounds: 10, expiresAt: 'target_end', repeatedSave: { ability: 'constitution', rollMode: 'normal', timing: 'target_end' } }) },
  },
  {
    id: 'blur', name: 'Blur', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:907',
    castingTime: 'action', components: V,
    targeting: { kind: 'self' },
    operation: { kind: 'effect', effect: effect({ kind: 'attacks_against_target_roll_mode', mode: 'disadvantage', bypassedBy: ['Blindsight', 'Truesight'] }, { target: 'self', concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'calm-emotions', name: 'Calm Emotions', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:972',
    castingTime: 'action', components: VS,
    targeting: { kind: 'area', rangeFeet: 60, shape: 'sphere', baseSizeFeet: 20, sizePerSlotFeet: 0 },
    operation: { kind: 'save_effect', ability: 'charisma', rollMode: 'normal', effect: effect({ kind: 'calm_emotions', options: ['suppress_charmed_frightened', 'indifferent'] }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'continual-flame', name: 'Continual Flame', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:1647',
    castingTime: 'action', components: material('ruby dust worth 50+ GP', true),
    targeting: { kind: 'utility', rangeFeet: 5 },
    operation: { kind: 'utility', effect: { kind: 'light_source', brightFeet: 20, dimFeet: 20, maximumLights: 1, moveFeetPerBonusAction: 0 }, concentration: false, durationRounds: null, stateful: true },
  },
  {
    id: 'darkness', name: 'Darkness', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:1929',
    castingTime: 'action', components: materialWith('bat fur and a piece of coal', { verbal: true, somatic: false }),
    targeting: { kind: 'area', rangeFeet: 60, shape: 'sphere', baseSizeFeet: 15, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'obscured_area', placement: 'selected_when_cast', radiusFeet: 15, obscurement: 'magical_darkness', dispersedByStrongWind: false, blocksDarkvision: true, suppressesLightSpellLevelAtMost: 2 }, concentration: true, durationRounds: 100 },
  },
  {
    id: 'darkvision', name: 'Darkvision', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:1952',
    castingTime: 'action', components: material('a dried carrot'),
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'darkvision', rangeFeet: 150 }, { durationRounds: 4800 }) },
  },
  {
    id: 'detect-thoughts', name: 'Detect Thoughts', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:2119',
    castingTime: 'action', components: material('1 Copper Piece'),
    targeting: { kind: 'self' },
    operation: { kind: 'utility', effect: { kind: 'detect_thoughts', radiusFeet: 30, probeSaveAbility: 'wisdom', escapeCheckAbility: 'intelligence', escapeCheckSkill: 'Arcana' }, concentration: true, durationRounds: 10 },
  },
  {
    id: 'dragons-breath', name: 'Dragon’s Breath', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:2492',
    castingTime: 'bonus_action', components: material('a hot pepper'),
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'granted_breath', damageTypes: ['Acid', 'Cold', 'Fire', 'Lightning', 'Poison'], coneFeet: 15, saveAbility: 'dexterity', onSuccess: 'half', dice: { baseCount: 3, sides: 6, perSlotCount: 1 } }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'enhance-ability', name: 'Enhance Ability', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:2660',
    castingTime: 'action', components: material('fur or a feather'),
    targeting: { kind: 'multiple', rangeFeet: 5, baseMaximum: 1, additionalPerSlot: 1 },
    operation: { kind: 'effect', effect: effect({ kind: 'ability_check_advantage', ability: 'chosen_when_cast' }, { concentration: true, durationRounds: 600 }) },
  },
  {
    id: 'enlarge-reduce', name: 'Enlarge/Reduce', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:2679',
    castingTime: 'action', components: material('a pinch of powdered iron'),
    targeting: { kind: 'single', rangeFeet: 30, willing: false },
    operation: { kind: 'effect', effect: effect({ kind: 'size_alteration', options: ['enlarge', 'reduce'], sizeCategoryDelta: 1, damageDieCount: 1, damageDieSides: 4 }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'find-traps', name: 'Find Traps', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:3131',
    castingTime: 'action', components: VS,
    targeting: { kind: 'utility', rangeFeet: 120 },
    operation: { kind: 'utility', effect: { kind: 'trap_detection', rangeFeet: 120, revealsLocation: false }, concentration: false, durationRounds: null },
  },
  {
    id: 'flaming-sphere', name: 'Flaming Sphere', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:3276',
    castingTime: 'action', components: material('a ball of wax'),
    targeting: { kind: 'area', rangeFeet: 60, shape: 'sphere', baseSizeFeet: 2.5, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'flaming_sphere', placement: 'selected_when_cast', diameterFeet: 5, damageCount: 2, damageSides: 6, damagePerSlotCount: 1, moveFeetPerBonusAction: 30, brightFeet: 20, dimFeet: 20 }, concentration: true, durationRounds: 10 },
  },
  {
    id: 'gentle-repose', name: 'Gentle Repose', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:3682',
    castingTime: 'action', ritual: true, components: material('2 Copper Pieces', true),
    targeting: { kind: 'utility', rangeFeet: 5 },
    operation: { kind: 'utility', effect: { kind: 'corpse_preservation', preventsDecayAndUndeath: true }, concentration: false, durationRounds: 144000 },
  },
  {
    id: 'gust-of-wind', name: 'Gust of Wind', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:4027',
    castingTime: 'action', components: material('a legume seed'),
    targeting: { kind: 'area', rangeFeet: 0, shape: 'line', baseSizeFeet: 60, sizePerSlotFeet: 0, secondarySizeFeet: 10 },
    operation: { kind: 'save_push', ability: 'strength', pushFeetOnFailure: 15, effect: effect({ kind: 'gust_of_wind_area', placement: 'selected_when_cast', widthFeet: 10, movementCostMultiplierTowardSource: 2, dispersesGas: true, unprotectedFlameExtinguished: true }, { target: 'self', concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'hold-person', name: 'Hold Person', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:4342',
    castingTime: 'action', components: material('a straight piece of iron'),
    targeting: { kind: 'multiple', rangeFeet: 60, baseMaximum: 1, additionalPerSlot: 1 },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'normal', effect: effect({ kind: 'condition', condition: 'Paralyzed' }, { concentration: true, durationRounds: 10, expiresAt: 'target_end', repeatedSave: { ability: 'wisdom', rollMode: 'normal', timing: 'target_end' } }) },
  },
  {
    id: 'invisibility', name: 'Invisibility', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:4691',
    castingTime: 'action', components: material('an eyelash in gum arabic'),
    targeting: { kind: 'multiple', rangeFeet: 5, baseMaximum: 1, additionalPerSlot: 1 },
    operation: { kind: 'effect', effect: effect({ kind: 'condition', condition: 'Invisible' }, { concentration: true, durationRounds: 600 }) },
  },
  {
    id: 'knock', name: 'Knock', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:4734',
    castingTime: 'action', components: V,
    targeting: { kind: 'utility', rangeFeet: 60 },
    operation: { kind: 'utility', effect: { kind: 'object_unlock', arcaneLockSuppressionRounds: 100, audibleRangeFeet: 300, unlocksOneLock: true }, concentration: false, durationRounds: null },
  },
  {
    id: 'lesser-restoration', name: 'Lesser Restoration', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:4774',
    castingTime: 'bonus_action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'remove_condition', conditions: ['Blinded', 'Deafened', 'Paralyzed', 'Poisoned'] },
  },
  {
    id: 'levitate', name: 'Levitate', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:4788',
    castingTime: 'action', components: material('a metal spring'),
    targeting: { kind: 'single', rangeFeet: 60, willing: false },
    operation: { kind: 'save_effect', ability: 'constitution', rollMode: 'normal', effect: effect({ kind: 'levitation', initialRiseFeet: 20, maximumWeightPounds: 500, altitudeChangeFeetPerTurn: 20 }, { concentration: true, durationRounds: 100 }) },
  },
  {
    id: 'locate-object', name: 'Locate Object', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:4881',
    castingTime: 'action', components: material('a forked twig'),
    targeting: { kind: 'self' },
    operation: { kind: 'utility', effect: { kind: 'object_location', radiusFeet: 1000, familiarityDistanceFeet: 30, blockedByLead: true }, concentration: true, durationRounds: 100 },
  },
  {
    id: 'magic-mouth', name: 'Magic Mouth', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:5048',
    castingTime: 'minute', ritual: true, components: material('jade dust worth 10+ GP', true),
    targeting: { kind: 'utility', rangeFeet: 30 },
    operation: { kind: 'utility', effect: { kind: 'magic_mouth', maximumWords: 25, maximumMessageRounds: 100, triggerRadiusFeet: 30 }, concentration: false, durationRounds: null, stateful: true },
  },
  {
    id: 'magic-weapon', name: 'Magic Weapon', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:5081',
    castingTime: 'bonus_action', components: VS,
    targeting: { kind: 'self' },
    operation: { kind: 'effect', effect: effect({ kind: 'magic_weapon', baseBonus: 1, levelThreeBonus: 2, levelSixBonus: 3 }, { target: 'self', durationRounds: 600 }) },
  },
  {
    id: 'mind-spike', name: 'Mind Spike', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:5398',
    castingTime: 'action', components: S,
    targeting: { kind: 'single', rangeFeet: 120, willing: false },
    operation: { kind: 'save_damage', ability: 'wisdom', onSuccess: 'half', damageType: damageType('Psychic'), dice: dice(3, 8, { perSlotCount: 1 }), riderOnFailure: effect({ kind: 'location_tracking', samePlaneOnly: true, negatesHiddenAndInvisibleBenefits: true }, { concentration: true, durationRounds: 600 }), pushFeetOnFailure: 0 },
  },
  {
    id: 'mirror-image', name: 'Mirror Image', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:5481',
    castingTime: 'action', components: VS,
    targeting: { kind: 'self' },
    operation: { kind: 'effect', effect: effect({ kind: 'mirror_images', duplicates: 3, interceptionDieSides: 6, interceptionMinimum: 3 }, { target: 'self', durationRounds: 10 }) },
  },
  {
    id: 'misty-step', name: 'Misty Step', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:5523',
    castingTime: 'bonus_action', components: V,
    targeting: { kind: 'self' },
    operation: { kind: 'utility', effect: { kind: 'teleport', maximumDistanceFeet: 30, requiresVisibleUnoccupiedSpace: true }, concentration: false, durationRounds: null },
  },
  {
    id: 'prayer-of-healing', name: 'Prayer of Healing', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:6014',
    castingTime: 'ten_minutes', components: V,
    targeting: { kind: 'multiple', rangeFeet: 30, baseMaximum: 5, additionalPerSlot: 0 },
    operation: { kind: 'healing', dice: dice(2, 8, { perSlotCount: 1 }), addSpellcastingModifier: false },
  },
  {
    id: 'protection-from-poison', name: 'Protection from Poison', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:6359',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'remove_condition_and_effect', condition: 'Poisoned', effect: effect({ kind: 'poison_protection', saveMode: 'advantage', resistanceType: 'Poison' }, { durationRounds: 600 }) },
  },
  {
    id: 'ray-of-enfeeblement', name: 'Ray of Enfeeblement', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:6407',
    castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 60, willing: false },
    operation: { kind: 'save_branch_effect', ability: 'constitution', successEffect: effect({ kind: 'ray_enfeeblement', branch: 'success', damagePenaltyCount: 0, damagePenaltySides: 8 }, { concentration: true, durationRounds: 1, expiresAt: 'source_start' }), failureEffect: effect({ kind: 'ray_enfeeblement', branch: 'failure', damagePenaltyCount: 1, damagePenaltySides: 8 }, { concentration: true, durationRounds: 10, expiresAt: 'target_end', repeatedSave: { ability: 'constitution', rollMode: 'normal', timing: 'target_end' } }) },
  },
  {
    id: 'rope-trick', name: 'Rope Trick', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:6619',
    castingTime: 'action', components: material('a segment of rope'),
    targeting: { kind: 'utility', rangeFeet: 5 },
    operation: { kind: 'utility', effect: { kind: 'rope_trick', portalWidthFeet: 3, portalHeightFeet: 5, maximumCreatures: 8 }, concentration: false, durationRounds: 600 },
  },
  {
    id: 'scorching-ray', name: 'Scorching Ray', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:6678',
    castingTime: 'action', components: VS,
    targeting: { kind: 'multiple', rangeFeet: 120, baseMaximum: 3, additionalPerSlot: 1 },
    operation: { kind: 'attack_rays', baseRays: 3, additionalPerSlot: 1, damageType: damageType('Fire'), dice: dice(2, 6) },
  },
  {
    id: 'see-invisibility', name: 'See Invisibility', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:6784',
    castingTime: 'action', components: material('a pinch of talc'),
    targeting: { kind: 'self' },
    operation: { kind: 'effect', effect: effect({ kind: 'see_invisibility', seesEtherealPlane: true }, { target: 'self', durationRounds: 600 }) },
  },
  {
    id: 'shatter', name: 'Shatter', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:6921',
    castingTime: 'action', components: material('a chip of mica'),
    targeting: { kind: 'area', rangeFeet: 60, shape: 'sphere', baseSizeFeet: 10, sizePerSlotFeet: 0 },
    operation: { kind: 'save_damage', ability: 'constitution', onSuccess: 'half', damageType: damageType('Thunder'), dice: dice(3, 8, { perSlotCount: 1 }), riderOnFailure: null, pushFeetOnFailure: 0 },
  },
  {
    id: 'silence', name: 'Silence', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:7026',
    castingTime: 'action', ritual: true, components: VS,
    targeting: { kind: 'area', rangeFeet: 120, shape: 'sphere', baseSizeFeet: 20, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'silence_area', placement: 'selected_when_cast', radiusFeet: 20, thunderImmune: true, verbalComponentsImpossible: true }, concentration: true, durationRounds: 100 },
  },
  {
    id: 'spider-climb', name: 'Spider Climb', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:7278',
    castingTime: 'action', components: material('a drop of bitumen and a spider'),
    targeting: { kind: 'multiple', rangeFeet: 5, baseMaximum: 1, additionalPerSlot: 1 },
    operation: { kind: 'effect', effect: effect({ kind: 'spider_climb', climbSpeedEqualsSpeed: true, handsFree: true }, { concentration: true, durationRounds: 600 }) },
  },
  {
    id: 'spiritual-weapon', name: 'Spiritual Weapon', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:7353',
    castingTime: 'bonus_action', components: VS,
    targeting: { kind: 'single', rangeFeet: 60, willing: false },
    operation: { kind: 'summoned_weapon_attack', damageType: damageType('Force'), dice: dice(1, 8, { perSlotCount: 1 }), addSpellcastingModifier: true, attackReachFeet: 5, moveFeetPerBonusAction: 20, effect: effect({ kind: 'spiritual_weapon', moveFeetPerBonusAction: 20, attackReachFeet: 5 }, { target: 'self', concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'suggestion', name: 'Suggestion', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:7477',
    castingTime: 'action', components: materialWith('a drop of honey', { verbal: true, somatic: false }),
    targeting: { kind: 'single', rangeFeet: 30, willing: false },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'normal', effect: effect({ kind: 'condition', condition: 'Charmed' }, { concentration: true, durationRounds: 4800 }) },
  },
  {
    id: 'warding-bond', name: 'Warding Bond', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:8388',
    castingTime: 'action', components: material('a pair of platinum rings worth 50+ GP each, which you and the target must wear for the duration'),
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'warding_bond', maximumDistanceFeet: 60, armorClassBonus: 1, savingThrowBonus: 1, resistanceToAllDamage: true, mirrorsDamageToSource: true }, { durationRounds: 600 }) },
  },
  {
    id: 'web', name: 'Web', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:8453',
    castingTime: 'action', components: material('a bit of spiderweb'),
    targeting: { kind: 'area', rangeFeet: 60, shape: 'cube', baseSizeFeet: 20, sizePerSlotFeet: 0 },
    operation: { kind: 'save_effect', ability: 'dexterity', rollMode: 'normal', effect: effect({ kind: 'web_area', placement: 'selected_when_cast', cubeFeet: 20, flatDepthFeet: 5, fireDamageCount: 2, fireDamageSides: 4 }, { concentration: true, durationRounds: 600 }) },
  },
  {
    id: 'zone-of-truth', name: 'Zone of Truth', level: 2,
    source: 'docs/srd/source/spell-descriptions.txt:8699',
    castingTime: 'action', components: VS,
    targeting: { kind: 'area', rangeFeet: 60, shape: 'sphere', baseSizeFeet: 15, sizePerSlotFeet: 0 },
    operation: { kind: 'save_effect', ability: 'charisma', rollMode: 'normal', effect: effect({ kind: 'truth_zone', placement: 'selected_when_cast', radiusFeet: 15, saveAbility: 'charisma' }, { durationRounds: 100 }) },
  },
  {
    id: 'animate-dead', name: 'Animate Dead', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:219', castingTime: 'minute', components: material('a drop of blood, a piece of flesh, and a pinch of bone dust'),
    targeting: { kind: 'utility', rangeFeet: 10 },
    operation: { kind: 'utility', effect: { kind: 'summoned_undead', forms: ['Skeleton', 'Zombie'], createdCreatures: 1, createdCreaturesPerSlot: 2, reassertedCreatures: 4, reassertedCreaturesPerSlot: 2, commandRangeFeet: 60, controlDurationRounds: 14400 }, concentration: false, durationRounds: null, stateful: true },
  },
  {
    id: 'beacon-of-hope', name: 'Beacon of Hope', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:726', castingTime: 'action', components: VS,
    targeting: { kind: 'all_in_range', rangeFeet: 30 },
    operation: { kind: 'effect', effect: effect({ kind: 'beacon_of_hope', wisdomSaveMode: 'advantage', deathSaveMode: 'advantage', maximizesHealing: true }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'bestow-curse', name: 'Bestow Curse', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:753', castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: false },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'normal', effect: effect({ kind: 'bestow_curse', options: ['ability_disadvantage', 'attacks_against_caster_disadvantage', 'forced_dodge', 'extra_necrotic_damage'], extraDamageCount: 1, extraDamageSides: 8 }, { concentration: true, durationRounds: 10, durationRoundsPerSlot: 90 }) },
  },
  {
    id: 'blink', name: 'Blink', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:878', castingTime: 'action', components: VS,
    targeting: { kind: 'self' },
    operation: { kind: 'effect', effect: effect({ kind: 'blink', dieSides: 6, etherealMinimum: 4, etherealVisionFeet: 60, returnSpaceFeet: 10 }, { target: 'self', durationRounds: 10 }) },
  },
  {
    id: 'clairvoyance', name: 'Clairvoyance', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:1121', castingTime: 'ten_minutes', components: material('a focus worth 100+ GP, either a jeweled horn for hearing or a glass eye for seeing'),
    targeting: { kind: 'utility', rangeFeet: 5280 },
    operation: { kind: 'utility', effect: { kind: 'clairvoyance_sensor', rangeFeet: 5280, senses: ['hearing', 'seeing'], switchCost: 'bonus_action' }, concentration: true, durationRounds: 100 },
  },
  {
    id: 'counterspell', name: 'Counterspell', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:1767', castingTime: 'reaction', components: S,
    targeting: { kind: 'single', rangeFeet: 60, willing: false },
    operation: { kind: 'reaction_save_cancel', ability: 'constitution' },
  },
  {
    id: 'create-food-and-water', name: 'Create Food and Water', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:1781', castingTime: 'action', components: VS,
    targeting: { kind: 'utility', rangeFeet: 30 },
    operation: { kind: 'utility', effect: { kind: 'created_food_and_water', foodPounds: 45, waterGallons: 30, foodSpoilsAfterRounds: 14400 }, concentration: false, durationRounds: null, stateful: true },
  },
  {
    id: 'daylight', name: 'Daylight', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:1967', castingTime: 'action', components: VS,
    targeting: { kind: 'area', rangeFeet: 60, shape: 'sphere', baseSizeFeet: 60, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'daylight_area', placement: 'selected_when_cast', brightRadiusFeet: 60, additionalDimFeet: 60, dispelsDarknessSpellLevelAtMost: 3 }, concentration: false, durationRounds: 600 },
  },
  {
    id: 'dispel-magic', name: 'Dispel Magic', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:2268', castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 120, willing: false },
    operation: { kind: 'dispel_magic', baseAutomaticLevel: 3, checkDcBase: 10 },
  },
  {
    id: 'fear', name: 'Fear', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:2945', castingTime: 'action', components: material('a white feather'),
    targeting: { kind: 'area', rangeFeet: 0, shape: 'cone', baseSizeFeet: 30, sizePerSlotFeet: 0 },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'normal', effect: effect({ kind: 'fear', condition: 'Frightened', dropsHeldObjects: true, forcedAction: 'dash_away', repeatSaveAbility: 'wisdom', repeatSaveRequiresNoLineOfSight: true }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'fireball', name: 'Fireball', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:3160', castingTime: 'action', components: material('a ball of bat guano and sulfur'),
    targeting: { kind: 'area', rangeFeet: 150, shape: 'sphere', baseSizeFeet: 20, sizePerSlotFeet: 0 },
    operation: { kind: 'save_damage', ability: 'dexterity', onSuccess: 'half', damageType: damageType('Fire'), dice: dice(8, 6, { perSlotCount: 1 }), riderOnFailure: null, pushFeetOnFailure: 0 },
  },
  {
    id: 'fly', name: 'Fly', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:3375', castingTime: 'action', components: material('a feather'),
    targeting: { kind: 'multiple', rangeFeet: 5, baseMaximum: 1, additionalPerSlot: 1, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'flight', speedFeet: 60, canHover: true, fallsWhenEffectEnds: true }, { concentration: true, durationRounds: 100 }) },
  },
  {
    id: 'gaseous-form', name: 'Gaseous Form', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:3590', castingTime: 'action', components: material('a bit of gauze'),
    targeting: { kind: 'multiple', rangeFeet: 5, baseMaximum: 1, additionalPerSlot: 1, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'gaseous_form', flySpeedFeet: 10, canHover: true, physicalResistanceTypes: ['Bludgeoning', 'Piercing', 'Slashing'], proneImmune: true, physicalSaveMode: 'advantage', canAttackOrCast: false }, { concentration: true, durationRounds: 600 }) },
  },
  {
    id: 'glyph-of-warding', name: 'Glyph of Warding', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:3802', castingTime: 'hour', components: material('powdered diamond worth 200+ GP', true),
    targeting: { kind: 'area', rangeFeet: 5, shape: 'sphere', baseSizeFeet: 5, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'glyph_of_warding', placement: 'selected_when_cast', maximumDiameterFeet: 10, movementBreakDistanceFeet: 10, explosiveRadiusFeet: 20, explosiveDamageTypes: ['Acid', 'Cold', 'Fire', 'Lightning', 'Thunder'], explosiveDamageCount: 5, explosiveDamageSides: 8, explosiveDamagePerSlotCount: 1, storedSpellMaximumLevel: 3 }, concentration: false, durationRounds: null, stateful: true },
  },
  {
    id: 'haste', name: 'Haste', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:4143', castingTime: 'action', components: material('a shaving of licorice root'),
    targeting: { kind: 'single', rangeFeet: 30, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'haste', speedMultiplier: 2, armorClassBonus: 2, dexteritySaveMode: 'advantage', extraActionOptions: ['attack_once', 'dash', 'disengage', 'hide', 'utilize'], lethargyCondition: 'Incapacitated', lethargySpeedFeet: 0, lethargyRounds: 1 }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'hypnotic-pattern', name: 'Hypnotic Pattern', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:4410', castingTime: 'action', components: materialWith('a pinch of confetti', { verbal: false, somatic: true }),
    targeting: { kind: 'area', rangeFeet: 120, shape: 'cube', baseSizeFeet: 30, sizePerSlotFeet: 0 },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'normal', effect: effect({ kind: 'hypnotic_pattern', conditions: ['Charmed', 'Incapacitated'], speedFeet: 0, endsOnDamage: true, wakeAction: true }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'lightning-bolt', name: 'Lightning Bolt', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:4831', castingTime: 'action', components: material('a bit of fur and a crystal rod'),
    targeting: { kind: 'area', rangeFeet: 0, shape: 'line', baseSizeFeet: 100, sizePerSlotFeet: 0, secondarySizeFeet: 5 },
    operation: { kind: 'save_damage', ability: 'dexterity', onSuccess: 'half', damageType: damageType('Lightning'), dice: dice(8, 6, { perSlotCount: 1 }), riderOnFailure: null, pushFeetOnFailure: 0 },
  },
  {
    id: 'magic-circle', name: 'Magic Circle', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:4952', castingTime: 'minute', components: material('salt and powdered silver worth 100+ GP', true),
    targeting: { kind: 'area', rangeFeet: 10, shape: 'cylinder', baseSizeFeet: 10, sizePerSlotFeet: 0, secondarySizeFeet: 20 },
    operation: { kind: 'utility', effect: { kind: 'magic_circle', placement: 'selected_when_cast', radiusFeet: 10, heightFeet: 20, creatureTypes: ['Celestial', 'Elemental', 'Fey', 'Fiend', 'Undead'], reversible: true }, concentration: false, durationRounds: 600, durationRoundsPerSlot: 600 },
  },
  {
    id: 'major-image', name: 'Major Image', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:5150', castingTime: 'action', components: material('a bit of fleece'),
    targeting: { kind: 'area', rangeFeet: 120, shape: 'cube', baseSizeFeet: 20, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'major_image', placement: 'selected_when_cast', maximumCubeFeet: 20, sensoryModes: ['visual', 'sound', 'smell', 'temperature'], movableByMagicAction: true, investigationAgainstSpellDc: true }, concentration: true, durationRounds: 100, becomesPermanentAtSlot: 4, losesConcentrationAtSlot: 4 },
  },
  {
    id: 'mass-healing-word', name: 'Mass Healing Word', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:5226', castingTime: 'bonus_action', components: V,
    targeting: { kind: 'multiple', rangeFeet: 60, baseMaximum: 6, additionalPerSlot: 0 },
    operation: { kind: 'healing', dice: dice(2, 4, { perSlotCount: 1 }), addSpellcastingModifier: true },
  },
  {
    id: 'meld-into-stone', name: 'Meld into Stone', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:5289', castingTime: 'action', ritual: true, components: VS,
    targeting: { kind: 'self' },
    operation: { kind: 'utility', effect: { kind: 'meld_into_stone', exitMovementFeet: 5, partialDestructionDamageCount: 6, partialDestructionDamageSides: 6, totalDestructionDamage: 50, expelledCondition: 'Prone' }, concentration: false, durationRounds: 4800 },
  },
  {
    id: 'nondetection', name: 'Nondetection', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:5647', castingTime: 'action', components: material('a pinch of diamond dust worth 25+ GP', true),
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'nondetection', blocksDivinationTargeting: true, blocksMagicalScryingSensors: true, maximumObjectDimensionFeet: 10 }, { durationRounds: 4800 }) },
  },
  {
    id: 'phantom-steed', name: 'Phantom Steed', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:5758', castingTime: 'minute', ritual: true, components: VS,
    targeting: { kind: 'utility', rangeFeet: 30 },
    operation: { kind: 'utility', effect: { kind: 'phantom_steed', speedFeet: 100, travelMilesPerHour: 13, equipmentVanishDistanceFeet: 10, fadeRounds: 10 }, concentration: false, durationRounds: 600 },
  },
  {
    id: 'protection-from-energy', name: 'Protection from Energy', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:6322', castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'energy_protection', damageTypes: ['Acid', 'Cold', 'Fire', 'Lightning', 'Thunder'], selectedDamageType: 'chosen_when_cast' }, { concentration: true, durationRounds: 600 }) },
  },
  {
    id: 'remove-curse', name: 'Remove Curse', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:6499', castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: true }, operation: { kind: 'remove_curse' },
  },
  {
    id: 'revivify', name: 'Revivify', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:6604', castingTime: 'action', components: material('a diamond worth 300+ GP', true),
    targeting: { kind: 'single', rangeFeet: 5, willing: true, allowDead: true },
    operation: { kind: 'revive', hitPoints: 1, maximumDeathAgeRounds: 10 },
  },
  {
    id: 'sending', name: 'Sending', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:6825', castingTime: 'action', components: material('a copper wire'),
    targeting: { kind: 'remote', range: 'unlimited' },
    operation: { kind: 'utility', effect: { kind: 'sending', maximumWords: 25, crossPlaneFailurePercent: 5, recipientBlockRounds: 4800 }, concentration: false, durationRounds: null },
  },
  {
    id: 'sleet-storm', name: 'Sleet Storm', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:7119', castingTime: 'action', components: material('a miniature umbrella'),
    targeting: { kind: 'area', rangeFeet: 150, shape: 'cylinder', baseSizeFeet: 20, sizePerSlotFeet: 0, secondarySizeFeet: 40 },
    operation: { kind: 'utility', effect: { kind: 'sleet_storm_area', placement: 'selected_when_cast', radiusFeet: 20, heightFeet: 40, obscurement: 'heavy', difficultTerrain: true, saveAbility: 'dexterity', failureCondition: 'Prone', failureBreaksConcentration: true }, concentration: true, durationRounds: 10 },
  },
  {
    id: 'slow', name: 'Slow', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:7140', castingTime: 'action', components: material('a drop of molasses'),
    targeting: { kind: 'area_selected', rangeFeet: 120, shape: 'cube', baseSizeFeet: 40, sizePerSlotFeet: 0, baseMaximum: 6, additionalPerSlot: 0 },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'normal', effect: effect({ kind: 'slow', speedMultiplier: 0.5, armorClassPenalty: 2, dexteritySavePenalty: 2, reactionsAllowed: false, actionOrBonusOnly: true, attacksPerAction: 1, somaticSpellFailurePercent: 25 }, { concentration: true, durationRounds: 10, expiresAt: 'target_end', repeatedSave: { ability: 'wisdom', rollMode: 'normal', timing: 'target_end' } }) },
  },
  {
    id: 'speak-with-dead', name: 'Speak with Dead', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:7214', castingTime: 'action', components: material('burning incense'),
    targeting: { kind: 'utility', rangeFeet: 10 },
    operation: { kind: 'utility', effect: { kind: 'speak_with_dead', maximumQuestions: 5, sameCorpseLockoutRounds: 144000 }, concentration: false, durationRounds: 100 },
  },
  {
    id: 'spirit-guardians', name: 'Spirit Guardians', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:7324', castingTime: 'action', components: material('a prayer scroll'),
    targeting: { kind: 'area', rangeFeet: 0, shape: 'emanation', baseSizeFeet: 15, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'spirit_guardians_area', placement: 'selected_when_cast', radiusFeet: 15, speedMultiplier: 0.5, damageTypes: ['Radiant', 'Necrotic'], damageCount: 3, damageSides: 8, damagePerSlotCount: 1, saveAbility: 'wisdom', onSuccess: 'half', oncePerTurn: true }, concentration: true, durationRounds: 100 },
  },
  {
    id: 'stinking-cloud', name: 'Stinking Cloud', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:7391', castingTime: 'action', components: material('a rotten egg'),
    targeting: { kind: 'area', rangeFeet: 90, shape: 'sphere', baseSizeFeet: 20, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'stinking_cloud_area', placement: 'selected_when_cast', radiusFeet: 20, obscurement: 'heavy', dispersedByStrongWind: true, saveAbility: 'constitution', failureCondition: 'Poisoned', actionsAllowedOnFailure: false }, concentration: true, durationRounds: 10 },
  },
  {
    id: 'tiny-hut', name: 'Tiny Hut', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:7908', castingTime: 'minute', ritual: true, components: material('a crystal bead'),
    targeting: { kind: 'area', rangeFeet: 0, shape: 'emanation', baseSizeFeet: 10, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'tiny_hut', placement: 'selected_when_cast', radiusFeet: 10, blocksOutsideCreaturesAndObjects: true, blocksSpellLevelAtMost: 3, opaqueFromOutside: true, transparentFromInside: true }, concentration: false, durationRounds: 4800 },
  },
  {
    id: 'tongues', name: 'Tongues', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:7932', castingTime: 'action', components: materialWith('a miniature ziggurat', { verbal: true, somatic: false }),
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'universal_language', understandsSpokenAndSigned: true, understoodByAnyLanguageSpeaker: true }, { durationRounds: 600 }) },
  },
  {
    id: 'vampiric-touch', name: 'Vampiric Touch', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:8158', castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: false },
    operation: { kind: 'lifedrain_attack', damageType: damageType('Necrotic'), dice: dice(3, 6, { perSlotCount: 1 }), healingDivisor: 2, effect: effect({ kind: 'vampiric_touch', repeatAttackCost: 'magic_action' }, { target: 'self', concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'water-breathing', name: 'Water Breathing', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:8415', castingTime: 'action', ritual: true, components: material('a short reed'),
    targeting: { kind: 'multiple', rangeFeet: 30, baseMaximum: 10, additionalPerSlot: 0, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'water_breathing', retainsNormalRespiration: true }, { durationRounds: 14400 }) },
  },
  {
    id: 'water-walk', name: 'Water Walk', level: 3,
    source: 'docs/srd/source/spell-descriptions.txt:8429', castingTime: 'action', ritual: true, components: material('a piece of cork'),
    targeting: { kind: 'multiple', rangeFeet: 30, baseMaximum: 10, additionalPerSlot: 0, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'water_walk', surfaces: ['water', 'acid', 'mud', 'snow', 'quicksand', 'lava'], transitionCost: 'bonus_action' }, { durationRounds: 600 }) },
  },
  {
    id: 'arcane-eye', name: 'Arcane Eye', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:398', castingTime: 'action', components: material('a bit of bat fur'),
    targeting: { kind: 'utility', rangeFeet: 30 },
    operation: { kind: 'utility', effect: { kind: 'arcane_eye', darkvisionFeet: 30, moveFeetPerBonusAction: 30, minimumOpeningInches: 1, invisible: true, invulnerable: true }, concentration: true, durationRounds: 600 },
  },
  {
    id: 'aura-of-life', name: 'Aura of Life', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:624', castingTime: 'action', components: V,
    targeting: { kind: 'self' },
    operation: { kind: 'effect', effect: effect({ kind: 'aura_of_life', radiusFeet: 30, resistanceType: 'Necrotic', preventsHitPointMaximumReduction: true, startTurnHealingAtZero: 1 }, { target: 'self', concentration: true, durationRounds: 100 }) },
  },
  {
    id: 'banishment', name: 'Banishment', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:686', castingTime: 'action', components: material('a pentacle'),
    targeting: { kind: 'multiple', rangeFeet: 30, baseMaximum: 1, additionalPerSlot: 1 },
    operation: { kind: 'save_effect', ability: 'charisma', rollMode: 'normal', effect: effect({ kind: 'banishment', condition: 'Incapacitated', nativePlaneCreatureTypes: ['Aberration', 'Celestial', 'Elemental', 'Fey', 'Fiend'], permanentAfterRounds: 10 }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'black-tentacles', name: 'Black Tentacles', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:784', castingTime: 'action', components: material('a tentacle'),
    targeting: { kind: 'area', rangeFeet: 90, shape: 'cube', baseSizeFeet: 20, sizePerSlotFeet: 0 },
    operation: { kind: 'save_damage_and_effect', ability: 'strength', onSuccess: 'none', damageType: damageType('Bludgeoning'), dice: dice(3, 6), effect: effect({ kind: 'black_tentacles_area', placement: 'selected_when_cast', squareFeet: 20, difficultTerrain: true, saveAbility: 'strength', damageCount: 3, damageSides: 6, damageType: 'Bludgeoning', failureCondition: 'Restrained', escapeCheckSkill: 'Athletics', oncePerTurn: true }, { target: 'self', concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'blight', name: 'Blight', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:842', castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 30, willing: false },
    operation: { kind: 'save_damage', ability: 'constitution', onSuccess: 'half', damageType: damageType('Necrotic'), dice: dice(8, 8, { perSlotCount: 1 }), riderOnFailure: null, pushFeetOnFailure: 0 },
  },
  {
    id: 'charm-monster', name: 'Charm Monster', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:1025', castingTime: 'action', components: VS,
    targeting: { kind: 'multiple', rangeFeet: 30, baseMaximum: 1, additionalPerSlot: 1 },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'normal', effect: effect({ kind: 'charm_monster', condition: 'Charmed', hostileSaveMode: 'advantage', attitude: 'Friendly', endsWhenDamagedByCasterOrAllies: true, targetKnowsAfterward: true }, { durationRounds: 600 }) },
  },
  {
    id: 'confusion', name: 'Confusion', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:1358', castingTime: 'action', components: material('three nut shells'),
    targeting: { kind: 'area', rangeFeet: 90, shape: 'sphere', baseSizeFeet: 10, sizePerSlotFeet: 5 },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'normal', effect: effect({ kind: 'confusion_area', placement: 'selected_when_cast', behaviorDieSides: 10, directionDieSides: 4, bonusActionsAllowed: false, reactionsAllowed: false }, { concentration: true, durationRounds: 10, expiresAt: 'target_end', repeatedSave: { ability: 'wisdom', rollMode: 'normal', timing: 'target_end' } }) },
  },
  {
    id: 'conjure-minor-elementals', name: 'Conjure Minor Elementals', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:1516', castingTime: 'action', components: VS,
    targeting: { kind: 'area', rangeFeet: 0, shape: 'emanation', baseSizeFeet: 15, sizePerSlotFeet: 0 },
    operation: { kind: 'effect', effect: effect({ kind: 'conjure_minor_elementals', radiusFeet: 15, damageTypes: ['Acid', 'Cold', 'Fire', 'Lightning'], damageCount: 2, damageSides: 8, damagePerSlotCount: 1, difficultTerrainForEnemies: true }, { target: 'self', concentration: true, durationRounds: 100 }) },
  },
  {
    id: 'control-water', name: 'Control Water', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:1660', castingTime: 'action', components: material('a mixture of water and dust'),
    targeting: { kind: 'area', rangeFeet: 300, shape: 'cube', baseSizeFeet: 100, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'control_water', placement: 'selected_when_cast', cubeFeet: 100, modes: ['flood', 'part_water', 'redirect_flow', 'whirlpool'], floodRiseFeet: 20, capsizePercent: 25, whirlpoolMinimumSquareFeet: 50, whirlpoolMinimumDepthFeet: 25, whirlpoolBaseFeet: 5, whirlpoolTopFeet: 50, whirlpoolHeightFeet: 25, pullRadiusFeet: 25, pullFeet: 10, damageCount: 2, damageSides: 8, onSuccess: 'half' }, concentration: true, durationRounds: 100 },
  },
  {
    id: 'death-ward', name: 'Death Ward', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:1992', castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'death_ward', replacementHitPoints: 1, negatesInstantDeath: true, consumedOnTrigger: true }, { durationRounds: 4800 }) },
  },
  {
    id: 'dimension-door', name: 'Dimension Door', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:2156', castingTime: 'action', components: V,
    targeting: { kind: 'utility', rangeFeet: 500 },
    operation: { kind: 'utility', effect: { kind: 'dimension_door', maximumDistanceFeet: 500, maximumPassengers: 1, passengerStartFeet: 5, passengerDestinationFeet: 5, failureDamageCount: 4, failureDamageSides: 6, failureDamageType: 'Force' }, concentration: false, durationRounds: null },
  },
  {
    id: 'divination', name: 'Divination', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:2313', castingTime: 'action', ritual: true, components: material('incense worth 25+ GP', true),
    targeting: { kind: 'utility', rangeFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'divination', forecastDays: 7, noAnswerChancePerExtraCastingPercent: 25 }, concentration: false, durationRounds: null },
  },
  {
    id: 'fabricate', name: 'Fabricate', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:2852', castingTime: 'ten_minutes', components: VS,
    targeting: { kind: 'utility', rangeFeet: 120 },
    operation: { kind: 'utility', effect: { kind: 'fabricate', standardCubeFeet: 10, connectedCubes: 8, mineralCubeFeet: 5, requiresArtisanToolProficiencyForSkilledItems: true, createsCreaturesOrMagicItems: false }, concentration: false, durationRounds: null, stateful: true },
  },
  {
    id: 'faithful-hound', name: 'Faithful Hound', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:2902', castingTime: 'action', components: material('a silver whistle'),
    targeting: { kind: 'utility', rangeFeet: 30 },
    operation: { kind: 'utility', effect: { kind: 'faithful_hound', maximumSeparationFeet: 300, triggerRadiusFeet: 30, truesightFeet: 30, biteReachFeet: 5, saveAbility: 'dexterity', damageCount: 4, damageSides: 8, damageType: 'Force', moveFeetPerMagicAction: 30 }, concentration: false, durationRounds: 4800, stateful: true },
  },
  {
    id: 'fire-shield', name: 'Fire Shield', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:3202', castingTime: 'action', components: material('a bit of phosphorus or a firefly'),
    targeting: { kind: 'self' },
    operation: { kind: 'effect', effect: effect({ kind: 'fire_shield', brightFeet: 10, dimFeet: 10, resistanceTypes: ['Cold', 'Fire'], retaliationReachFeet: 5, retaliationDamageCount: 2, retaliationDamageSides: 8, retaliationDamageTypes: ['Fire', 'Cold'] }, { target: 'self', durationRounds: 100 }) },
  },
  {
    id: 'freedom-of-movement', name: 'Freedom of Movement', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:3520', castingTime: 'action', components: material('a leather strap'),
    targeting: { kind: 'multiple', rangeFeet: 5, baseMaximum: 1, additionalPerSlot: 1, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'freedom_of_movement', ignoresDifficultTerrain: true, preventsMagicalSpeedReduction: true, preventedConditions: ['Paralyzed', 'Restrained'], swimSpeedEqualsSpeed: true, nonmagicalEscapeMovementFeet: 5 }, { durationRounds: 600 }) },
  },
  {
    id: 'greater-invisibility', name: 'Greater Invisibility', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:3898', castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'condition', condition: 'Invisible' }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'guardian-of-faith', name: 'Guardian of Faith', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:3927', castingTime: 'action', components: V,
    targeting: { kind: 'utility', rangeFeet: 30 },
    operation: { kind: 'utility', effect: { kind: 'guardian_of_faith', size: 'Large', triggerRadiusFeet: 10, saveAbility: 'dexterity', damage: 20, damageType: 'Radiant', onSuccess: 'half', maximumTotalDamage: 60 }, concentration: false, durationRounds: 4800, stateful: true },
  },
  {
    id: 'hallucinatory-terrain', name: 'Hallucinatory Terrain', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:4101', castingTime: 'ten_minutes', components: material('a mushroom'),
    targeting: { kind: 'area', rangeFeet: 300, shape: 'cube', baseSizeFeet: 150, sizePerSlotFeet: 0 },
    operation: { kind: 'utility', effect: { kind: 'hallucinatory_terrain', placement: 'selected_when_cast', cubeFeet: 150, sensoryModes: ['visual', 'sound', 'smell'], tactileUnchanged: true, investigationAgainstSpellDc: true }, concentration: false, durationRounds: 14400 },
  },
  {
    id: 'ice-storm', name: 'Ice Storm', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:4453', castingTime: 'action', components: material('a mitten'),
    targeting: { kind: 'area', rangeFeet: 300, shape: 'cylinder', baseSizeFeet: 20, sizePerSlotFeet: 0, secondarySizeFeet: 40 },
    operation: { kind: 'save_multi_damage', ability: 'dexterity', onSuccess: 'half', terms: [{ damageType: damageType('Bludgeoning'), dice: dice(2, 10, { perSlotCount: 1 }) }, { damageType: damageType('Cold'), dice: dice(4, 6) }], effect: effect({ kind: 'ice_storm_terrain', placement: 'selected_when_cast', difficultTerrain: true }, { target: 'self', durationRounds: 2, expiresAt: 'source_end' }) },
  },
  {
    id: 'locate-creature', name: 'Locate Creature', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:4858', castingTime: 'action', components: material('fur from a bloodhound'),
    targeting: { kind: 'self' },
    operation: { kind: 'effect', effect: effect({ kind: 'locate_creature', radiusFeet: 1000, familiarityDistanceFeet: 30, blockedByLead: true, failsForDifferentForm: true }, { target: 'self', concentration: true, durationRounds: 600 }) },
  },
  {
    id: 'phantasmal-killer', name: 'Phantasmal Killer', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:5733', castingTime: 'action', components: VS,
    targeting: { kind: 'single', rangeFeet: 120, willing: false },
    operation: { kind: 'save_damage', ability: 'wisdom', onSuccess: 'half', damageType: damageType('Psychic'), dice: dice(4, 10, { perSlotCount: 1 }), riderOnFailure: effect({ kind: 'phantasmal_killer', disadvantagedTests: ['ability_check', 'attack_roll'], repeatSaveAbility: 'wisdom', repeatDamageCount: 4, repeatDamageSides: 10, repeatDamagePerSlotCount: 1, repeatDamageType: 'Psychic' }, { concentration: true, durationRounds: 10, expiresAt: 'target_end', repeatedSave: { ability: 'wisdom', rollMode: 'normal', timing: 'target_end' } }), pushFeetOnFailure: 0 },
  },
  {
    id: 'polymorph', name: 'Polymorph', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:5939', castingTime: 'action', components: material('a caterpillar cocoon'),
    targeting: { kind: 'single', rangeFeet: 60, willing: false },
    operation: { kind: 'save_effect', ability: 'wisdom', rollMode: 'normal', effect: effect({ kind: 'polymorph', formType: 'Beast', maximumChallengeRating: 'target_cr_or_level', temporaryHitPoints: 'beast_hit_points', endsAtTemporaryHitPoints: 0, canSpeak: false, canCastSpells: false, gearMelds: true }, { concentration: true, durationRounds: 600 }) },
  },
  {
    id: 'private-sanctum', name: 'Private Sanctum', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:6213', castingTime: 'ten_minutes', components: material('a thin sheet of lead'),
    targeting: { kind: 'area', rangeFeet: 120, shape: 'cube', baseSizeFeet: 100, sizePerSlotFeet: 100 },
    operation: { kind: 'utility', effect: { kind: 'private_sanctum', placement: 'selected_when_cast', minimumCubeFeet: 5, maximumCubeFeet: 100, cubeFeetPerSlot: 100, protections: ['sound', 'vision', 'divination_sensors', 'divination_targeting', 'teleportation', 'planar_travel'], permanentAfterDailyCastings: 365 }, concentration: false, durationRounds: 14400 },
  },
  {
    id: 'resilient-sphere', name: 'Resilient Sphere', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:6513', castingTime: 'action', components: material('a glass sphere'),
    targeting: { kind: 'single', rangeFeet: 30, willing: false },
    operation: { kind: 'save_effect', ability: 'dexterity', rollMode: 'normal', effect: effect({ kind: 'resilient_sphere', maximumSize: 'Large', blocksPhysicalObjectsEnergyAndSpells: true, immuneToDamage: true, rollSpeedMultiplier: 0.5, destroyedBy: 'Disintegrate' }, { concentration: true, durationRounds: 10 }) },
  },
  {
    id: 'secret-chest', name: 'Secret Chest', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:6755', castingTime: 'action', components: material('a chest, 3 feet by 2 feet by 2 feet, constructed from rare materials worth 5,000+ GP, and a Tiny replica of the chest made from the same materials worth 50+ GP'),
    targeting: { kind: 'utility', rangeFeet: 5 },
    operation: { kind: 'utility', effect: { kind: 'secret_chest', chestDimensionsFeet: [3, 2, 2], capacityCubicFeet: 12, recallDistanceFeet: 5, riskBeginsAfterDays: 60, dailyEndChancePercent: 5, chestMinimumGp: 5000, replicaMinimumGp: 50 }, concentration: false, durationRounds: null, stateful: true },
  },
  {
    id: 'stone-shape', name: 'Stone Shape', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:7413', castingTime: 'action', components: material('soft clay'),
    targeting: { kind: 'utility', rangeFeet: 5 },
    operation: { kind: 'utility', effect: { kind: 'stone_shape', maximumDimensionFeet: 5, maximumHinges: 2, permitsLatch: true }, concentration: false, durationRounds: null, stateful: true },
  },
  {
    id: 'stoneskin', name: 'Stoneskin', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:7429', castingTime: 'action', components: material('diamond dust worth 100+ GP', true),
    targeting: { kind: 'single', rangeFeet: 5, willing: true },
    operation: { kind: 'effect', effect: effect({ kind: 'damage_resistances', damageTypes: ['Bludgeoning', 'Piercing', 'Slashing'] }, { concentration: true, durationRounds: 600 }) },
  },
  {
    id: 'vitriolic-sphere', name: 'Vitriolic Sphere', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:8196', castingTime: 'action', components: material('a drop of bile'),
    targeting: { kind: 'area', rangeFeet: 150, shape: 'sphere', baseSizeFeet: 20, sizePerSlotFeet: 0 },
    operation: { kind: 'save_damage_over_time', ability: 'dexterity', onSuccess: 'half_initial', damageType: damageType('Acid'), initialDice: dice(10, 4, { perSlotCount: 2 }), laterDice: dice(5, 4), laterTiming: 'target_end' },
  },
  {
    id: 'wall-of-fire', name: 'Wall of Fire', level: 4,
    source: 'docs/srd/source/spell-descriptions.txt:8217', castingTime: 'action', components: material('a piece of charcoal'),
    targeting: { kind: 'area', rangeFeet: 120, shape: 'line', baseSizeFeet: 60, sizePerSlotFeet: 0, secondarySizeFeet: 1 },
    operation: { kind: 'save_damage_and_effect', ability: 'dexterity', onSuccess: 'half', damageType: damageType('Fire'), dice: dice(5, 8, { perSlotCount: 1 }), effect: effect({ kind: 'wall_of_fire', placement: 'selected_when_cast', maximumLengthFeet: 60, heightFeet: 20, thicknessFeet: 1, ringDiameterFeet: 20, damagingSideDistanceFeet: 10, damageCount: 5, damageSides: 8, damagePerSlotCount: 1, damageType: 'Fire', opaque: true }, { target: 'self', concentration: true, durationRounds: 10 }) },
  },
] as const;

const definitionsById = new Map(
  IMPLEMENTED_SPELL_DEFINITIONS.map((definition) => [definition.id, definition] as const),
);

export function spellDefinition(id: string): SpellDefinition | null {
  return definitionsById.get(id) ?? null;
}
