import type { SpellLevel } from './types';

export type SpellManifestStatus = 'implemented' | 'pending';

export interface SpellManifestMembership {
  readonly list: 'Cleric' | 'Wizard';
  readonly source: string;
}

export interface SpellManifestRow {
  readonly id: string;
  readonly name: string;
  readonly level: SpellLevel;
  readonly memberships: readonly SpellManifestMembership[];
  readonly status: SpellManifestStatus;
  /** Precise residual after the executable mechanical core; never a fallback. */
  readonly partial?: string;
}

/**
 * D260 level-7 Fighter/Cleric/Wizard coverage inventory. Fighter/Champion has
 * no spell list. Rows are the deduplicated union of the independently printed
 * Cleric and Wizard lists through level 4, plus their selectable cantrips.
 */
export const SPELL_MANIFEST = [
  { id: "acid-splash", name: "Acid Splash", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:246" }], status: 'implemented' },
  { id: "chill-touch", name: "Chill Touch", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:248" }], status: 'implemented' },
  { id: "dancing-lights", name: "Dancing Lights", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:250" }], status: 'implemented', partial: 'Light count, radii, concentration, duration, and movement limit are typed; independent light positions await created-object spatial state.' },
  { id: "elementalism", name: "Elementalism", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:252" }], status: 'implemented', partial: 'All five choices are typed; doors, surfaces, containers, and elemental material mutations await encounter object state.' },
  { id: "fire-bolt", name: "Fire Bolt", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:253" }], status: 'implemented' },
  { id: "guidance", name: "Guidance", level: 0, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:28" }], status: 'implemented' },
  { id: "light", name: "Light", level: 0, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:30" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:254" }], status: 'implemented', partial: 'Light radii and duration are typed; attachment to a chosen object and opaque covering await encounter object state.' },
  { id: "mage-hand", name: "Mage Hand", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:260" }], status: 'implemented', partial: 'Range, movement, duration, and carrying limit are typed; manipulating inventory and doors awaits encounter object state.' },
  { id: "mending", name: "Mending", level: 0, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:32" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:261" }], status: 'implemented', partial: 'Casting time and one-foot repair limit are executable data; applying repair awaits object damage state.' },
  { id: "message", name: "Message", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:263" }], status: 'implemented', partial: 'Target, range, reply, duration, and magical-silence block are typed; material-specific wall blocking awaits barrier material data.' },
  { id: "minor-illusion", name: "Minor Illusion", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:265" }], status: 'implemented', partial: 'Sound/image modes, size, and duration are typed; Study checks and per-creature discernment await illusion-observer state.' },
  { id: "poison-spray", name: "Poison Spray", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:266" }], status: 'implemented' },
  { id: "prestidigitation", name: "Prestidigitation", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:267" }], status: 'implemented', partial: 'All six choices and the three-effect cap are typed; their object and sensory mutations await encounter object state.' },
  { id: "ray-of-frost", name: "Ray of Frost", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:269" }], status: 'implemented' },
  { id: "resistance", name: "Resistance", level: 0, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:33" }], status: 'implemented', partial: 'Chosen damage type, 1d4 reduction, concentration, and once-per-turn constraint are typed; reduction awaits typed per-term damage interception.' },
  { id: "sacred-flame", name: "Sacred Flame", level: 0, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:34" }], status: 'implemented' },
  { id: "shocking-grasp", name: "Shocking Grasp", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:270" }], status: 'implemented' },
  { id: "spare-the-dying", name: "Spare the Dying", level: 0, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:36" }], status: 'implemented' },
  { id: "thaumaturgy", name: "Thaumaturgy", level: 0, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:37" }], status: 'implemented', partial: 'All six choices and the three-effect cap are typed; their object and sensory mutations await encounter object state.' },
  { id: "true-strike", name: "True Strike", level: 0, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:271" }], status: 'implemented', partial: 'Spellcasting attack, weapon damage, and level-7 Radiant rider execute; proficiency and the selected weapon range await the equipment-backed cast adapter.' },
  { id: "alarm", name: "Alarm", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:275" }], status: 'implemented', partial: 'The typed ward, duration, audible and mental ranges execute; door/window intrusion, exclusions, and alerts await encounter object and trigger state.' },
  { id: "bane", name: "Bane", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:43" }], status: 'implemented' },
  { id: "bless", name: "Bless", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:44" }], status: 'implemented' },
  { id: "burning-hands", name: "Burning Hands", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:277" }], status: 'implemented' },
  { id: "charm-person", name: "Charm Person", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:279" }], status: 'implemented', partial: 'The Charmed condition and combat save are executable; Humanoid typing, ally-damage expiry, and post-expiry knowledge await creature-type and alliance history.' },
  { id: "chromatic-orb", name: "Chromatic Orb", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:280" }], status: 'implemented', partial: 'Selectable damage type, attack, base damage, and slot scaling execute; equal-die leap chains await multi-attack roll-result routing.' },
  { id: "color-spray", name: "Color Spray", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:281" }], status: 'implemented' },
  { id: "command", name: "Command", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:45" }], status: 'implemented', partial: 'The save, five closed command choices, duration, and upcast target count execute; forced turn behavior awaits commanded-action reducer commands.' },
  { id: "comprehend-languages", name: "Comprehend Languages", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:283" }], status: 'implemented', partial: 'Duration, one-minute page rate, and secret-message exclusion are typed; language and document content are outside encounter state.' },
  { id: "create-or-destroy-water", name: "Create or Destroy Water", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:47" }], status: 'implemented', partial: 'Exact area placement and both gallon and cube upcast scales are typed; containers, water, fog, flames, and rain await environmental object state.' },
  { id: "cure-wounds", name: "Cure Wounds", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:49" }], status: 'implemented' },
  { id: "detect-evil-and-good", name: "Detect Evil and Good", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:50" }], status: 'implemented', partial: 'The typed detection category, radius, duration, and concentration execute; creature types, Hallow locations, and material blocking await world-state queries.' },
  { id: "detect-magic", name: "Detect Magic", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:52" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:285" }], status: 'implemented', partial: 'The typed magic sense, radius, duration, and concentration execute; aura visibility, schools, and material blocking await object and spell-origin queries.' },
  { id: "detect-poison-and-disease", name: "Detect Poison and Disease", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:53" }], status: 'implemented', partial: 'The typed poison-and-disease sense, radius, duration, and concentration execute; poison, contagion, creature-type, and material-blocking queries await world state.' },
  { id: "disguise-self", name: "Disguise Self", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:286" }], status: 'implemented', partial: 'Duration, height bound, physical-inspection limitation, and Investigation contest are typed; observer knowledge and appearance rendering await perception state.' },
  { id: "expeditious-retreat", name: "Expeditious Retreat", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:288" }], status: 'implemented', partial: 'Immediate and later Bonus Action Dash access is typed with concentration and duration; Dash movement-budget execution awaits the general Dash command.' },
  { id: "false-life", name: "False Life", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:290" }], status: 'implemented' },
  { id: "feather-fall", name: "Feather Fall", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:291" }], status: 'implemented', partial: 'Reaction cost, five-target cap, descent rate, duration, and landing protection are typed; vertical position, falling triggers, and landing await elevation state.' },
  { id: "find-familiar", name: "Find Familiar", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:292" }], status: 'implemented', partial: 'Creation persists as a typed effect with all listed forms and telepathy range; independent initiative, creature statblocks, senses, touch delivery, dismissal, and inventory exceed this increment.' },
  { id: "floating-disk", name: "Floating Disk", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:293" }], status: 'implemented', partial: 'Dimensions, load, follow and break distances, and duration persist as typed state; carried objects, elevation, path following, and overload await object and elevation state.' },
  { id: "fog-cloud", name: "Fog Cloud", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:294" }], status: 'implemented', partial: 'Intersection-anchored sphere placement, radius scaling data, heavy obscurement, concentration, and duration persist; visibility recomputation and wind dispersal await environmental events.' },
  { id: "grease", name: "Grease", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:296" }], status: 'implemented', partial: 'Intersection-anchored initial area save and Prone effect execute; persistent Difficult Terrain and enter/end-turn saves await effect-backed terrain hooks.' },
  { id: "guiding-bolt", name: "Guiding Bolt", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:54" }], status: 'implemented' },
  { id: "healing-word", name: "Healing Word", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:56" }], status: 'implemented' },
  { id: "hideous-laughter", name: "Hideous Laughter", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:298" }], status: 'implemented', partial: 'The initial save, bundled Prone and Incapacitated conditions, concentration, duration, and upcast targets execute; damage-triggered and end-turn repeat saves await multi-trigger effect saves.' },
  { id: "ice-knife", name: "Ice Knife", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:299" }], status: 'implemented' },
  { id: "identify", name: "Identify", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:300" }], status: 'implemented', partial: 'Casting cost and typed identification capability execute; item properties, charges, attunement, creation provenance, and creature spell lists await item and spell-instance state.' },
  { id: "illusory-script", name: "Illusory Script", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:301" }], status: 'implemented', partial: 'Consumed ink, ten-day duration, and Truesight interaction persist as typed state; documents, designated readers, handwriting, language, and dispelling await object state.' },
  { id: "inflict-wounds", name: "Inflict Wounds", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:58" }], status: 'implemented' },
  { id: "jump", name: "Jump", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:302" }], status: 'implemented', partial: 'Jump distance, movement cost, once-per-turn use, duration, and upcast target count persist as typed state; jump path execution awaits elevation-aware movement.' },
  { id: "longstrider", name: "Longstrider", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:303" }], status: 'implemented' },
  { id: "mage-armor", name: "Mage Armor", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:304" }], status: 'implemented', partial: 'Base AC 13 plus Dexterity and the unarmored requirement persist as typed state; profiles currently expose resolved AC rather than Dexterity and equipped armor.' },
  { id: "magic-missile", name: "Magic Missile", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:306" }], status: 'implemented' },
  { id: "protection-from-evil-and-good", name: "Protection from Evil and Good", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:59" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:308" }], status: 'implemented', partial: 'All six creature types, duration, and concentration persist as typed protection; type-filtered attack disadvantage, possession, condition prevention, and repeat-save advantage await creature types and effect provenance.' },
  { id: "purify-food-and-drink", name: "Purify Food and Drink", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:60" }], status: 'implemented', partial: 'Intersection-anchored radius and poison-and-rot removal execute as a typed utility; food, drink, poison, and spoilage await encounter object state.' },
  { id: "ray-of-sickness", name: "Ray of Sickness", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:309" }], status: 'implemented' },
  { id: "sanctuary", name: "Sanctuary", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:61" }], status: 'implemented', partial: 'The ward, Wisdom-save requirement, range, and duration persist as typed state; attack redirection/loss and offensive-action expiry await pre-target interception and damage attribution hooks.' },
  { id: "shield", name: "Shield", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:310" }], status: 'implemented' },
  { id: "shield-of-faith", name: "Shield of Faith", level: 1, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:62" }], status: 'implemented' },
  { id: "silent-image", name: "Silent Image", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:312" }], status: 'implemented', partial: 'Intersection-anchored size, movement capability, Investigation contest, duration, and concentration persist; observer knowledge, physical interaction, and Magic-action relocation await illusion entities.' },
  { id: "sleep", name: "Sleep", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:314" }], status: 'implemented', partial: 'Intersection-anchored initial save and Incapacitated stage execute, with the Unconscious transition typed; second saves, wake actions, damage expiry, and sleep immunity await staged effect transitions and ancestry traits.' },
  { id: "thunderwave", name: "Thunderwave", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:316" }], status: 'implemented' },
  { id: "unseen-servant", name: "Unseen Servant", level: 1, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:318" }], status: 'implemented', partial: 'AC, Hit Points, Strength, movement, command cost, maximum distance, and duration persist as typed creation state; independent token, object interactions, task execution, and destruction await summon entities.' },
  { id: "acid-arrow", name: "Acid Arrow", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:324" }], status: 'implemented' },
  { id: "aid", name: "Aid", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:66" }], status: 'implemented', partial: 'Maximum and current Hit Point increases execute; expiry-time maximum reduction and current-HP clamping await derived maximum-HP lifecycle hooks.' },
  { id: "alter-self", name: "Alter Self", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:325" }], status: 'implemented', partial: 'All three forms and natural-weapon values persist; swim/breathing, appearance rendering, option switching, and equipment attacks await movement, avatar, and equipment state.' },
  { id: "arcane-lock", name: "Arcane Lock", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:326" }], status: 'implemented', partial: 'Permanent lock, password range, and unlock duration persist; doors, containers, designated creatures, and passwords await encounter object state.' },
  { id: "arcanists-magic-aura", name: "Arcanist’s Magic Aura", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:327" }], status: 'implemented', partial: 'Mask, False Aura, duration, and permanent-casting threshold persist; creature types, item auras, daily history, and detection queries await world state.' },
  { id: "augury", name: "Augury", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:67" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:328" }], status: 'implemented', partial: 'Forecast window and cumulative no-answer chance execute as typed divination data; omen choice and future-course adjudication remain explicitly GM-facing.' },
  { id: "blindness-deafness", name: "Blindness/Deafness", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:69" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:329" }], status: 'implemented' },
  { id: "blur", name: "Blur", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:330" }], status: 'implemented', partial: 'Attack disadvantage and sensory bypasses persist as typed state; attack resolution awaits generalized attacks-against-target effect interception.' },
  { id: "calm-emotions", name: "Calm Emotions", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:71" }], status: 'implemented', partial: 'Exact area save, options, concentration, and duration execute; Humanoid filtering, condition suppression, attitudes, and damage/witness expiry await type and alliance state.' },
  { id: "continual-flame", name: "Continual Flame", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:72" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:331" }], status: 'implemented', partial: 'Permanent light radii persist; attachment to a coverable object and interaction with environmental illumination await object-backed light state.' },
  { id: "darkness", name: "Darkness", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:332" }], status: 'implemented', partial: 'Exact magical-darkness sphere, Darkvision blocking, light suppression, and duration persist; object emanations, covering, and live visibility recomputation await environmental hooks.' },
  { id: "darkvision", name: "Darkvision", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:333" }], status: 'implemented', partial: 'The 150-foot sense and duration persist; visibility resolution does not yet consume effect-granted senses.' },
  { id: "detect-thoughts", name: "Detect Thoughts", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:334" }], status: 'implemented', partial: 'Sense radius, probe save, and Arcana escape data persist; language, thoughts, attention shifts, cover materials, and observer knowledge await perception state.' },
  { id: "dragons-breath", name: "Dragon’s Breath", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:335" }], status: 'implemented', partial: 'Damage choices, cone, save-half, dice scaling, duration, and concentration persist; later Magic-action breath execution awaits granted-action commands.' },
  { id: "enhance-ability", name: "Enhance Ability", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:73" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:336" }], status: 'implemented', partial: 'Chosen-ability advantage, duration, concentration, and upcast targets persist; per-target differing selections await structured multi-target option input.' },
  { id: "enlarge-reduce", name: "Enlarge/Reduce", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:337" }], status: 'implemented', partial: 'Both size modes, Strength modes, damage die, duration, and concentration persist; object targeting, unwilling saves, token footprint, and attack integration await size/equipment state.' },
  { id: "find-traps", name: "Find Traps", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:75" }], status: 'implemented', partial: 'Range and location-exclusion ruling execute; traps, line of sight, and danger natures await environmental hazard state.' },
  { id: "flaming-sphere", name: "Flaming Sphere", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:338" }], status: 'implemented', partial: 'Placement, dimensions, damage scaling, movement, light, duration, and concentration persist; end-turn saves, bonus movement, collision, barriers, pits, and ignition await summoned-area turn hooks.' },
  { id: "gentle-repose", name: "Gentle Repose", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:77" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:339" }], status: 'implemented', partial: 'Ten-day preservation and undead prevention persist; corpses, decay, undead creation, and resurrection time limits await remains state.' },
  { id: "gust-of-wind", name: "Gust of Wind", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:340" }], status: 'implemented', partial: 'Initial exact-line saves and pushes execute; repeated end-turn saves, movement costs, direction changes, gas, and flame interactions await persistent-zone hooks.' },
  { id: "hold-person", name: "Hold Person", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:78" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:341" }], status: 'implemented', partial: 'Save, Paralyzed condition, repeated saves, duration, concentration, and upcast targets execute; Humanoid filtering awaits creature-type profiles.' },
  { id: "invisibility", name: "Invisibility", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:342" }], status: 'implemented', partial: 'Invisible condition, duration, concentration, and upcast targets execute; attack, damage, and spell-triggered expiry awaits offensive-action attribution hooks.' },
  { id: "knock", name: "Knock", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:343" }], status: 'implemented', partial: 'Single-lock scope, Arcane Lock suppression, and sound range execute; doors, locks, stuck or barred state, and audibility await object and sound state.' },
  { id: "lesser-restoration", name: "Lesser Restoration", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:79" }], status: 'implemented' },
  { id: "levitate", name: "Levitate", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:344" }], status: 'implemented', partial: 'Save, rise, weight, altitude-change rate, duration, and concentration persist; willing bypass, vertical position, surface pulling, and landing await elevation state.' },
  { id: "locate-object", name: "Locate Object", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:81" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:345" }], status: 'implemented', partial: 'Range, familiarity distance, lead blocking, duration, and concentration persist; object identity, motion, direction, and path blocking await world-object queries.' },
  { id: "magic-mouth", name: "Magic Mouth", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:346" }], status: 'implemented', partial: 'Word limit, message duration, trigger radius, ritual, and permanent creation persist; objects, messages, conditions, voices, repetition, and triggers await object/event state.' },
  { id: "magic-weapon", name: "Magic Weapon", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:347" }], status: 'implemented', partial: 'All three slot-band bonuses and duration persist; nonmagical weapon selection, attack/damage integration, and recast expiry await equipment-backed effects.' },
  { id: "mind-spike", name: "Mind Spike", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:348" }], status: 'implemented', partial: 'Save-half damage and failed-save tracking state execute; same-plane location knowledge and Hidden/Invisible benefit suppression await perception resolution.' },
  { id: "mirror-image", name: "Mirror Image", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:349" }], status: 'implemented', partial: 'Duplicate count, d6 interception threshold, and duration persist; hit interception, duplicate consumption, and sensory bypass await pre-damage attack hooks.' },
  { id: "misty-step", name: "Misty Step", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:350" }], status: 'implemented', partial: 'Bonus-action cost, maximum distance, visibility, and unoccupied-space requirements execute as typed utility; destination input and token relocation await teleport commands.' },
  { id: "prayer-of-healing", name: "Prayer of Healing", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:82" }], status: 'implemented', partial: 'Ten-minute cast, five targets, healing, and upcast scaling execute; Short Rest benefits, continuous range, and once-per-Long-Rest recipient lockout await rest/history state.' },
  { id: "protection-from-poison", name: "Protection from Poison", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:87" }], status: 'implemented', partial: 'Poisoned removal and typed save advantage/resistance execute; poison save mode and damage resistance await generalized effect interception.' },
  { id: "ray-of-enfeeblement", name: "Ray of Enfeeblement", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:351" }], status: 'implemented', partial: 'Both save branches, repeat saves, duration, concentration, and d8 penalty persist; Strength-test disadvantage and damage subtraction await D20/damage interception.' },
  { id: "rope-trick", name: "Rope Trick", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:352" }], status: 'implemented', partial: 'Portal dimensions, capacity, and duration persist; rope position, extradimensional occupancy, sight, effect blocking, and expiry drops await elevation and region state.' },
  { id: "scorching-ray", name: "Scorching Ray", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:353" }], status: 'implemented' },
  { id: "see-invisibility", name: "See Invisibility", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:354" }], status: 'implemented', partial: 'Invisible and Ethereal visibility capabilities and duration persist; visibility resolution does not yet consume effect-granted senses.' },
  { id: "shatter", name: "Shatter", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:355" }], status: 'implemented', partial: 'Exact area, save-half damage, and upcast scaling execute; Construct save disadvantage and unattended-object damage await creature types and object state.' },
  { id: "silence", name: "Silence", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:89" }], status: 'implemented', partial: 'Exact persistent sphere, Thunder immunity, Deafening capability, verbal prohibition, ritual, and concentration persist; live containment and casting/damage interception await area-effect queries.' },
  { id: "spider-climb", name: "Spider Climb", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:356" }], status: 'implemented', partial: 'Climb speed, hands-free capability, duration, concentration, and upcast targets persist; walls and ceilings await elevation-aware movement.' },
  { id: "spiritual-weapon", name: "Spiritual Weapon", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:90" }], status: 'implemented', partial: 'Immediate attack, damage modifier/scaling, reach, movement, duration, and concentration execute; independent force position and later bonus-action attacks await summon entities.' },
  { id: "suggestion", name: "Suggestion", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:357" }], status: 'implemented', partial: 'Save, Charmed condition, concentration, and duration execute; word count, hearing/language, feasibility, behavior, completion, and damage expiry await command and event state.' },
  { id: "warding-bond", name: "Warding Bond", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:91" }], status: 'implemented', partial: 'Range, AC/save bonuses, resistance, mirrored damage, and duration persist; damage sharing, rings, distance/0-HP expiry, and recast exclusivity await damage and equipment hooks.' },
  { id: "web", name: "Web", level: 2, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:358" }], status: 'implemented', partial: 'Initial exact-area save and Restrained state execute with geometry, depth, fire dice, duration, and concentration; entry/start saves, escape action, anchors, terrain, obscurement, and burning await zone hooks.' },
  { id: "zone-of-truth", name: "Zone of Truth", level: 2, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:92" }], status: 'implemented', partial: 'Initial exact-area Charisma saves and truth constraint state execute; entry/start saves, caster save knowledge, speech truth evaluation, and awareness await zone and dialogue state.' },
  { id: "animate-dead", name: "Animate Dead", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:96" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:362" }], status: 'implemented', partial: 'Creation count, forms, command range, control duration, and upcast scaling persist; corpse selection and independent Skeleton/Zombie entities await remains and summon state.' },
  { id: "beacon-of-hope", name: "Beacon of Hope", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:97" }], status: 'implemented', partial: 'Unlimited in-range target legality and all three benefits persist; save advantage and healing maximization await generalized roll and healing effect interception.' },
  { id: "bestow-curse", name: "Bestow Curse", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:98" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:363" }], status: 'implemented', partial: 'Save, four choices, 1d8 rider, concentration, and level-4 duration execute as typed state; selected-option behavior awaits D20/action/damage interception.' },
  { id: "blink", name: "Blink", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:364" }], status: 'implemented', partial: 'Die threshold, vision, return distance, and duration persist; end-turn plane transitions and destination selection await planar position state.' },
  { id: "clairvoyance", name: "Clairvoyance", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:99" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:365" }], status: 'implemented', partial: 'One-mile range, sensor senses, switch cost, duration, and concentration persist; remote sensor placement and perception await world-location state.' },
  { id: "counterspell", name: "Counterspell", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:366" }], status: 'implemented', partial: 'Reaction, range, component, and Constitution save execute; cancelling an in-flight cast while preserving its slot awaits interrupt-stack commands.' },
  { id: "create-food-and-water", name: "Create Food and Water", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:100" }], status: 'implemented', partial: 'Food weight, water volume, spoilage time, and persistence execute; containers, consumption, nutrition, and spoilage events await inventory state.' },
  { id: "daylight", name: "Daylight", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:101" }], status: 'implemented', partial: 'Exact sphere, light radii, duration, and darkness-dispel threshold persist; illumination and object attachment await live environment queries.' },
  { id: "dispel-magic", name: "Dispel Magic", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:102" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:367" }], status: 'implemented', partial: 'Creature-targeted effects through the used slot level end; object/area targets and higher-level DC 10 + level checks await effect-origin targeting and check routing.' },
  { id: "fear", name: "Fear", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:372" }], status: 'implemented', partial: 'Exact cone save and Frightened condition execute; dropping objects, forced Dash movement, and line-of-sight repeat saves await inventory and turn-behavior hooks.' },
  { id: "fireball", name: "Fireball", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:373" }], status: 'implemented', partial: 'Exact sphere, save-half damage, and upcast scaling execute through the shared resolver; flammable-object ignition awaits encounter object state.' },
  { id: "fly", name: "Fly", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:374" }], status: 'implemented', partial: 'Willing targets, speed, hover, fall flag, duration, concentration, and upcast targets persist; aerial movement and falling await elevation state.' },
  { id: "gaseous-form", name: "Gaseous Form", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:375" }], status: 'implemented', partial: 'Movement, hover, resistances, immunity, saves, action restrictions, duration, and upcast targets persist; effect consumers and narrow-opening movement await movement/action interception.' },
  { id: "glyph-of-warding", name: "Glyph of Warding", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:103" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:376" }], status: 'implemented', partial: 'Glyph dimensions, movement break, explosion area/dice/types/scaling, and stored-spell level persist; triggers, concealment, stored casting, and detonation await object/event state.' },
  { id: "haste", name: "Haste", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:377" }], status: 'implemented', partial: 'All bonuses, extra-action choices, lethargy values, duration, and concentration persist; Speed/save/action consumers and expiry lethargy await generalized effect interception.' },
  { id: "hypnotic-pattern", name: "Hypnotic Pattern", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:378" }], status: 'implemented', partial: 'Exact cube save, Charmed/Incapacitated conditions, zero Speed, duration, and concentration execute; visibility filtering and damage/wake expiry await perception and event hooks.' },
  { id: "lightning-bolt", name: "Lightning Bolt", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:379" }], status: 'implemented' },
  { id: "magic-circle", name: "Magic Circle", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:104" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:380" }], status: 'implemented', partial: 'Exact cylinder, creature types, reversal, duration, and upcast duration persist; crossing, teleport saves, attacks, and condition protection await live-zone interception.' },
  { id: "major-image", name: "Major Image", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:381" }], status: 'implemented', partial: 'Exact cube, sensory modes, movement, Study contest, duration, and level-4 permanence execute; rendering and per-observer discernment await illusion entities.' },
  { id: "mass-healing-word", name: "Mass Healing Word", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:106" }], status: 'implemented', partial: 'Six-target healing, spellcasting modifier, bonus-action cost, and upcast scaling execute; visibility-based target legality awaits perception queries.' },
  { id: "meld-into-stone", name: "Meld into Stone", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:108" }], status: 'implemented', partial: 'Ritual, exit cost, destruction damage, expulsion condition, and duration persist; stone objects, containment, perception, and destruction triggers await terrain/object state.' },
  { id: "nondetection", name: "Nondetection", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:382" }], status: 'implemented', partial: 'Creature protection, object-size bound, and duration persist; object/place targeting and divination/sensor blocking await world query interception.' },
  { id: "phantom-steed", name: "Phantom Steed", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:383" }], status: 'implemented', partial: 'Speed, travel rate, equipment distance, fade time, ritual, and duration persist; Riding Horse statblock, mount token, riding, and damage expiry await summon/mount state.' },
  { id: "protection-from-energy", name: "Protection from Energy", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:110" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:384" }], status: 'implemented', partial: 'Choice validation, resistance type, duration, and concentration persist; resistance awaits damage-response effect interception.' },
  { id: "remove-curse", name: "Remove Curse", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:112" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:385" }], status: 'implemented', partial: 'Bestow Curse effects on a creature end; object curses and attunement breaking await equipment and generalized curse provenance.' },
  { id: "revivify", name: "Revivify", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:114" }], status: 'implemented', partial: 'Dead-target legality, consumed diamond, and revival at 1 HP execute; one-minute death age, old age, and missing body parts await death-history and anatomy state.' },
  { id: "sending", name: "Sending", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:116" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:386" }], status: 'implemented', partial: 'Unlimited targeting, word cap, cross-plane failure chance, and block duration execute as typed data; message content, planes, delivery, replies, and history await communication state.' },
  { id: "sleet-storm", name: "Sleet Storm", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:387" }], status: 'implemented', partial: 'Exact cylinder and all terrain, obscurement, save, Prone, and concentration-break values persist; enter/start triggers, flames, terrain, and concentration loss await zone hooks.' },
  { id: "slow", name: "Slow", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:388" }], status: 'implemented', partial: 'Exact cube, six-target selection, save/repeat save, and all penalties persist; Speed, AC, saves, reactions, action limits, and spell failure await effect interception.' },
  { id: "speak-with-dead", name: "Speak with Dead", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:118" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:389" }], status: 'implemented', partial: 'Question cap, corpse lockout, range, and duration persist; corpse eligibility, knowledge, language, answers, and cast history await remains/dialogue state.' },
  { id: "spirit-guardians", name: "Spirit Guardians", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:120" }], status: 'implemented', partial: 'Exact emanation, speed, damage choices/dice/scaling, save-half, once-per-turn, duration, and concentration persist; exclusions and enter/end damage await moving-zone hooks.' },
  { id: "stinking-cloud", name: "Stinking Cloud", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:390" }], status: 'implemented', partial: 'Exact sphere, obscurement, wind, save, Poisoned, action restriction, duration, and concentration persist; start-turn saves and dispersal await zone/environment hooks.' },
  { id: "tiny-hut", name: "Tiny Hut", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:391" }], status: 'implemented', partial: 'Exact emanation, passage and spell barriers, visibility, ritual, and duration persist; initial containment, atmosphere, light, recast, and caster-exit expiry await region hooks.' },
  { id: "tongues", name: "Tongues", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:122" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:392" }], status: 'implemented', partial: 'Spoken/signed comprehension, universal intelligibility, and duration persist; language communication awaits dialogue state.' },
  { id: "vampiric-touch", name: "Vampiric Touch", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:393" }], status: 'implemented', partial: 'Immediate melee attack, damage/upcast scaling, half-damage healing, duration, and concentration execute; later Magic-action attacks await granted-action commands.' },
  { id: "water-breathing", name: "Water Breathing", level: 3, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:394" }], status: 'implemented', partial: 'Ten willing targets, underwater and normal respiration, ritual, and duration persist; drowning and respiration await environmental survival state.' },
  { id: "water-walk", name: "Water Walk", level: 3, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:124" }], status: 'implemented', partial: 'Ten willing targets, six surface types, transition cost, ritual, and duration persist; liquid terrain, falling passage, and lava heat await environmental movement state.' },
  { id: "arcane-eye", name: "Arcane Eye", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:398" }], status: 'pending' },
  { id: "aura-of-life", name: "Aura of Life", level: 4, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:128" }], status: 'pending' },
  { id: "banishment", name: "Banishment", level: 4, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:130" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:399" }], status: 'pending' },
  { id: "black-tentacles", name: "Black Tentacles", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:400" }], status: 'pending' },
  { id: "blight", name: "Blight", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:401" }], status: 'pending' },
  { id: "charm-monster", name: "Charm Monster", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:402" }], status: 'pending' },
  { id: "confusion", name: "Confusion", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:403" }], status: 'pending' },
  { id: "conjure-minor-elementals", name: "Conjure Minor Elementals", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:404" }], status: 'pending' },
  { id: "control-water", name: "Control Water", level: 4, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:131" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:405" }], status: 'pending' },
  { id: "death-ward", name: "Death Ward", level: 4, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:132" }], status: 'pending' },
  { id: "dimension-door", name: "Dimension Door", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:406" }], status: 'pending' },
  { id: "divination", name: "Divination", level: 4, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:133" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:407" }], status: 'pending' },
  { id: "fabricate", name: "Fabricate", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:408" }], status: 'pending' },
  { id: "faithful-hound", name: "Faithful Hound", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:409" }], status: 'pending' },
  { id: "fire-shield", name: "Fire Shield", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:410" }], status: 'pending' },
  { id: "freedom-of-movement", name: "Freedom of Movement", level: 4, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:134" }], status: 'pending' },
  { id: "greater-invisibility", name: "Greater Invisibility", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:411" }], status: 'pending' },
  { id: "guardian-of-faith", name: "Guardian of Faith", level: 4, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:135" }], status: 'pending' },
  { id: "hallucinatory-terrain", name: "Hallucinatory Terrain", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:412" }], status: 'pending' },
  { id: "ice-storm", name: "Ice Storm", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:413" }], status: 'pending' },
  { id: "locate-creature", name: "Locate Creature", level: 4, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:136" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:414" }], status: 'pending' },
  { id: "phantasmal-killer", name: "Phantasmal Killer", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:415" }], status: 'pending' },
  { id: "polymorph", name: "Polymorph", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:420" }], status: 'pending' },
  { id: "private-sanctum", name: "Private Sanctum", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:422" }], status: 'pending' },
  { id: "resilient-sphere", name: "Resilient Sphere", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:423" }], status: 'pending' },
  { id: "secret-chest", name: "Secret Chest", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:424" }], status: 'pending' },
  { id: "stone-shape", name: "Stone Shape", level: 4, memberships: [{ list: 'Cleric', source: "docs/srd/source/cleric-spell-list.txt:137" }, { list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:425" }], status: 'pending' },
  { id: "stoneskin", name: "Stoneskin", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:426" }], status: 'pending' },
  { id: "vitriolic-sphere", name: "Vitriolic Sphere", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:427" }], status: 'pending' },
  { id: "wall-of-fire", name: "Wall of Fire", level: 4, memberships: [{ list: 'Wizard', source: "docs/srd/source/wizard-spell-list.txt:428" }], status: 'pending' },
] as const satisfies readonly SpellManifestRow[];

export function assertSpellManifestBurnDown(
  rows: readonly SpellManifestRow[],
  definitionFor: (id: string) => { readonly name: string; readonly level: number } | null,
): void {
  const ids = new Set<string>();
  for (const row of rows) {
    if (ids.has(row.id)) throw new Error(`Duplicate spell manifest id ${row.id}.`);
    ids.add(row.id);
    if (row.memberships.length === 0) throw new Error(`Spell ${row.id} has no class-list source.`);
    const definition = definitionFor(row.id);
    if (row.status === 'implemented') {
      if (definition === null) throw new Error(`Implemented spell ${row.id} has no definition.`);
      if (definition.name !== row.name || definition.level !== row.level) {
        throw new Error(`Spell definition ${row.id} does not match its manifest row.`);
      }
    } else if (definition !== null) {
      throw new Error(`Pending spell ${row.id} already has a definition.`);
    }
  }
}
