import {
  guidedBuildPath,
  GUIDED_PANEL,
  GUIDED_PANEL_ATTRIBUTE,
  type GuidedSpellsStepState,
} from '../../../builder/contracts';
import type { EligibleSpell } from '../../../domain/read-models';
import { element, type Cleanup } from '../../dom';
import { createSpellPicker } from '../planner/spell-picker';
import { characterListLink, guidedShell } from './guided-builder';

export function createSpellsStep(options: {
  readonly characterId: number;
  readonly state: GuidedSpellsStepState;
  readonly search: (
    address: GuidedSpellsStepState['choices'][number],
    query: string,
  ) => Promise<readonly EligibleSpell[]>;
  readonly assign: (
    address: GuidedSpellsStepState['choices'][number],
    spell: EligibleSpell,
    operationUuid: string,
  ) => Promise<unknown>;
  readonly navigate: (path: string) => void;
}): { readonly element: HTMLElement; readonly cleanup: Cleanup } {
  const pickers = options.state.choices.map((choice) => {
    const picker = createSpellPicker({
      addressKey: `${choice.kind}-${String(choice.id)}`,
      label: choice.label,
      contextDescriptionId: null,
      value: null,
      valueCatalogLayer: null,
      freeTextValue: false,
      invalid: false,
      disabled: false,
      search: async (query) => [...(await options.search(choice, query))],
      onSelect: (spell) => {
        void options
          .assign(choice, spell, crypto.randomUUID())
          .then(() => options.navigate(guidedBuildPath(options.characterId)));
      },
    });
    return picker;
  });
  const panel = element(
    'section',
    {
      className: 'guided-panel',
      attributes: {
        [GUIDED_PANEL_ATTRIBUTE]: GUIDED_PANEL.spellsStep,
      },
    },
    [
      element('h2', { text: 'Choose level 1 spells' }),
      element('p', {
        text:
          'These are the durable spell choices generated by the character’s ' +
          'class and feat rules. Search results use the same eligibility ' +
          'constraints as the planner.',
      }),
      ...pickers.map((picker) => picker.element),
      characterListLink(),
    ],
  );
  return {
    element: guidedShell('spells', panel),
    cleanup: () => pickers.forEach((picker) => picker.destroy()),
  };
}
