import {
  guidedBuildPath,
  GUIDED_PANEL,
  GUIDED_PANEL_ATTRIBUTE,
  type GuidedSpellsStepState,
} from '../../../builder/contracts';
import type { EligibleSpell } from '../../../domain/read-models';
import { catalogControlDescription } from '../../catalog-control-disclosure';
import { clear, element, listen, type Cleanup } from '../../dom';
import {
  createSpellPicker,
  spellPickerControlId,
} from '../planner/spell-picker';
import { characterListLink, guidedShell } from './guided-builder';

export interface GuidedSpellTransition {
  readonly focusKey: string;
  readonly announcement: string;
}

export function createSpellsStep(options: {
  readonly characterId: number;
  readonly state: GuidedSpellsStepState;
  readonly search: (
    address: GuidedSpellsStepState['choices'][number],
    query: string,
  ) => Promise<readonly EligibleSpell[]>;
  readonly assign: (
    address: GuidedSpellsStepState['choices'][number],
    spell: EligibleSpell,
    operationUuid: string,
  ) => Promise<unknown>;
  readonly navigate: (
    path: string,
    transition?: GuidedSpellTransition,
  ) => void;
}): { readonly element: HTMLElement; readonly cleanup: Cleanup } {
  const cleanups: Cleanup[] = [];
  const pickers: ReturnType<typeof createSpellPicker>[] = [];
  const status = element('p', {
    className: 'guided-spell-status',
    attributes: { role: 'status', 'aria-live': 'polite' },
  });
  const announce = (message: string): void => {
    clear(status);
    status.textContent = message;
  };
  const rows = options.state.choices.map((choice) => {
    const addressKey = `${choice.kind}-${String(choice.id)}`;
    const focusKey = `guided-spell-change-${addressKey}`;
    const row = element('div', { className: 'guided-spell-choice' });
    const renderPicker = (focus: boolean): void => {
      const picker = createSpellPicker({
        addressKey,
        label: choice.label,
        contextDescriptionId: null,
        value: null,
        valueCatalogLayer: null,
        freeTextValue: false,
        invalid: false,
        disabled: false,
        search: async (query) => [...(await options.search(choice, query))],
        onSelect: (spell) => {
          void options
            .assign(choice, spell, crypto.randomUUID())
            .then(() => {
              const announcement =
                `${spell.name} selected for ${choice.label}.`;
              announce(announcement);
              options.navigate(
                guidedBuildPath(options.characterId),
                { focusKey, announcement },
              );
            });
        },
      });
      pickers.push(picker);
      row.replaceChildren(
        element('label', {
          className: 'guided-spell-choice-label',
          text: choice.label,
          attributes: { for: spellPickerControlId(addressKey) },
        }),
        picker.element,
      );
      if (focus) picker.focus();
    };

    if (
      choice.selected_spell_name === null ||
      choice.selected_spell_catalog_layer === null
    ) {
      renderPicker(false);
      return row;
    }

    const change = element('button', {
      className: 'guided-spell-change',
      text: `Change ${choice.label}`,
      attributes: {
        type: 'button',
        'data-focus-key': focusKey,
      },
    });
    const disclosure = catalogControlDescription(
      change,
      `guided-spell-${addressKey}-catalog-layer`,
      choice.selected_spell_catalog_layer,
    );
    const summary = element('div', { className: 'guided-spell-summary' }, [
      element('span', {
        text: `${choice.selected_spell_name} — ${choice.label}`,
      }),
      disclosure,
      change,
    ]);
    cleanups.push(
      listen(change, 'click', () => {
        announce(
          `Choose a replacement for ${choice.selected_spell_name} in ${choice.label}.`,
        );
        renderPicker(true);
      }),
    );
    row.append(summary);
    return row;
  });
  const panel = element(
    'section',
    {
      className: 'guided-panel',
      attributes: {
        [GUIDED_PANEL_ATTRIBUTE]: GUIDED_PANEL.spellsStep,
      },
    },
    [
      element('h2', { text: 'Choose level 1 spells' }),
      element('p', {
        text:
          'These are the durable spell choices generated by the character’s ' +
          'class and feat rules. Search results use the same eligibility ' +
          'constraints as the planner.',
      }),
      ...rows,
      status,
      characterListLink(),
    ],
  );
  return {
    element: guidedShell('spells', panel),
    cleanup: () => {
      pickers.forEach((picker) => picker.destroy());
      cleanups.forEach((cleanup) => cleanup());
    },
  };
}
