import type { SrdRuleIdOfKind } from '../rule-index';
import type { RuleStatus } from '../rule-status-types';

/**
 * RULE_STATUS for weapons, armor, weapon properties and masteries, tools and adventuring gear.
 * HAND-MAINTAINED: a new id in the generated index fails this record to
 * compile until it is given a status here.
 *
 * `unrepresented` names the unit that will type the rule (SRD-TYPED plan,
 * synthesis §6.2); `UNASSIGNED` means no planned unit owns it yet.
 */
// D923 Q8: tools are typed data the sheet and checks use, and item prices are
// tracked, so these rows are no longer owner-gated.
const UNREPRESENTED_COINS_COSTS = { status: 'unrepresented', unit: 'COINS-COSTS' } as const;
const UNREPRESENTED_TOOLS_LANGUAGES = { status: 'unrepresented', unit: 'TOOLS-LANGUAGES' } as const;
const UNREPRESENTED_WEAPONS_ARMOR_DATA = { status: 'unrepresented', unit: 'WEAPONS-ARMOR-DATA' } as const;

export const EQUIPMENT_STATUS = {
  'weapon.club': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.dagger': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.greatclub': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.handaxe': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.javelin': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.light-hammer': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.mace': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.quarterstaff': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.sickle': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.spear': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.dart': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.light-crossbow': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.shortbow': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.sling': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.battleaxe': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.flail': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.glaive': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.greataxe': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.greatsword': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.halberd': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.lance': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.longsword': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.maul': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.morningstar': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.pike': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.rapier': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.scimitar': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.shortsword': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.trident': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.warhammer': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.war-pick': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.whip': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.blowgun': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.hand-crossbow': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.heavy-crossbow': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.longbow': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.musket': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon.pistol': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.padded-armor': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.leather-armor': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.studded-leather-armor': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.hide-armor': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.chain-shirt': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.scale-mail': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.breastplate': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.half-plate-armor': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.ring-mail': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.chain-mail': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.splint-armor': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.plate-armor': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'armor.shield': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_property.ammunition': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_property.finesse': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_property.heavy': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_property.light': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_property.loading': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_property.range': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_property.reach': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_property.thrown': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_property.two-handed': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_property.versatile': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_mastery.cleave': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_mastery.graze': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_mastery.nick': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_mastery.push': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_mastery.sap': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_mastery.slow': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_mastery.topple': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'weapon_mastery.vex': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'tool.alchemists-supplies': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.brewers-supplies': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.calligraphers-supplies': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.carpenters-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.cartographers-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.cobblers-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.cooks-utensils': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.glassblowers-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.jewelers-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.leatherworkers-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.masons-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.painters-supplies': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.potters-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.smiths-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.tinkers-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.weavers-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.woodcarvers-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.disguise-kit': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.forgery-kit': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.gaming-set': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.herbalism-kit': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.musical-instrument': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.navigators-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.poisoners-kit': UNREPRESENTED_TOOLS_LANGUAGES,
  'tool.thieves-tools': UNREPRESENTED_TOOLS_LANGUAGES,
  'adventuring_gear.acid': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.alchemists-fire': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.ammunition': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.antitoxin': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.arcane-focus': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.backpack': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.ball-bearings': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.barrel': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.basket': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.bedroll': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.bell': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.blanket': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.block-and-tackle': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.book': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.bottle-glass': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.bucket': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.burglars-pack': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.caltrops': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.candle': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.case-crossbow-bolt': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.case-map-or-scroll': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.chain': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.chest': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.climbers-kit': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.clothes-fine': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.clothes-travelers': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.component-pouch': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.costume': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.crowbar': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.diplomats-pack': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.druidic-focus': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.dungeoneers-pack': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.entertainers-pack': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.explorers-pack': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.flask': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.grappling-hook': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.healers-kit': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.holy-symbol': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.holy-water': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.hunting-trap': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.ink': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.ink-pen': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.jug': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.ladder': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.lamp': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.lantern-bullseye': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.lantern-hooded': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.lock': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.magnifying-glass': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.manacles': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.map': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.mirror': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.net': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.oil': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.paper': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.parchment': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.perfume': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.poison-basic': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.pole': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.pot-iron': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.potion-of-healing': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.pouch': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.priests-pack': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.quiver': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.ram-portable': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.rations': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.robe': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.rope': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.sack': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.scholars-pack': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.shovel': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.signal-whistle': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.spell-scroll': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.spikes-iron': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.spyglass': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.string': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.tent': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.tinderbox': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.torch': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.vial': UNREPRESENTED_COINS_COSTS,
  'adventuring_gear.waterskin': UNREPRESENTED_COINS_COSTS,
} as const satisfies { readonly [K in SrdRuleIdOfKind<'weapon' | 'armor' | 'weapon_property' | 'weapon_mastery' | 'tool' | 'adventuring_gear'>]: RuleStatus };
