import type { SrdRuleIdOfKind } from '../rule-index';
import type { RuleStatus } from '../rule-status-types';

/**
 * RULE_STATUS for the chapter rule sections and the Rules Glossary.
 * HAND-MAINTAINED: a new id in the generated index fails this record to
 * compile until it is given a status here.
 *
 * `unrepresented` names the unit that will type the rule (SRD-TYPED plan,
 * synthesis §6.2); `UNASSIGNED` means no planned unit owns it yet. A status
 * other than `unrepresented` cites its evidence beside it; `executed` names
 * only witnesses that exercise every clause of the entry.
 */
const UNREPRESENTED_ACTIONS_COMPLETE = { status: 'unrepresented', unit: 'ACTIONS-COMPLETE' } as const;
const UNREPRESENTED_CLASS_TABLES = { status: 'unrepresented', unit: 'CLASS-TABLES' } as const;
const UNREPRESENTED_CONDITION_D20 = { status: 'unrepresented', unit: 'CONDITION-D20' } as const;
const UNREPRESENTED_COVER_EDGE = { status: 'unrepresented', unit: 'COVER-EDGE' } as const;
const UNREPRESENTED_FEATURE_REGISTRY = { status: 'unrepresented', unit: 'FEATURE-REGISTRY' } as const;
const UNREPRESENTED_FOOTPRINT = { status: 'unrepresented', unit: 'FOOTPRINT' } as const;
const UNREPRESENTED_MAGIC_ITEMS = { status: 'unrepresented', unit: 'MAGIC-ITEMS' } as const;
const UNREPRESENTED_MON_TABLES = { status: 'unrepresented', unit: 'MON-TABLES' } as const;
const UNREPRESENTED_MON_VOCAB = { status: 'unrepresented', unit: 'MON-VOCAB' } as const;
const UNREPRESENTED_MOVE_COST = { status: 'unrepresented', unit: 'MOVE-COST' } as const;
const UNREPRESENTED_MOVEMENT_MODES = { status: 'unrepresented', unit: 'MOVEMENT-MODES' } as const;
const UNREPRESENTED_ORIGINS_FEATS = { status: 'unrepresented', unit: 'ORIGINS-FEATS' } as const;
const UNREPRESENTED_OWNER_GATED_ROWS = { status: 'unrepresented', unit: 'OWNER-GATED-ROWS' } as const;
const UNREPRESENTED_SPELL_EFFECT_FACTS = { status: 'unrepresented', unit: 'SPELL-EFFECT-FACTS' } as const;
const UNREPRESENTED_SPELL_HEADERS = { status: 'unrepresented', unit: 'SPELL-HEADERS' } as const;
const UNREPRESENTED_SRD_MONSTERS = { status: 'unrepresented', unit: 'SRD-MONSTERS' } as const;
const UNREPRESENTED_UNASSIGNED = { status: 'unrepresented', unit: 'UNASSIGNED' } as const;
const UNREPRESENTED_WEAPONS_ARMOR_DATA = { status: 'unrepresented', unit: 'WEAPONS-ARMOR-DATA' } as const;
const UNREPRESENTED_WORLD_TOOLBOX = { status: 'unrepresented', unit: 'WORLD-TOOLBOX' } as const;

export const RULES_STATUS = {
  'rule_section.playing-the-game': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.rhythm-of-play': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.the-six-abilities': UNREPRESENTED_CLASS_TABLES,
  'rule_section.playing-the-game.d20-tests': UNREPRESENTED_CONDITION_D20,
  'rule_section.playing-the-game.ability-checks': UNREPRESENTED_CONDITION_D20,
  'rule_section.playing-the-game.saving-throws': UNREPRESENTED_CONDITION_D20,
  'rule_section.playing-the-game.attack-rolls': UNREPRESENTED_CONDITION_D20,
  'rule_section.playing-the-game.advantage-disadvantage': UNREPRESENTED_CONDITION_D20,
  'rule_section.playing-the-game.proficiency': UNREPRESENTED_CLASS_TABLES,
  'rule_section.playing-the-game.actions': UNREPRESENTED_ACTIONS_COMPLETE,
  'rule_section.playing-the-game.bonus-actions': UNREPRESENTED_ACTIONS_COMPLETE,
  'rule_section.playing-the-game.reactions': UNREPRESENTED_ACTIONS_COMPLETE,
  'rule_section.playing-the-game.social-interaction': UNREPRESENTED_ACTIONS_COMPLETE,
  'rule_section.playing-the-game.exploration': UNREPRESENTED_WORLD_TOOLBOX,
  'rule_section.playing-the-game.vision-and-light': UNREPRESENTED_WORLD_TOOLBOX,
  'rule_section.playing-the-game.hiding': UNREPRESENTED_ACTIONS_COMPLETE,
  'rule_section.playing-the-game.interacting-with-objects': UNREPRESENTED_WORLD_TOOLBOX,
  'rule_section.playing-the-game.hazards': UNREPRESENTED_WORLD_TOOLBOX,
  'rule_section.playing-the-game.travel': UNREPRESENTED_WORLD_TOOLBOX,
  'rule_section.playing-the-game.combat': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.the-order-of-combat': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.movement-and-position': UNREPRESENTED_MOVEMENT_MODES,
  'rule_section.playing-the-game.making-an-attack': UNREPRESENTED_CONDITION_D20,
  'rule_section.playing-the-game.ranged-attacks': UNREPRESENTED_CONDITION_D20,
  'rule_section.playing-the-game.melee-attacks': UNREPRESENTED_CONDITION_D20,
  'rule_section.playing-the-game.mounted-combat': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.underwater-combat': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.damage-and-healing': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.hit-points': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.damage-rolls': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.critical-hits': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.saving-throws-and-damage': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.damage-types': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.resistance-and-vulnerability': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.immunity': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.healing': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.dropping-to-0-hit-points': UNREPRESENTED_UNASSIGNED,
  'rule_section.playing-the-game.temporary-hit-points': UNREPRESENTED_UNASSIGNED,
  'rule_section.character-creation': UNREPRESENTED_UNASSIGNED,
  'rule_section.character-creation.choose-a-character-sheet': UNREPRESENTED_UNASSIGNED,
  'rule_section.character-creation.create-your-character': UNREPRESENTED_UNASSIGNED,
  'rule_section.character-creation.level-advancement': UNREPRESENTED_CLASS_TABLES,
  'rule_section.character-creation.starting-at-higher-levels': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.character-creation.multiclassing': UNREPRESENTED_CLASS_TABLES,
  'rule_section.character-creation.trinkets': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.classes': UNREPRESENTED_CLASS_TABLES,
  'rule_section.sorcerer.metamagic-options': UNREPRESENTED_FEATURE_REGISTRY,
  'rule_section.warlock.eldritch-invocation-options': UNREPRESENTED_FEATURE_REGISTRY,
  'rule_section.character-origins': UNREPRESENTED_ORIGINS_FEATS,
  'rule_section.character-origins.character-backgrounds': UNREPRESENTED_ORIGINS_FEATS,
  'rule_section.character-origins.character-species': UNREPRESENTED_ORIGINS_FEATS,
  'rule_section.feats': UNREPRESENTED_ORIGINS_FEATS,
  'rule_section.feats.feat-descriptions': UNREPRESENTED_ORIGINS_FEATS,
  'rule_section.feats.origin-feats': UNREPRESENTED_ORIGINS_FEATS,
  'rule_section.feats.general-feats': UNREPRESENTED_ORIGINS_FEATS,
  'rule_section.feats.fighting-style-feats': UNREPRESENTED_ORIGINS_FEATS,
  'rule_section.feats.epic-boon-feats': UNREPRESENTED_ORIGINS_FEATS,
  'rule_section.equipment': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'rule_section.equipment.coins': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.equipment.weapons': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'rule_section.equipment.properties': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'rule_section.equipment.mastery-properties': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'rule_section.equipment.armor': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'rule_section.equipment.tools': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.equipment.adventuring-gear': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.equipment.mounts-and-vehicles': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.equipment.lifestyle-expenses': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.equipment.food-drink-and-lodging': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.equipment.hirelings': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.equipment.spellcasting': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.equipment.magic-items': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.equipment.crafting-nonmagical-items': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.equipment.brewing-potions-of-healing': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.equipment.scribing-spell-scrolls': UNREPRESENTED_OWNER_GATED_ROWS,
  'rule_section.spells': UNREPRESENTED_SPELL_HEADERS,
  'rule_section.spells.gaining-spells': UNREPRESENTED_SPELL_HEADERS,
  'rule_section.spells.casting-spells': UNREPRESENTED_SPELL_HEADERS,
  'rule_section.spells.spell-descriptions': UNREPRESENTED_SPELL_HEADERS,
  'rule_section.rules-glossary': UNREPRESENTED_UNASSIGNED,
  'rule_section.gameplay-toolbox': UNREPRESENTED_WORLD_TOOLBOX,
  'rule_section.gameplay-toolbox.travel-pace': UNREPRESENTED_WORLD_TOOLBOX,
  'rule_section.gameplay-toolbox.creating-a-background': UNREPRESENTED_ORIGINS_FEATS,
  'rule_section.gameplay-toolbox.curses-and-magical-contagions': UNREPRESENTED_WORLD_TOOLBOX,
  'rule_section.gameplay-toolbox.environmental-effects': UNREPRESENTED_WORLD_TOOLBOX,
  'rule_section.gameplay-toolbox.fear-and-mental-stress': UNREPRESENTED_WORLD_TOOLBOX,
  'rule_section.gameplay-toolbox.poison': UNREPRESENTED_WORLD_TOOLBOX,
  'rule_section.gameplay-toolbox.traps': UNREPRESENTED_WORLD_TOOLBOX,
  'rule_section.gameplay-toolbox.combat-encounters': UNREPRESENTED_MON_TABLES,
  'rule_section.magic-items': UNREPRESENTED_MAGIC_ITEMS,
  'rule_section.magic-items.magic-item-categories': UNREPRESENTED_MAGIC_ITEMS,
  'rule_section.magic-items.magic-item-rarity': UNREPRESENTED_MAGIC_ITEMS,
  'rule_section.magic-items.activating-a-magic-item': UNREPRESENTED_MAGIC_ITEMS,
  'rule_section.magic-items.the-next-dawn': UNREPRESENTED_MAGIC_ITEMS,
  'rule_section.magic-items.cursed-items': UNREPRESENTED_MAGIC_ITEMS,
  'rule_section.magic-items.magic-item-resilience': UNREPRESENTED_MAGIC_ITEMS,
  'rule_section.magic-items.crafting-magic-items': UNREPRESENTED_MAGIC_ITEMS,
  'rule_section.magic-items.sentient-magic-items': UNREPRESENTED_MAGIC_ITEMS,
  'rule_section.magic-items.magic-items-a-z': UNREPRESENTED_MAGIC_ITEMS,
  'rule_section.monsters': UNREPRESENTED_SRD_MONSTERS,
  'rule_section.monsters.stat-block-overview': UNREPRESENTED_MON_VOCAB,
  'rule_section.monsters.parts-of-a-stat-block': UNREPRESENTED_MON_VOCAB,
  'rule_section.monsters.running-a-monster': UNREPRESENTED_MON_VOCAB,
  'rule_section.monsters.monsters-a-z': UNREPRESENTED_SRD_MONSTERS,
  'rule_section.monsters.animals': UNREPRESENTED_SRD_MONSTERS,
  'glossary.ability-check': UNREPRESENTED_CONDITION_D20,
  'glossary.ability-score-and-modifier': UNREPRESENTED_CLASS_TABLES,
  'glossary.action': UNREPRESENTED_ACTIONS_COMPLETE,
  // Two d20s, the higher kept (resolution.test.ts); duplicate sources stay at
  // two dice and one Disadvantage cancels them (roll-defense-modifiers.test.ts).
  'glossary.advantage': {
    status: 'executed',
    witness: [
      'tests/unit/combat/resolution.test.ts::consumes one draw normally and two sequential draws for advantage and disadvantage',
      'tests/unit/vtt/roll-defense-modifiers.test.ts::advantage_sources: duplicate sources stay at two dice, one disadvantage cancels them, and Faerie-Fire scope does not affect another target',
    ],
  },
  'glossary.adventure': UNREPRESENTED_UNASSIGNED,
  'glossary.alignment': UNREPRESENTED_UNASSIGNED,
  'glossary.ally': UNREPRESENTED_UNASSIGNED,
  'glossary.area-of-effect': UNREPRESENTED_UNASSIGNED,
  'glossary.armor-class': UNREPRESENTED_UNASSIGNED,
  'glossary.armor-training': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'glossary.attack-roll': UNREPRESENTED_CONDITION_D20,
  'glossary.attitude': UNREPRESENTED_ACTIONS_COMPLETE,
  'glossary.attunement': UNREPRESENTED_MAGIC_ITEMS,
  'glossary.blindsight': UNREPRESENTED_UNASSIGNED,
  'glossary.bloodied': UNREPRESENTED_UNASSIGNED,
  'glossary.bonus-action': UNREPRESENTED_ACTIONS_COMPLETE,
  'glossary.breaking-objects': UNREPRESENTED_WORLD_TOOLBOX,
  'glossary.bright-light': UNREPRESENTED_WORLD_TOOLBOX,
  // Typed per stat block (src/combat/statblock.ts:30 MovementKind, :581
  // movement); combat speed is the walking speed only (:1122-1123).
  'glossary.burrow-speed': { status: 'typed_only', awaiting: ['movement_modes'] },
  'glossary.campaign': UNREPRESENTED_UNASSIGNED,
  'glossary.cantrip': UNREPRESENTED_SPELL_HEADERS,
  'glossary.carrying-capacity': UNREPRESENTED_OWNER_GATED_ROWS,
  'glossary.challenge-rating': UNREPRESENTED_MON_TABLES,
  'glossary.character-sheet': UNREPRESENTED_UNASSIGNED,
  'glossary.climbing': UNREPRESENTED_MOVEMENT_MODES,
  // Typed per stat block (src/combat/statblock.ts:30 MovementKind, :581
  // movement); combat speed is the walking speed only (:1122-1123).
  'glossary.climb-speed': { status: 'typed_only', awaiting: ['movement_modes'] },
  'glossary.concentration': UNREPRESENTED_SPELL_HEADERS,
  'glossary.condition': UNREPRESENTED_CONDITION_D20,
  'glossary.cover': UNREPRESENTED_COVER_EDGE,
  'glossary.crawling': UNREPRESENTED_MOVEMENT_MODES,
  'glossary.creature': UNREPRESENTED_UNASSIGNED,
  'glossary.creature-type': UNREPRESENTED_MON_VOCAB,
  'glossary.critical-hit': UNREPRESENTED_CONDITION_D20,
  'glossary.curses': UNREPRESENTED_WORLD_TOOLBOX,
  'glossary.d20-test': UNREPRESENTED_CONDITION_D20,
  'glossary.damage': UNREPRESENTED_UNASSIGNED,
  'glossary.damage-roll': UNREPRESENTED_UNASSIGNED,
  'glossary.damage-threshold': UNREPRESENTED_WORLD_TOOLBOX,
  'glossary.damage-types': UNREPRESENTED_UNASSIGNED,
  'glossary.darkness': UNREPRESENTED_WORLD_TOOLBOX,
  'glossary.darkvision': UNREPRESENTED_UNASSIGNED,
  'glossary.dead': UNREPRESENTED_UNASSIGNED,
  // The entry's one clause: a PC starting its turn at 0 Hit Points must make a Death Save.
  'glossary.death-saving-throw': {
    status: 'executed',
    witness: ['tests/unit/combat/death-saves.test.ts::queues a closed death_save PendingDecision at the start of a dying PC turn'],
  },
  'glossary.difficult-terrain': UNREPRESENTED_MOVE_COST,
  'glossary.difficulty-class': UNREPRESENTED_CONDITION_D20,
  'glossary.dim-light': UNREPRESENTED_WORLD_TOOLBOX,
  'glossary.disadvantage': UNREPRESENTED_CONDITION_D20,
  'glossary.encounter': UNREPRESENTED_UNASSIGNED,
  'glossary.enemy': UNREPRESENTED_UNASSIGNED,
  'glossary.experience-points': UNREPRESENTED_OWNER_GATED_ROWS,
  'glossary.expertise': UNREPRESENTED_CLASS_TABLES,
  'glossary.flying': UNREPRESENTED_MOVEMENT_MODES,
  'glossary.fly-speed': UNREPRESENTED_MOVEMENT_MODES,
  'glossary.grappling': UNREPRESENTED_CONDITION_D20,
  'glossary.hazard': UNREPRESENTED_WORLD_TOOLBOX,
  'glossary.healing': UNREPRESENTED_UNASSIGNED,
  'glossary.heavily-obscured': UNREPRESENTED_WORLD_TOOLBOX,
  'glossary.heroic-inspiration': UNREPRESENTED_UNASSIGNED,
  'glossary.high-jump': UNREPRESENTED_UNASSIGNED,
  'glossary.hit-point-dice': UNREPRESENTED_CLASS_TABLES,
  'glossary.hit-points': UNREPRESENTED_UNASSIGNED,
  'glossary.hover': UNREPRESENTED_MOVEMENT_MODES,
  'glossary.illusions': UNREPRESENTED_UNASSIGNED,
  'glossary.immunity': UNREPRESENTED_UNASSIGNED,
  'glossary.improvised-weapons': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'glossary.initiative': UNREPRESENTED_CONDITION_D20,
  'glossary.jumping': UNREPRESENTED_UNASSIGNED,
  'glossary.knocking-out-a-creature': UNREPRESENTED_UNASSIGNED,
  'glossary.lightly-obscured': UNREPRESENTED_WORLD_TOOLBOX,
  'glossary.long-jump': UNREPRESENTED_UNASSIGNED,
  'glossary.long-rest': UNREPRESENTED_UNASSIGNED,
  'glossary.magical-effect': UNREPRESENTED_UNASSIGNED,
  'glossary.monster': UNREPRESENTED_UNASSIGNED,
  'glossary.nonplayer-character': UNREPRESENTED_UNASSIGNED,
  'glossary.object': UNREPRESENTED_WORLD_TOOLBOX,
  'glossary.occupied-space': UNREPRESENTED_FOOTPRINT,
  'glossary.opportunity-attacks': UNREPRESENTED_UNASSIGNED,
  'glossary.passive-perception': UNREPRESENTED_UNASSIGNED,
  'glossary.per-day': UNREPRESENTED_UNASSIGNED,
  'glossary.player-character': UNREPRESENTED_UNASSIGNED,
  'glossary.possession': UNREPRESENTED_UNASSIGNED,
  'glossary.proficiency': UNREPRESENTED_CLASS_TABLES,
  'glossary.reach': UNREPRESENTED_UNASSIGNED,
  'glossary.reaction': UNREPRESENTED_ACTIONS_COMPLETE,
  'glossary.resistance': UNREPRESENTED_UNASSIGNED,
  'glossary.ritual': UNREPRESENTED_SPELL_HEADERS,
  'glossary.round-down': UNREPRESENTED_UNASSIGNED,
  'glossary.save': UNREPRESENTED_CONDITION_D20,
  'glossary.saving-throw': UNREPRESENTED_CONDITION_D20,
  'glossary.shape-shifting': UNREPRESENTED_UNASSIGNED,
  'glossary.short-rest': UNREPRESENTED_UNASSIGNED,
  'glossary.simultaneous-effects': UNREPRESENTED_UNASSIGNED,
  'glossary.size': UNREPRESENTED_FOOTPRINT,
  'glossary.skill': UNREPRESENTED_CLASS_TABLES,
  'glossary.speed': UNREPRESENTED_MOVEMENT_MODES,
  'glossary.spell': UNREPRESENTED_SPELL_HEADERS,
  'glossary.spell-attack': UNREPRESENTED_SPELL_HEADERS,
  'glossary.spellcasting-focus': UNREPRESENTED_SPELL_HEADERS,
  'glossary.stable': UNREPRESENTED_UNASSIGNED,
  'glossary.stat-block': UNREPRESENTED_MON_VOCAB,
  'glossary.surprise': UNREPRESENTED_CONDITION_D20,
  'glossary.swimming': UNREPRESENTED_MOVEMENT_MODES,
  // Typed per stat block (src/combat/statblock.ts:30 MovementKind, :581
  // movement); combat speed is the walking speed only (:1122-1123).
  'glossary.swim-speed': { status: 'typed_only', awaiting: ['movement_modes'] },
  'glossary.target': UNREPRESENTED_UNASSIGNED,
  'glossary.telepathy': UNREPRESENTED_MON_VOCAB,
  'glossary.teleportation': UNREPRESENTED_UNASSIGNED,
  'glossary.temporary-hit-points': UNREPRESENTED_UNASSIGNED,
  'glossary.tremorsense': UNREPRESENTED_UNASSIGNED,
  'glossary.truesight': UNREPRESENTED_UNASSIGNED,
  'glossary.unarmed-strike': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'glossary.unoccupied-space': UNREPRESENTED_FOOTPRINT,
  'glossary.vulnerability': UNREPRESENTED_UNASSIGNED,
  'glossary.weapon': UNREPRESENTED_WEAPONS_ARMOR_DATA,
  'glossary.weapon-attack': UNREPRESENTED_UNASSIGNED,
  'condition.blinded': UNREPRESENTED_CONDITION_D20,
  'condition.charmed': UNREPRESENTED_CONDITION_D20,
  // Typed (src/combat/conditions.ts:195-204, clause 'cannot_hear' at :498);
  // nothing reads the clause, so no check fails for want of hearing.
  'condition.deafened': { status: 'typed_only', awaiting: ['perception_filters'] },
  'condition.exhaustion': UNREPRESENTED_CONDITION_D20,
  'condition.frightened': UNREPRESENTED_CONDITION_D20,
  'condition.grappled': UNREPRESENTED_CONDITION_D20,
  'condition.incapacitated': UNREPRESENTED_CONDITION_D20,
  'condition.invisible': UNREPRESENTED_CONDITION_D20,
  'condition.paralyzed': UNREPRESENTED_CONDITION_D20,
  'condition.petrified': UNREPRESENTED_CONDITION_D20,
  'condition.poisoned': UNREPRESENTED_CONDITION_D20,
  'condition.prone': UNREPRESENTED_CONDITION_D20,
  'condition.restrained': UNREPRESENTED_CONDITION_D20,
  'condition.stunned': UNREPRESENTED_CONDITION_D20,
  'condition.unconscious': UNREPRESENTED_CONDITION_D20,
  'action.attack': UNREPRESENTED_ACTIONS_COMPLETE,
  'action.dash': UNREPRESENTED_ACTIONS_COMPLETE,
  'action.disengage': UNREPRESENTED_ACTIONS_COMPLETE,
  'action.dodge': UNREPRESENTED_ACTIONS_COMPLETE,
  'action.help': UNREPRESENTED_ACTIONS_COMPLETE,
  'action.hide': UNREPRESENTED_ACTIONS_COMPLETE,
  'action.influence': UNREPRESENTED_ACTIONS_COMPLETE,
  'action.magic': UNREPRESENTED_ACTIONS_COMPLETE,
  'action.ready': UNREPRESENTED_ACTIONS_COMPLETE,
  'action.search': UNREPRESENTED_ACTIONS_COMPLETE,
  'action.study': UNREPRESENTED_ACTIONS_COMPLETE,
  'action.utilize': UNREPRESENTED_ACTIONS_COMPLETE,
  'area_of_effect.cone': UNREPRESENTED_SPELL_EFFECT_FACTS,
  'area_of_effect.cube': UNREPRESENTED_SPELL_EFFECT_FACTS,
  'area_of_effect.cylinder': UNREPRESENTED_SPELL_EFFECT_FACTS,
  'area_of_effect.emanation': UNREPRESENTED_SPELL_EFFECT_FACTS,
  'area_of_effect.line': UNREPRESENTED_SPELL_EFFECT_FACTS,
  'area_of_effect.sphere': UNREPRESENTED_SPELL_EFFECT_FACTS,
  'attitude.friendly': UNREPRESENTED_ACTIONS_COMPLETE,
  'attitude.hostile': UNREPRESENTED_ACTIONS_COMPLETE,
  'attitude.indifferent': UNREPRESENTED_ACTIONS_COMPLETE,
  'hazard.burning': UNREPRESENTED_WORLD_TOOLBOX,
  'hazard.dehydration': UNREPRESENTED_WORLD_TOOLBOX,
  'hazard.falling': UNREPRESENTED_WORLD_TOOLBOX,
  'hazard.malnutrition': UNREPRESENTED_WORLD_TOOLBOX,
  'hazard.suffocation': UNREPRESENTED_WORLD_TOOLBOX,
} as const satisfies { readonly [K in SrdRuleIdOfKind<'rule_section' | 'glossary' | 'condition' | 'action' | 'area_of_effect' | 'attitude' | 'hazard'>]: RuleStatus };
