export type SpellSrdLocator =
  | `docs/srd/source/spell-descriptions.txt:${number}`
  | `docs/srd/source/spell-descriptions.txt:${number}-${number}`;

export type SpellEngineLimitationCode =
  | 'post_hit_cast_timing_prearmed'
  | 'creature_size_save_mode_unavailable'
  | 'effect_escape_action_unavailable'
  | 'persistent_area_move_action_unavailable'
  | 'persistent_area_entry_trigger_unavailable'
  | 'shapechange_reversion_unavailable';

export interface SpellEngineLimitation {
  readonly code: SpellEngineLimitationCode;
  readonly note: string;
}

export interface SpellKbEntry {
  readonly ruleId: `R-SPELL-${string}`;
  readonly spellId: string;
  readonly srdLocator: SpellSrdLocator;
  readonly rulingGuidance: string;
  readonly limitations?: readonly SpellEngineLimitation[];
  readonly fieldCitations?: Readonly<{
    readonly identity: SpellSrdLocator;
    readonly castingTime: SpellSrdLocator;
    readonly components: SpellSrdLocator;
    readonly targeting: SpellSrdLocator;
    readonly operation: SpellSrdLocator;
  }>;
}

function entry(
  ruleId: `R-SPELL-${string}`,
  spellId: string,
  line: `${number}` | `${number}-${number}`,
  rulingGuidance: string,
): SpellKbEntry {
  return { ruleId, spellId, srdLocator: `docs/srd/source/spell-descriptions.txt:${line}`, rulingGuidance };
}

/** One decision-oriented SRD locator for every executable manifest spell. */
export const SPELL_KB_ENTRIES = [
  entry('R-SPELL-001', 'acid-splash', '37-51', 'Place the 5-foot sphere within 60 feet; a failed Dexterity save takes scaling Acid damage.'),
  entry('R-SPELL-002', 'chill-touch', '1066', 'Resolve a melee spell attack for scaling Necrotic damage and suppress healing until the next turn.'),
  entry('R-SPELL-003', 'dancing-lights', '1906', 'Track up to four dim lights, their 60-foot bonus-action movement, and concentration.'),
  entry('R-SPELL-004', 'elementalism', '2630', 'Choose one listed minor elemental effect; the spell states no shared active-effect cap.'),
  entry('R-SPELL-005', 'fire-bolt', '3184-3200', 'Resolve a 120-foot ranged spell attack and apply the caster-level Fire damage scaling.'),
  entry('R-SPELL-006', 'guidance', '4000', 'Choose a skill and add 1d4 to one qualifying check during the one-minute concentration window.'),
  entry('R-SPELL-007', 'light', '4816', 'Create one 20-foot bright and 20-foot dim light source for one hour.'),
  entry('R-SPELL-008', 'mage-hand', '4931', 'Keep the hand within 30 feet and enforce its 10-pound carry limit.'),
  entry('R-SPELL-009', 'mending', '5322', 'Repair a break no larger than 1 foot without restoring lost magic.'),
  entry('R-SPELL-010', 'message', '5341', 'Establish a 120-foot whisper-and-reply link that magical silence blocks.'),
  entry('R-SPELL-011', 'minor-illusion', '5420', 'Choose sound or a static image no larger than a 5-foot cube.'),
  entry('R-SPELL-012', 'poison-spray', '5925', 'Resolve the 30-foot ranged spell attack for scaling Poison damage.'),
  entry('R-SPELL-013', 'prestidigitation', '6034', 'Choose a listed minor magical effect and keep no more than three active.'),
  entry('R-SPELL-014', 'ray-of-frost', '6427', 'On a ranged spell hit, deal scaling Cold damage and reduce Speed by 10 feet.'),
  entry('R-SPELL-015', 'resistance', '6540', 'Choose a damage type and subtract 1d4 from one instance during concentration.'),
  entry('R-SPELL-016', 'sacred-flame', '6645', 'A failed Dexterity save takes scaling Radiant damage; success negates it.'),
  entry('R-SPELL-017', 'shocking-grasp', '7006', 'A melee spell hit deals scaling Lightning damage and blocks opportunity attacks briefly.'),
  entry('R-SPELL-018', 'spare-the-dying', '7181', 'At reference-party level 7, stabilize a living creature at 0 HP within 30 feet.'),
  entry('R-SPELL-019', 'thaumaturgy', '7842', 'Choose a listed wonder and keep no more than three one-minute effects active.'),
  {
    ...entry('R-SPELL-020', 'true-strike', '8079-8094', 'Use the caster’s spellcasting ability for the weapon attack and damage, optionally convert the weapon damage to Radiant, and add Radiant d6s at levels 5, 11, and 17.'),
    fieldCitations: {
      identity: 'docs/srd/source/spell-descriptions.txt:8079-8080',
      castingTime: 'docs/srd/source/spell-descriptions.txt:8081',
      components: 'docs/srd/source/spell-descriptions.txt:8083-8084',
      targeting: 'docs/srd/source/spell-descriptions.txt:8082-8087',
      operation: 'docs/srd/source/spell-descriptions.txt:8086-8094',
    },
  },
  entry('R-SPELL-021', 'bane', '670', 'Up to three targets, plus one per higher slot, subtract 1d4 after failed Charisma saves.'),
  entry('R-SPELL-022', 'charm-person', '1046', 'Targets make Wisdom saves with the hostile-combat advantage rule before becoming Charmed.'),
  entry('R-SPELL-023', 'bless', '824', 'Up to three targets, plus one per higher slot, add 1d4 to attacks and saves during concentration.'),
  entry('R-SPELL-024', 'burning-hands', '924', 'Use the 15-foot cone; Dexterity success halves the 3d6 Fire damage, scaling 1d6 per slot.'),
  entry('R-SPELL-025', 'cure-wounds', '1895', 'Restore 2d8 plus the spellcasting modifier, adding 2d8 per higher slot.'),
  entry('R-SPELL-026', 'false-life', '2930', 'Grant 2d4+4 temporary HP, adding 5 per higher slot.'),
  entry('R-SPELL-027', 'guiding-bolt', '4011', 'A ranged hit deals 4d6 Radiant damage and grants advantage to the next attack.'),
  entry('R-SPELL-028', 'healing-word', '4169', 'As a bonus action, restore 2d4 plus the spellcasting modifier at 60 feet.'),
  entry('R-SPELL-029', 'inflict-wounds', '4593', 'A Constitution save halves 2d10 Necrotic damage, adding 1d10 per higher slot.'),
  entry('R-SPELL-030', 'magic-missile', '5033', 'Allocate every dart; each automatically deals 1d4+1 Force damage and higher slots add darts.'),
  entry('R-SPELL-031', 'shield', '6937', 'When hit by an attack or targeted by Magic Missile, react for +5 AC and Magic Missile immunity until the next turn.'),
  entry('R-SPELL-032', 'shield-of-faith', '6956', 'Grant +2 AC to one creature within 60 feet while concentration lasts.'),
  entry('R-SPELL-033', 'thunderwave', '7868', 'Use the 15-foot cube; failure takes full Thunder damage and pushes 10 feet, success takes half.'),
  entry('R-SPELL-034', 'alarm', '70', 'Ward the selected 20-foot cube for 8 hours and choose audible or mental notification.'),
  entry('R-SPELL-035', 'chromatic-orb', '1079', 'Choose the damage type, then resolve a 90-foot ranged attack for 3d8 plus 1d8 per higher slot.'),
  entry('R-SPELL-036', 'color-spray', '1193', 'Creatures in the 15-foot cone that fail Constitution saves are Blinded through the next turn.'),
  entry('R-SPELL-037', 'command', '1209', 'Choose a listed command; failed Wisdom saves bind targets for their next turn.'),
  entry('R-SPELL-038', 'comprehend-languages', '1304', 'Understand literal spoken and touched written language, taking one minute per written page.'),
  entry('R-SPELL-039', 'create-or-destroy-water', '1797', 'Choose water quantity or rain-cube mode and apply its distinct higher-slot scaling.'),
  entry('R-SPELL-040', 'detect-evil-and-good', '2068', 'While concentrating, sense listed creature types and hallowed or desecrated places within 30 feet.'),
  entry('R-SPELL-041', 'detect-magic', '2085', 'While concentrating, sense magic within 30 feet and inspect visible auras.'),
  entry('R-SPELL-042', 'detect-poison-and-disease', '2103', 'While concentrating, sense and identify poison, poisonous creatures, and disease within 30 feet.'),
  entry('R-SPELL-043', 'disguise-self', '2185', 'Track the one-hour visual disguise and its one-foot apparent-height constraint.'),
  entry('R-SPELL-044', 'expeditious-retreat', '2810', 'Dash immediately and permit later bonus-action Dashes while concentration lasts.'),
  entry('R-SPELL-045', 'feather-fall', '2964', 'The reaction protects up to five falling creatures with 60-foot-per-round descent.'),
  entry('R-SPELL-046', 'find-familiar', '2979', 'Create the chosen familiar form and enforce the 100-foot telepathy core.'),
  entry('R-SPELL-047', 'floating-disk', '3335', 'Track the 3-foot disk, 500-pound capacity, 20-foot follow distance, and 100-foot cutoff.'),
  entry('R-SPELL-048', 'fog-cloud', '3396', 'Place a heavily obscured 20-foot-radius sphere, adding 20 feet per higher slot.'),
  entry('R-SPELL-049', 'grease', '3883', 'Place the 10-foot square and knock creatures Prone on failed Dexterity saves.'),
  entry('R-SPELL-050', 'hideous-laughter', '4294', 'Failed Wisdom saves impose Prone and Incapacitated during concentration.'),
  entry('R-SPELL-051', 'ice-knife', '4430', 'Resolve the piercing spell attack, then the 5-foot cold burst with higher-slot scaling.'),
  entry('R-SPELL-052', 'identify', '4476', 'Reveal the touched item’s magical properties, charges, and affecting spells.'),
  entry('R-SPELL-053', 'illusory-script', '4495', 'Preserve the secret written message for ten days while Truesight reveals it.'),
  entry('R-SPELL-054', 'jump', '4710', 'Each affected target can spend 10 feet of movement for one 30-foot jump per turn.'),
  entry('R-SPELL-055', 'longstrider', '4904', 'Increase Speed by 10 feet for one hour, adding one target per higher slot.'),
  entry('R-SPELL-056', 'mage-armor', '4920', 'Set an unarmored target’s base AC to 13 plus Dexterity for eight hours.'),
  entry('R-SPELL-057', 'protection-from-evil-and-good', '6337', 'Apply the listed creature-type protections to one willing target during concentration.'),
  entry('R-SPELL-058', 'purify-food-and-drink', '6369', 'Purify nonmagical food and drink in the selected 5-foot-radius sphere.'),
  entry('R-SPELL-059', 'ray-of-sickness', '6456', 'A ranged hit deals Poison damage and applies the short Poisoned rider.'),
  entry('R-SPELL-060', 'sanctuary', '6662', 'Attackers must pass the Wisdom save while the sanctuary effect remains unbroken.'),
  entry('R-SPELL-061', 'silent-image', '7042', 'Place a movable image within a 15-foot cube and maintain concentration.'),
  entry('R-SPELL-062', 'sleep', '7103', 'Exclude the caster; failed Wisdom saves progress from Incapacitated to Unconscious.'),
  entry('R-SPELL-063', 'unseen-servant', '8131', 'Track the servant’s AC 10, 1 HP, Strength 2, movement, and distance limit.'),
  entry('R-SPELL-064', 'acid-arrow', '20', 'A ranged hit deals 4d4 Acid now and 2d4 later; a miss deals half initial damage.'),
  entry('R-SPELL-065', 'aid', '53', 'Increase current and maximum HP of up to three creatures by 5, plus 5 per higher slot.'),
  entry('R-SPELL-066', 'alter-self', '101', 'Choose aquatic adaptation, appearance change, or 1d6 natural weapons during concentration.'),
  entry('R-SPELL-067', 'arcane-lock', '479', 'Create the persistent lock and honor the password’s 5-foot, one-minute suppression.'),
  entry('R-SPELL-068', 'arcanists-magic-aura', '527', 'Choose mask or false aura; thirty daily castings make the selected aura permanent.'),
  entry('R-SPELL-069', 'augury', '595', 'Forecast the next 30 minutes and add a 25 percent no-answer risk per extra same-day casting.'),
  entry('R-SPELL-070', 'blindness-deafness', '859', 'Choose Blinded or Deafened; Constitution saves repeat at each affected target’s turn end.'),
  entry('R-SPELL-071', 'blur', '907', 'Attacks against the caster have disadvantage unless Blindsight or Truesight bypasses Blur.'),
  entry('R-SPELL-072', 'calm-emotions', '972', 'Failed Charisma saves allow suppression of fear or charm, or temporary indifference.'),
  entry('R-SPELL-073', 'continual-flame', '1647', 'Create persistent 20-foot bright and 20-foot dim light after consuming the ruby dust.'),
  entry('R-SPELL-074', 'darkness', '1929', 'Place 15-foot-radius magical darkness that blocks Darkvision and dispels overlapping light spells through level 2.'),
  entry('R-SPELL-075', 'darkvision', '1952', 'Grant 150-foot Darkvision to the touched willing creature for eight hours.'),
  entry('R-SPELL-076', 'detect-thoughts', '2119', 'Sense thoughts within 30 feet and use the listed Wisdom save and Intelligence escape check.'),
  entry('R-SPELL-077', 'dragons-breath', '2492', 'Grant a 15-foot breath cone dealing 3d6 chosen damage, plus 1d6 per higher slot.'),
  entry('R-SPELL-078', 'enhance-ability', '2660', 'Grant advantage on checks with one chosen ability, adding one target per higher slot.'),
  entry('R-SPELL-079', 'enlarge-reduce', '2679', 'Choose enlargement or reduction and track one size category plus the 1d4 damage adjustment.'),
  entry('R-SPELL-080', 'find-traps', '3131', 'Detect the presence and nature of qualifying traps within 120 feet without revealing location.'),
  entry('R-SPELL-081', 'flaming-sphere', '3276', 'Track the 5-foot sphere, 2d6 Fire core, 30-foot movement, light, and higher-slot damage.'),
  entry('R-SPELL-082', 'gentle-repose', '3682', 'Preserve the corpse against decay and undeath for ten days.'),
  entry('R-SPELL-083', 'gust-of-wind', '4027', 'Use the 60-by-10-foot line; failure pushes 15 feet and movement toward the source costs double.'),
  entry('R-SPELL-084', 'hold-person', '4342', 'A failed Wisdom save Paralyzes; repeat the save at each affected target’s turn end.'),
  entry('R-SPELL-085', 'invisibility', '4691', 'Apply Invisible for up to one hour during concentration, adding one target per higher slot.'),
  entry('R-SPELL-086', 'knock', '4734', 'Suppress Arcane Lock for one minute, open one lock, and emit sound audible to 300 feet.'),
  entry('R-SPELL-087', 'lesser-restoration', '4774', 'Remove one selected Blinded, Deafened, Paralyzed, or Poisoned condition.'),
  entry('R-SPELL-088', 'levitate', '4788', 'Lift up to 500 pounds by 20 feet and permit 20-foot altitude changes during concentration.'),
  entry('R-SPELL-089', 'locate-object', '4881', 'Sense the familiar object within 1,000 feet unless lead blocks the effect.'),
  entry('R-SPELL-090', 'magic-mouth', '5048', 'Store up to 25 words with a trigger sensed within 30 feet.'),
  entry('R-SPELL-091', 'magic-weapon', '5081', 'Apply the slot-tier magic weapon bonus for one hour.'),
  entry('R-SPELL-092', 'mind-spike', '5398', 'Wisdom success halves 3d8 Psychic damage; failure also enables location tracking.'),
  entry('R-SPELL-093', 'mirror-image', '5481', 'Track three duplicates and intercept an attack on 3 or higher on a d6.'),
  entry('R-SPELL-094', 'misty-step', '5523', 'Teleport up to 30 feet to a visible unoccupied space as a bonus action.'),
  entry('R-SPELL-095', 'prayer-of-healing', '6014', 'After ten minutes, heal up to five targets for 2d8 plus 1d8 per higher slot.'),
  entry('R-SPELL-096', 'protection-from-poison', '6359', 'Remove Poisoned, grant advantage on poison saves, and grant Poison resistance for one hour.'),
  entry('R-SPELL-097', 'ray-of-enfeeblement', '6407', 'Constitution success shortens the effect; failure applies its d8 damage penalty and repeat saves.'),
  entry('R-SPELL-098', 'rope-trick', '6619', 'Create the 3-by-5-foot extradimensional portal holding up to eight creatures.'),
  entry('R-SPELL-099', 'scorching-ray', '6678', 'Allocate three ranged spell attacks dealing 2d6 Fire each, plus one ray per higher slot.'),
  entry('R-SPELL-100', 'see-invisibility', '6784', 'For one hour, see invisible creatures and objects and perceive the Ethereal Plane.'),
  entry('R-SPELL-101', 'shatter', '6921', 'Use the 10-foot-radius sphere; Constitution success halves 3d8 Thunder damage.'),
  entry('R-SPELL-102', 'silence', '7026', 'Place the 20-foot-radius zone that prevents verbal components and grants Thunder immunity.'),
  entry('R-SPELL-103', 'spider-climb', '7278', 'Grant hands-free wall and ceiling movement with a climb Speed equal to Speed.'),
  entry('R-SPELL-104', 'spiritual-weapon', '7353', 'Make the immediate 1d8 plus modifier Force attack and track its movement and repeat attacks.'),
  entry('R-SPELL-105', 'suggestion', '7477', 'A failed Wisdom save Charms the target into the stated reasonable course during concentration.'),
  entry('R-SPELL-106', 'warding-bond', '8388', 'Within 60 feet, grant +1 AC and saves, all-damage resistance, and mirror damage to the caster.'),
  entry('R-SPELL-107', 'web', '8453', 'Place the 20-foot cube; save when entering or starting a turn there, and track 2d4 Fire ignition damage.'),
  entry('R-SPELL-108', 'zone-of-truth', '8699', 'A creature entering or starting its turn in the 15-foot-radius zone saves against knowingly speaking falsehoods.'),
  entry('R-SPELL-109', 'animate-dead', '219', 'Create one Skeleton or Zombie, add two per higher slot, and track 60-foot commands plus 24-hour control.'),
  entry('R-SPELL-110', 'beacon-of-hope', '726', 'Chosen creatures within 30 feet gain Wisdom-save and death-save advantage and maximize incoming healing.'),
  entry('R-SPELL-111', 'bestow-curse', '753', 'A failed Wisdom save applies one of four curses; slots 4/5/7/9 use the exact duration and concentration tiers.'),
  entry('R-SPELL-112', 'blink', '878', 'At each turn end, a 4–6 on d6 shifts the caster Ethereal until the next turn and limits return placement.'),
  entry('R-SPELL-113', 'clairvoyance', '1121', 'Place a one-mile sensor for seeing or hearing and switch its sense with a bonus action.'),
  entry('R-SPELL-114', 'counterspell', '1767', 'React to a visible creature within 60 feet casting with components; that creature makes the Constitution save.'),
  entry('R-SPELL-115', 'create-food-and-water', '1781', 'Create 45 pounds of food and 30 gallons of water; uneaten food spoils after 24 hours.'),
  entry('R-SPELL-116', 'daylight', '1967', 'Place 60-foot-radius sunlight with 60 additional feet of dim light and dispel overlapping Darkness through level 3.'),
  entry('R-SPELL-117', 'dispel-magic', '2268', 'End ongoing spells through level 3 automatically, using the slot level as the higher-slot automatic threshold.'),
  entry('R-SPELL-118', 'fear', '2945', 'Creatures in the 30-foot cone that fail Wisdom saves drop held objects and flee while Frightened.'),
  entry('R-SPELL-119', 'fireball', '3160', 'Place the 20-foot-radius sphere within 150 feet; deal 8d6 Fire, half on save, plus 1d6 per higher slot.'),
  entry('R-SPELL-120', 'fly', '3375', 'Grant a willing touched creature 60-foot flying speed and hover, adding one target per higher slot.'),
  entry('R-SPELL-121', 'gaseous-form', '3590', 'Apply the mist form’s 10-foot flight, hover, physical resistances, save advantage, and action restrictions.'),
  entry('R-SPELL-122', 'glyph-of-warding', '3802', 'Track the 10-foot glyph, 10-foot movement break, 20-foot explosion, 5d8 damage, and slot scaling.'),
  entry('R-SPELL-123', 'haste', '4143', 'Double Speed, add +2 AC, grant Dexterity-save advantage and the restricted extra action, then apply lethargy.'),
  entry('R-SPELL-124', 'hypnotic-pattern', '4410', 'Creatures seeing the 30-foot cube save or become Charmed, Incapacitated, and unable to move.'),
  entry('R-SPELL-125', 'lightning-bolt', '4831', 'Use the exact 100-by-5-foot line; deal 8d6 Lightning, half on save, plus 1d6 per higher slot.'),
  entry('R-SPELL-126', 'magic-circle', '4952', 'Place the 10-foot-radius, 20-foot-high cylinder and add one hour of duration per higher slot.'),
  entry('R-SPELL-127', 'major-image', '5150', 'Create a multisensory 20-foot-cube illusion; a level-4 slot makes it permanent without concentration.'),
  entry('R-SPELL-128', 'mass-healing-word', '5226', 'As a bonus action heal up to six creatures for 2d4 plus modifier, adding 1d4 per higher slot.'),
  entry('R-SPELL-129', 'meld-into-stone', '5289', 'Track the eight-hour merge, 5-foot exit, 6d6 partial-destruction damage, and 50 total-destruction damage.'),
  entry('R-SPELL-130', 'nondetection', '5647', 'For eight hours block Divination targeting and magical scrying of the touched eligible target.'),
  entry('R-SPELL-131', 'phantom-steed', '5758', 'Create the one-hour mount with Speed 100, 13-mile hourly travel, and a one-minute fade.'),
  entry('R-SPELL-132', 'protection-from-energy', '6322', 'Choose Acid, Cold, Fire, Lightning, or Thunder resistance for the willing touched target.'),
  entry('R-SPELL-133', 'remove-curse', '6499', 'End all curses on the touched creature; cursed-item handling instead breaks the owner’s attunement.'),
  entry('R-SPELL-134', 'revivify', '6604', 'Consume the diamond to return an eligible creature dead no longer than one minute with 1 HP.'),
  entry('R-SPELL-135', 'sending', '6825', 'Send at most 25 words to a creature you met or one described by someone who met it, with the cross-plane failure rule.'),
  entry('R-SPELL-136', 'sleet-storm', '7119', 'Place the exact 20-foot-radius, 40-foot-high cylinder with heavy obscurement, difficult terrain, and Prone saves.'),
  entry('R-SPELL-137', 'slow', '7140', 'Choose up to six creatures in the exact 40-foot cube and apply the listed penalties after failed Wisdom saves.'),
  entry('R-SPELL-138', 'speak-with-dead', '7214', 'Ask the eligible corpse up to five questions during ten minutes, respecting the ten-day repeat lockout.'),
  entry('R-SPELL-139', 'spirit-guardians', '7324', 'Use the 15-foot emanation, halve hostile Speed, and deal Radiant unless the caster is Evil, then Necrotic.'),
  entry('R-SPELL-140', 'stinking-cloud', '7391', 'Place a 20-foot-radius heavily obscured cloud whose failed Constitution saves prevent actions while Poisoned.'),
  entry('R-SPELL-141', 'tiny-hut', '7908', 'Create the stationary 10-foot emanation for eight hours with its passage, spell, atmosphere, and visibility barriers.'),
  entry('R-SPELL-142', 'tongues', '7932', 'The touched creature understands spoken and signed languages and is understood by creatures knowing a language.'),
  entry('R-SPELL-143', 'vampiric-touch', '8158', 'A melee spell hit deals 3d6 Necrotic plus 1d6 per higher slot and heals half the damage dealt.'),
  entry('R-SPELL-144', 'water-breathing', '8415', 'Up to ten willing creatures breathe underwater for 24 hours while retaining normal respiration.'),
  entry('R-SPELL-145', 'water-walk', '8429', 'Up to ten willing creatures treat six listed liquid surfaces as ground and use a bonus action to cross the surface.'),
  entry('R-SPELL-146', 'arcane-eye', '398', 'Create the invisible eye within 30 feet, then move it 30 feet per bonus action while maintaining concentration.'),
  entry('R-SPELL-147', 'aura-of-life', '624', 'Use the 30-foot emanation for Necrotic resistance, maximum-HP protection, and 1 HP start-turn recovery.'),
  entry('R-SPELL-148', 'banishment', '686', 'A failed Charisma save removes and Incapacitates the target; higher slots add one target each.'),
  entry('R-SPELL-149', 'black-tentacles', '784', 'Place the 20-foot square; failed Strength saves deal 3d6 Bludgeoning and Restrain amid difficult terrain.'),
  entry('R-SPELL-150', 'blight', '842', 'Constitution success halves 8d8 Necrotic damage, adding 1d8 per higher slot.'),
  entry('R-SPELL-151', 'charm-monster', '1025', 'A failed Wisdom save Charms and makes the creature Friendly for one hour; higher slots add targets.'),
  entry('R-SPELL-152', 'confusion', '1358', 'Place the 10-foot-radius sphere, apply the failed-save behavior restriction, and add 5 feet per higher slot.'),
  entry('R-SPELL-153', 'conjure-minor-elementals', '1516', 'Use the 15-foot emanation for 2d8 chosen elemental attack damage and enemy difficult terrain.'),
  entry('R-SPELL-154', 'control-water', '1660', 'Control the exact 100-foot cube using flood, part, redirect, or the fully dimensioned whirlpool mode.'),
  entry('R-SPELL-155', 'death-ward', '1992', 'The first qualifying drop reaches 1 HP instead of 0, or one non-damaging instant-death effect is negated.'),
  entry('R-SPELL-156', 'dimension-door', '2156', 'Teleport up to 500 feet with at most one nearby willing passenger and apply 4d6 Force on blocked arrival.'),
  entry('R-SPELL-157', 'divination', '2312', 'Ask about the next seven days and add a cumulative 25 percent no-answer chance after the first casting.'),
  entry('R-SPELL-158', 'fabricate', '2852', 'Enforce the 10-foot standard cube, eight connected cubes, 5-foot mineral limit, and skilled-tool requirement.'),
  entry('R-SPELL-159', 'faithful-hound', '2902', 'Track the hound’s 300-foot separation, 30-foot trigger and sight, and 4d8 Force bite save.'),
  entry('R-SPELL-160', 'fire-shield', '3202', 'Choose warm or chill for the paired resistance and 2d8 retaliation while emitting 10-foot light radii.'),
  entry('R-SPELL-161', 'freedom-of-movement', '3520', 'Ignore difficult terrain and magical movement restraints; higher slots add one touched target each.'),
  entry('R-SPELL-162', 'greater-invisibility', '3898', 'The touched creature remains Invisible for the one-minute concentration duration.'),
  entry('R-SPELL-163', 'guardian-of-faith', '3927', 'Enemies within 10 feet save against 20 Radiant damage until the guardian has dealt 60 total.'),
  entry('R-SPELL-164', 'hallucinatory-terrain', '4101', 'Place the 150-foot cube illusion for 24 hours while retaining tactile terrain and a Study contest.'),
  entry('R-SPELL-165', 'ice-storm', '4453', 'Use the 20-foot-radius, 40-foot-high cylinder for 2d10 Bludgeoning plus 4d6 Cold, half on save.'),
  entry('R-SPELL-166', 'locate-creature', '4858', 'Sense a familiar creature within 1,000 feet unless lead or a changed form defeats the query.'),
  entry('R-SPELL-167', 'phantasmal-killer', '5733', 'Wisdom success halves 4d10 Psychic and ends the spell; failure also applies repeated saves and damage.'),
  entry('R-SPELL-168', 'polymorph', '5939', 'On a failed Wisdom save replace statistics with an eligible Beast form and track its temporary HP.'),
  entry('R-SPELL-169', 'private-sanctum', '6213', 'Ward a 5-to-100-foot cube with selected barriers, adding 100 feet per higher slot.'),
  entry('R-SPELL-170', 'resilient-sphere', '6513', 'Enclose a willing target directly; an unwilling Large-or-smaller creature first makes a Dexterity save.'),
  entry('R-SPELL-171', 'secret-chest', '6755', 'After day 60, track a cumulative daily risk that rises by 5 percentage points each day.'),
  entry('R-SPELL-172', 'stone-shape', '7413', 'Shape a touched stone section up to 5 feet in any dimension with at most two hinges and a latch.'),
  entry('R-SPELL-173', 'stoneskin', '7429', 'Consume the diamond dust to grant resistance to Bludgeoning, Piercing, and Slashing for one hour.'),
  entry('R-SPELL-174', 'vitriolic-sphere', '8196', 'Place the 20-foot-radius sphere for 10d4 Acid plus 5d4 later on failure and 2d4 upcast scaling.'),
  entry('R-SPELL-175', 'wall-of-fire', '8217', 'Place the 60-by-20-by-1-foot wall or 20-foot ring and apply scaling 5d8 Fire damage.'),
  {
    ...entry('R-SPELL-176', 'eldritch-blast', '2608-2626', 'Allocate one beam at levels 1-4, two at 5-10, three at 11-16, and four at 17-20; resolve a separate ranged spell attack for 1d10 Force damage against each allocated target.'),
    fieldCitations: {
      identity: 'docs/srd/source/spell-descriptions.txt:2608-2609',
      castingTime: 'docs/srd/source/spell-descriptions.txt:2611',
      components: 'docs/srd/source/spell-descriptions.txt:2615',
      targeting: 'docs/srd/source/spell-descriptions.txt:2613-2626',
      operation: 'docs/srd/source/spell-descriptions.txt:2619-2626',
    },
  },
  {
    ...entry('R-SPELL-177', 'divine-favor', '2333-2341', 'Arm a one-minute self effect whose every weapon hit deals 1d4 extra Radiant damage.'),
    fieldCitations: {
      identity: 'docs/srd/source/spell-descriptions.txt:2333-2334',
      castingTime: 'docs/srd/source/spell-descriptions.txt:2336',
      components: 'docs/srd/source/spell-descriptions.txt:2338',
      targeting: 'docs/srd/source/spell-descriptions.txt:2337',
      operation: 'docs/srd/source/spell-descriptions.txt:2339-2341',
    },
  },
  {
    ...entry('R-SPELL-178', 'ensnaring-strike', '2708-2728', 'Consume the armed rider on the next weapon hit; a failed Strength save Restrains and starts scaling Piercing damage.'),
    limitations: [
      { code: 'post_hit_cast_timing_prearmed', note: 'The reducer pre-arms the rider because post-hit spell-cast reactions are not yet commands.' },
      { code: 'creature_size_save_mode_unavailable', note: 'Large-or-larger save Advantage awaits typed creature size on combat profiles.' },
      { code: 'effect_escape_action_unavailable', note: 'The Strength (Athletics) escape action awaits effect-targeted action commands.' },
    ],
    fieldCitations: {
      identity: 'docs/srd/source/spell-descriptions.txt:2708-2709',
      castingTime: 'docs/srd/source/spell-descriptions.txt:2711-2712',
      components: 'docs/srd/source/spell-descriptions.txt:2714',
      targeting: 'docs/srd/source/spell-descriptions.txt:2713',
      operation: 'docs/srd/source/spell-descriptions.txt:2715-2728',
    },
  },
  {
    ...entry('R-SPELL-179', 'searing-smite', '6738-6751', 'Consume the armed rider on the next weapon hit, scale both Fire damage phases by slot, and repeat the start-turn Constitution save until success.'),
    limitations: [
      { code: 'post_hit_cast_timing_prearmed', note: 'The reducer pre-arms the rider because post-hit spell-cast reactions are not yet commands.' },
    ],
    fieldCitations: {
      identity: 'docs/srd/source/spell-descriptions.txt:6738-6739',
      castingTime: 'docs/srd/source/spell-descriptions.txt:6740-6742',
      components: 'docs/srd/source/spell-descriptions.txt:6744',
      targeting: 'docs/srd/source/spell-descriptions.txt:6743',
      operation: 'docs/srd/source/spell-descriptions.txt:6745-6751',
    },
  },
  {
    ...entry('R-SPELL-180', 'heal', '4158-4167', 'Restore exactly 70 Hit Points at level 6, add 10 per higher slot, and end Blinded, Deafened, and Poisoned.'),
    fieldCitations: {
      identity: 'docs/srd/source/spell-descriptions.txt:4158-4159',
      castingTime: 'docs/srd/source/spell-descriptions.txt:4160',
      components: 'docs/srd/source/spell-descriptions.txt:4162',
      targeting: 'docs/srd/source/spell-descriptions.txt:4161-4164',
      operation: 'docs/srd/source/spell-descriptions.txt:4163-4167',
    },
  },
  {
    ...entry('R-SPELL-181', 'moonbeam', '5582-5611', 'Place the exact cylinder; creatures save against scaling Radiant damage when it appears and at supported end-turn triggers.'),
    limitations: [
      { code: 'persistent_area_move_action_unavailable', note: 'Moving the beam up to 60 feet awaits a persistent-area Magic action command.' },
      { code: 'persistent_area_entry_trigger_unavailable', note: 'Area movement and creature-entry triggers await movement-to-zone interception.' },
      { code: 'shapechange_reversion_unavailable', note: 'Shapechange reversion awaits typed form ownership and restoration hooks.' },
    ],
    fieldCitations: {
      identity: 'docs/srd/source/spell-descriptions.txt:5582-5583',
      castingTime: 'docs/srd/source/spell-descriptions.txt:5585',
      components: 'docs/srd/source/spell-descriptions.txt:5587',
      targeting: 'docs/srd/source/spell-descriptions.txt:5586-5594',
      operation: 'docs/srd/source/spell-descriptions.txt:5588-5611',
    },
  },
] as const satisfies readonly SpellKbEntry[];
