import { describe, expect, it } from 'vitest';
import { sha256 } from '../../../src/crypto/sha256';
import { LUNA6_EFFORT_STUDY } from '../../../tools/luna6-effort-study/registration';
import { declareTestInputs } from '../../helpers/test-inputs';

// FOOTPRINT (owner rulings D904, D907 Q7, D911, D925). The v5 manifest is edited in place: seven brutal fixture
// shas are the repaired rooms' and a typed interim amendment names the superseded bytes. Nothing is re-registered
// for any study: D925 withdrew the D898 effort study before any cell ran, so no D898 pre-run amendment will be
// written (the brutal cohort is still regenerated by COVER-EDGE + REGEN, D911, for the rooms themselves).
//
// W16: the original v5 manifest (sha 8c0bcb3c, the one D569 v5's results and D898 name) is rebuilt without git
// from the committed bytes alone: remove the exact interim amendment text and swap the seven shas back.
// W17'': the LUNA6 registration (tools/luna6-effort-study, kept by D926) is HISTORICAL: it records the study as it
// was registered and then withdrawn (D925), so it names the superseded v5 manifest and is never re-registered.
// That drift is stated here, typed and deliberate; the registration is a record, not a live study input.

const V5_PATH = 'tests/fixtures/d569-blind-experiment-manifest.json';
const SECOND_FAMILY_PATH = 'tests/fixtures/d569-second-family-manifest.json';
const inputs = declareTestInputs({ fixtures: [V5_PATH, SECOND_FAMILY_PATH] });

const ORIGINAL_V5_SHA256 = '8c0bcb3c0afa8358c26129efbef82d0d2882135389d8dd8040fe7e4b6451e13a';
const SECOND_FAMILY_SHA256 = '83daa7ea3ca89b270e5149368d09fa97074124dfe438cf95b346e996996026c8';

interface Amendment {
  readonly id: string;
  readonly supersededManifestSha256?: string;
  readonly supersededFixtures?: readonly { readonly seed: number; readonly sha256: string }[];
}
interface V5Manifest {
  readonly preregistrationAmendments: readonly Amendment[];
  readonly primaryCohorts: readonly { readonly id: string; readonly fixtures: readonly { readonly seed: number; readonly sha256: string }[] }[];
}

function countOf(text: string, needle: string): number {
  return text.split(needle).length - 1;
}

/** The v5 manifest bytes before FOOTPRINT, rebuilt from the committed bytes and the interim entry they carry. */
function rebuiltOriginalV5(bytes: string): string {
  const manifest = JSON.parse(bytes) as V5Manifest;
  const interim = manifest.preregistrationAmendments.at(-1);
  if (interim?.id !== 'footprint-whole-body-fixture-repair' || interim.supersededFixtures === undefined) {
    throw new Error('The v5 manifest does not end with the FOOTPRINT interim amendment.');
  }
  // The exact entry text as committed: its opening line through its closing brace, preceded by the separator.
  const opening = ',\n    {\n      "id": "footprint-whole-body-fixture-repair",';
  expect(countOf(bytes, opening)).toBe(1);
  const start = bytes.indexOf(opening);
  const end = bytes.indexOf('\n    }', start + opening.length) + '\n    }'.length;
  let original = bytes.slice(0, start) + bytes.slice(end);
  const brutal = manifest.primaryCohorts.find((cohort) => cohort.id === 'evaluation-brutal');
  if (brutal === undefined) throw new Error('The v5 manifest has no evaluation-brutal cohort.');
  for (const superseded of interim.supersededFixtures) {
    const current = brutal.fixtures.find((fixture) => fixture.seed === superseded.seed);
    if (current === undefined) throw new Error(`Seed ${String(superseded.seed)} is not in the brutal cohort.`);
    expect(countOf(original, current.sha256), `seed ${String(superseded.seed)} repaired sha occurs once`).toBe(1);
    original = original.replace(current.sha256, superseded.sha256);
  }
  return original;
}

describe('FOOTPRINT interim v5 manifest edit', () => {
  it('W16: rebuilds the original v5 manifest bytes (8c0bcb3c) from the committed manifest alone', () => {
    const bytes = inputs.fixtures.readText(V5_PATH);
    const manifest = JSON.parse(bytes) as V5Manifest;
    expect(manifest.preregistrationAmendments.at(-1)?.supersededManifestSha256).toBe(ORIGINAL_V5_SHA256);
    // Seven superseded fixtures, the brutal seeds FOOTPRINT repaired (D904); 6203004, 005 and 007 were legal.
    expect(manifest.preregistrationAmendments.at(-1)?.supersededFixtures?.map((fixture) => fixture.seed))
      .toEqual([6_203_001, 6_203_002, 6_203_003, 6_203_006, 6_203_008, 6_203_009, 6_203_010]);
    expect(sha256(bytes)).not.toBe(ORIGINAL_V5_SHA256);
    expect(sha256(rebuiltOriginalV5(bytes))).toBe(ORIGINAL_V5_SHA256);
  });

  it("W17'': the withdrawn LUNA6 registration (D925) is historical and names the superseded v5 manifest", () => {
    const v5Bytes = inputs.fixtures.readText(V5_PATH);
    const secondFamilyBytes = inputs.fixtures.readText(SECOND_FAMILY_PATH);
    const pins = new Map(LUNA6_EFFORT_STUDY.strata.map((stratum) => [stratum.manifest.path, stratum.manifest.sha256]));
    expect([...pins.keys()].sort()).toEqual([SECOND_FAMILY_PATH, V5_PATH].sort());
    const interim = (JSON.parse(v5Bytes) as V5Manifest).preregistrationAmendments.at(-1);
    // v5: the registered sha is the superseded manifest's, not the committed bytes'.
    expect(pins.get(V5_PATH)).not.toBe(sha256(v5Bytes));
    expect(pins.get(V5_PATH)).toBe(interim?.supersededManifestSha256);
    expect(pins.get(V5_PATH)).toBe(ORIGINAL_V5_SHA256);
    // Second family: untouched by FOOTPRINT; the registration equals the committed bytes.
    expect(sha256(secondFamilyBytes)).toBe(SECOND_FAMILY_SHA256);
    expect(pins.get(SECOND_FAMILY_PATH)).toBe(sha256(secondFamilyBytes));
  });
});
