export const STARTER_ART_TITLE = 'Starter Pixel Art and Ink Room';
export const STARTER_ART_CREATOR = 'SRD-55 contributors';
export const STARTER_ART_LICENSE = 'CC0-1.0' as const;
export const STARTER_ART_LICENSE_URL =
  'https://creativecommons.org/publicdomain/zero/1.0/legalcode' as const;
export const STARTER_ART_ATTRIBUTION =
  '“Starter Pixel Art and Ink Room” is generated by this repository and dedicated to the public domain under CC0 1.0 Universal (https://creativecommons.org/publicdomain/zero/1.0/legalcode).';
