/**
 * D516 starter-art generator: 64×64 top-down tiles in a 16-bit sensibility.
 * One key light (upper-left), 2×2 Bayer for every gradient, palette colours
 * addressed only as (ramp, step). Every pixel here is generated by this code;
 * nothing is traced or copied from any game.
 */
import { Bitmap, bayer2, hashNoise, type Ink } from './bitmap';
import { neutral, ramp, type PaletteRamp, type RampStep } from './palette';
import { encodePng } from './png';

export const TILE_SIZE = 64;

export const WALL_PIECES = ['n', 's', 'w', 'e', 'nw', 'ne', 'sw', 'se'] as const;
export type WallPiece = (typeof WALL_PIECES)[number];
export const BAND_SIDES = ['n', 's', 'w', 'e'] as const;
export type BandSide = (typeof BAND_SIDES)[number];
export const FLOOR_VARIANTS = [0, 1, 2, 3] as const;
export type FloorVariant = (typeof FLOOR_VARIANTS)[number];
export const DOOR_STATES = ['closed', 'open'] as const;
export type DoorState = (typeof DOOR_STATES)[number];
export const TERRAIN_OBJECTS = ['rubble', 'crate', 'pillar', 'hazard'] as const;
export type TerrainObject = (typeof TERRAIN_OBJECTS)[number];
export const OVERLAY_EFFECTS = [
  'difficult',
  'obscurement-light',
  'obscurement-heavy',
  'magical-darkness',
  'light-bright',
  'light-dim',
  'light-darkness',
  'blocked',
  'light-source',
] as const;
export type OverlayEffect = (typeof OVERLAY_EFFECTS)[number];
export const FOG_STATES = ['hidden', 'unexplored', 'revealed'] as const;
export type FogState = (typeof FOG_STATES)[number];
export const TOKEN_ARCHETYPES = [
  'fighter',
  'wizard',
  'cleric',
  'rogue',
  'ranger',
  'brute',
  'beast',
  'undead',
  'fiend',
  'ooze',
  'construct',
] as const;
export type TokenArchetype = (typeof TOKEN_ARCHETYPES)[number];
export const TOKEN_SIDES = ['party', 'foe'] as const;
export type TokenSide = (typeof TOKEN_SIDES)[number];

export type ArtRecipe =
  | { readonly kind: 'floor'; readonly material: 'stone'; readonly variant: FloorVariant }
  | { readonly kind: 'wall'; readonly material: 'stone'; readonly piece: WallPiece }
  | { readonly kind: 'door'; readonly material: 'wood'; readonly side: BandSide; readonly state: DoorState }
  | { readonly kind: 'shade'; readonly side: BandSide }
  | { readonly kind: 'terrain'; readonly object: TerrainObject }
  | { readonly kind: 'overlay'; readonly effect: OverlayEffect }
  | { readonly kind: 'fog'; readonly state: FogState }
  | { readonly kind: 'focus'; readonly mark: 'active' | 'hidden' }
  | { readonly kind: 'event'; readonly mark: 'adjudicated' }
  | { readonly kind: 'token'; readonly archetype: TokenArchetype; readonly side: TokenSide }
  | { readonly kind: 'token-dead' };

const STONE = (step: RampStep): Ink => ramp('stone', step);
const WOOD = (step: RampStep): Ink => ramp('wood', step);
const EARTH = (step: RampStep): Ink => ramp('earth', step);
const MOSS = (step: RampStep): Ink => ramp('moss', step);
const METAL = (step: RampStep): Ink => ramp('metal', step);
const SKIN = (step: RampStep): Ink => ramp('skin', step);
const WARM = (step: RampStep): Ink => ramp('cloth-warm', step);
const COOL = (step: RampStep): Ink => ramp('cloth-cool', step);
const shade = (ink: Ink, alpha: number): Ink => ({ ...ink, alpha });

// ---------------------------------------------------------------------------
// Floor
// ---------------------------------------------------------------------------

interface Slab {
  readonly x0: number;
  readonly y0: number;
  readonly x1: number;
  readonly y1: number;
}

const SLAB = (x0: number, y0: number, x1: number, y1: number): Slab => ({ x0, y0, x1, y1 });

const FLOOR_LAYOUTS: Readonly<Record<FloorVariant, readonly Slab[]>> = {
  0: [SLAB(0, 0, 30, 30), SLAB(32, 0, 63, 30), SLAB(0, 32, 30, 63), SLAB(32, 32, 63, 63)],
  1: [
    SLAB(0, 0, 40, 20), SLAB(42, 0, 63, 20),
    SLAB(0, 22, 18, 41), SLAB(20, 22, 52, 41), SLAB(54, 22, 63, 41),
    SLAB(0, 43, 30, 63), SLAB(32, 43, 63, 63),
  ],
  2: [SLAB(0, 0, 41, 41), SLAB(43, 0, 63, 20), SLAB(43, 22, 63, 41), SLAB(0, 43, 20, 63), SLAB(22, 43, 63, 63)],
  3: [
    SLAB(0, 0, 20, 30), SLAB(0, 32, 20, 63),
    SLAB(22, 0, 45, 44), SLAB(22, 46, 45, 63),
    SLAB(47, 0, 63, 15), SLAB(47, 17, 63, 63),
  ],
};

function paintSlab(bitmap: Bitmap, slab: Slab, tone: 0 | 1 | 2): void {
  const width = slab.x1 - slab.x0 + 1;
  const height = slab.y1 - slab.y0 + 1;
  const light: Ink = tone === 2 ? STONE(2) : STONE(3);
  const dark: Ink = tone === 2 ? STONE(1) : STONE(2);
  const span = Math.max(1, width + height - 2);
  for (let y = slab.y0; y <= slab.y1; y += 1) {
    for (let x = slab.x0; x <= slab.x1; x += 1) {
      const t = ((x - slab.x0) + (y - slab.y0)) / span;
      const level = Math.min(4, Math.round(t * 3 + (tone === 1 ? 1 : 0)));
      bitmap.put(x, y, bayer2(x, y) < level ? dark : light);
    }
  }
  bitmap.hLine(slab.x0, slab.x1, slab.y0, tone === 2 ? STONE(3) : STONE(4));
  bitmap.vLine(slab.x0, slab.y0, slab.y1, tone === 2 ? STONE(3) : STONE(4));
  bitmap.hLine(slab.x0 + 1, slab.x1, slab.y1, STONE(1));
  bitmap.vLine(slab.x1, slab.y0 + 1, slab.y1, STONE(1));
}

function paintCrack(bitmap: Bitmap, points: readonly (readonly [number, number])[]): void {
  for (let index = 1; index < points.length; index += 1) {
    const [x0, y0] = points[index - 1]!;
    const [x1, y1] = points[index]!;
    bitmap.line(x0, y0, x1, y1, STONE(1));
    bitmap.blendLine(x0 + 1, y0, x1 + 1, y1, shade(STONE(4), 160));
  }
}

function paintMossPatch(bitmap: Bitmap, cx: number, cy: number, rx: number, ry: number): void {
  for (let y = cy - ry; y <= cy + ry; y += 1) {
    for (let x = cx - rx; x <= cx + rx; x += 1) {
      const nx = (x - cx) / (rx + 0.5);
      const ny = (y - cy) / (ry + 0.5);
      const d = nx * nx + ny * ny;
      if (d > 1) continue;
      const level = d < 0.35 ? 3 : d < 0.7 ? 2 : 1;
      if (bayer2(x, y) < level) bitmap.put(x, y, d < 0.2 && bayer2(x, y) === 0 ? MOSS(2) : MOSS(1));
    }
  }
}

function paintChip(bitmap: Bitmap, x: number, y: number, size: number): void {
  for (let dy = 0; dy < size; dy += 1) {
    for (let dx = 0; dx < size - dy; dx += 1) bitmap.put(x + dx, y + dy, STONE(1));
  }
  bitmap.put(x + 1, y + 1, STONE(0));
  bitmap.rect(x + size - 2, y + size, 2, 2, STONE(2));
  bitmap.rect(x + size + 1, y + size - 3, 2, 2, STONE(2));
}

function paintFloor(bitmap: Bitmap, variant: FloorVariant): void {
  bitmap.fill(STONE(1));
  FLOOR_LAYOUTS[variant].forEach((slab, index) => {
    const tone = hashNoise(index, variant, 11) < 0.2 ? 2 : hashNoise(index, variant, 12) < 0.5 ? 1 : 0;
    paintSlab(bitmap, slab, tone);
  });
  switch (variant) {
    case 0:
      paintCrack(bitmap, [[36, 34], [41, 41], [40, 47], [47, 55], [53, 58]]);
      return;
    case 1:
      paintMossPatch(bitmap, 12, 52, 10, 6);
      paintMossPatch(bitmap, 50, 8, 6, 4);
      return;
    case 2:
      paintChip(bitmap, 35, 34, 7);
      return;
    case 3:
      paintCrack(bitmap, [[24, 4], [29, 12], [27, 20]]);
      paintMossPatch(bitmap, 55, 40, 5, 7);
      return;
  }
}

// ---------------------------------------------------------------------------
// Wall band
// ---------------------------------------------------------------------------

const COURSE_HEIGHT = 8;
const BRICK_WIDTH = 16;

function paintBrickCap(bitmap: Bitmap): void {
  for (let y = 0; y < TILE_SIZE; y += 1) {
    const course = Math.floor(y / COURSE_HEIGHT);
    const rowInCourse = y % COURSE_HEIGHT;
    for (let x = 0; x < TILE_SIZE; x += 1) {
      const shifted = (x + (course % 2) * (BRICK_WIDTH / 2)) % BRICK_WIDTH;
      if (rowInCourse === COURSE_HEIGHT - 1 || shifted === BRICK_WIDTH - 1) {
        bitmap.put(x, y, STONE(1));
        continue;
      }
      const t = (shifted / (BRICK_WIDTH - 2) + rowInCourse / (COURSE_HEIGHT - 2)) / 2;
      const level = Math.round(t * 3);
      const lit = rowInCourse === 0 || shifted === 0;
      bitmap.put(x, y, lit ? STONE(4) : bayer2(x, y) < level ? STONE(2) : STONE(3));
    }
  }
}

function outerSides(piece: WallPiece): readonly BandSide[] {
  switch (piece) {
    case 'n': return ['n'];
    case 's': return ['s'];
    case 'w': return ['w'];
    case 'e': return ['e'];
    case 'nw': return ['n', 'w'];
    case 'ne': return ['n', 'e'];
    case 'sw': return ['s', 'w'];
    case 'se': return ['s', 'e'];
  }
}

/** Chebyshev distance from a wall pixel to the room floor this piece borders. */
export function wallFloorDistance(piece: WallPiece, x: number, y: number): number {
  const south = TILE_SIZE - y;
  const north = y + 1;
  const east = TILE_SIZE - x;
  const west = x + 1;
  switch (piece) {
    case 'n': return south;
    case 's': return north;
    case 'w': return east;
    case 'e': return west;
    case 'nw': return Math.max(east, south);
    case 'ne': return Math.max(west, south);
    case 'sw': return Math.max(east, north);
    case 'se': return Math.max(west, north);
  }
}

function paintWallRims(bitmap: Bitmap, piece: WallPiece): void {
  const sides = outerSides(piece);
  for (let y = 0; y < TILE_SIZE; y += 1) {
    for (let x = 0; x < TILE_SIZE; x += 1) {
      let ink: Ink | null = null;
      if (sides.includes('n') && y < 2) ink = y === 0 ? STONE(6) : STONE(5);
      if (sides.includes('w') && x < 2) ink = x === 0 ? STONE(6) : STONE(5);
      if (sides.includes('s') && y > TILE_SIZE - 3) ink = y === TILE_SIZE - 1 ? STONE(0) : STONE(1);
      if (sides.includes('e') && x > TILE_SIZE - 3) ink = x === TILE_SIZE - 1 ? STONE(0) : STONE(1);
      const floor = wallFloorDistance(piece, x, y);
      if (floor <= 1) ink = STONE(0);
      else if (floor === 2) ink = STONE(1);
      else if (floor === 3 && bayer2(x, y) < 2) ink = STONE(1);
      if (ink !== null) bitmap.put(x, y, ink);
    }
  }
}

function paintWall(bitmap: Bitmap, piece: WallPiece): void {
  paintBrickCap(bitmap);
  paintWallRims(bitmap, piece);
}

// ---------------------------------------------------------------------------
// Doors
// ---------------------------------------------------------------------------

function horizontalBand(side: BandSide): boolean {
  return side === 'n' || side === 's';
}

/** Maps door-local coordinates (door drawn as if in the north band) onto the tile for its side. */
function doorPut(bitmap: Bitmap, side: BandSide, x: number, y: number, ink: Ink): void {
  switch (side) {
    case 'n': bitmap.put(x, y, ink); return;
    case 's': bitmap.put(x, TILE_SIZE - 1 - y, ink); return;
    case 'w': bitmap.put(y, x, ink); return;
    case 'e': bitmap.put(TILE_SIZE - 1 - y, x, ink); return;
  }
}

function paintDoor(bitmap: Bitmap, side: BandSide, state: DoorState): void {
  paintWall(bitmap, side);
  const across = { start: 10, end: 53 };
  const depth = { start: 14, end: 49 };
  // jambs
  for (let y = depth.start - 2; y <= depth.end + 2; y += 1) {
    for (const x of [across.start - 2, across.start - 1, across.end + 1, across.end + 2]) {
      doorPut(bitmap, side, x, y, x < across.start ? STONE(4) : STONE(1));
    }
  }
  if (state === 'closed') {
    for (let y = depth.start; y <= depth.end; y += 1) {
      for (let x = across.start; x <= across.end; x += 1) {
        const plank = Math.floor((x - across.start) / 6);
        const inPlank = (x - across.start) % 6;
        const seam = inPlank === 5;
        const t = inPlank / 5 + (y - depth.start) / (depth.end - depth.start) * 0.4;
        const level = Math.round(t * 2.5);
        let ink: Ink = seam ? WOOD(1) : bayer2(x, y) < level ? WOOD(2) : WOOD(3);
        if (!seam && inPlank === 0) ink = WOOD(4);
        if (!seam && y === depth.start) ink = WOOD(5);
        if (plank % 2 === 1 && !seam && bayer2(x, y) === 3 && (y - depth.start) % 9 === 4) ink = WOOD(2);
        doorPut(bitmap, side, x, y, ink);
      }
    }
    for (const bandY of [depth.start + 6, depth.end - 9]) {
      for (let x = across.start; x <= across.end; x += 1) {
        doorPut(bitmap, side, x, bandY, METAL(4));
        doorPut(bitmap, side, x, bandY + 1, METAL(3));
        doorPut(bitmap, side, x, bandY + 2, METAL(2));
        doorPut(bitmap, side, x, bandY + 3, METAL(1));
        if ((x - across.start) % 8 === 3) doorPut(bitmap, side, x, bandY + 1, METAL(5));
      }
    }
    const keyX = across.end - 8;
    const keyY = Math.floor((depth.start + depth.end) / 2);
    for (let dy = -3; dy <= 3; dy += 1) {
      for (let dx = -3; dx <= 3; dx += 1) {
        if (dx * dx + dy * dy <= 9) doorPut(bitmap, side, keyX + dx, keyY + dy, METAL(2));
      }
    }
    doorPut(bitmap, side, keyX, keyY - 1, neutral(0));
    doorPut(bitmap, side, keyX, keyY, neutral(0));
    doorPut(bitmap, side, keyX - 1, keyY + 1, neutral(0));
    doorPut(bitmap, side, keyX + 1, keyY + 1, neutral(0));
    doorPut(bitmap, side, keyX - 2, keyY - 2, METAL(5));
    return;
  }
  // open: the opening glows warm from beyond; the leaf is swung against the west jamb
  for (let y = depth.start - 1; y <= depth.end + 1; y += 1) {
    for (let x = across.start; x <= across.end; x += 1) {
      const t = (y - depth.start) / (depth.end - depth.start);
      const level = Math.round((1 - t) * 4);
      const glow = bayer2(x, y) < level;
      doorPut(bitmap, side, x, y, glow ? (t < 0.25 ? WARM(6) : t < 0.55 ? WARM(5) : WARM(4)) : neutral(1));
    }
  }
  for (let y = depth.start; y <= TILE_SIZE - 2; y += 1) {
    for (let x = across.start; x <= across.start + 5; x += 1) {
      const inPlank = x - across.start;
      doorPut(bitmap, side, x, y, inPlank === 0 ? WOOD(4) : inPlank === 5 ? WOOD(1) : WOOD(3));
    }
  }
}

// ---------------------------------------------------------------------------
// Ambient-occlusion shade bands (3 px along a wall base)
// ---------------------------------------------------------------------------

function paintShade(bitmap: Bitmap, side: BandSide): void {
  const alphas = [150, 100, 50] as const;
  alphas.forEach((alpha, offset) => {
    for (let along = 0; along < TILE_SIZE; along += 1) {
      const ink = shade(neutral(0), alpha);
      switch (side) {
        case 'n': bitmap.put(along, offset, ink); break;
        case 's': bitmap.put(along, TILE_SIZE - 1 - offset, ink); break;
        case 'w': bitmap.put(offset, along, ink); break;
        case 'e': bitmap.put(TILE_SIZE - 1 - offset, along, ink); break;
      }
    }
  });
}

// ---------------------------------------------------------------------------
// Terrain objects
// ---------------------------------------------------------------------------

function paintChunk(bitmap: Bitmap, x: number, y: number, w: number, h: number, base: PaletteRamp): void {
  bitmap.ellipse(x + w / 2, y + h / 2 + 1, w / 2, h / 2, shade(neutral(0), 110));
  bitmap.ellipse(x + w / 2, y + h / 2, w / 2, h / 2, ramp(base, 2));
  bitmap.ellipse(x + w / 2 - 1, y + h / 2 - 1, w / 2 - 1, h / 2 - 1, ramp(base, 3));
  bitmap.put(x + 1, y + 1, ramp(base, 4));
  bitmap.put(x + 2, y + 1, ramp(base, 4));
}

function paintRubble(bitmap: Bitmap): void {
  const chunks = [
    [8, 10, 14, 9], [30, 6, 10, 7], [46, 14, 12, 8], [14, 30, 9, 8], [36, 26, 16, 11],
    [6, 46, 12, 9], [26, 44, 8, 6], [44, 42, 14, 10], [22, 54, 12, 6],
  ] as const;
  for (const [x, y, w, h] of chunks) paintChunk(bitmap, x, y, w, h, 'earth');
  bitmap.line(20, 24, 30, 36, EARTH(1));
  bitmap.line(50, 30, 58, 24, EARTH(1));
}

function paintCrate(bitmap: Bitmap): void {
  bitmap.rect(14, 14, 40, 40, shade(neutral(0), 100));
  const x0 = 12;
  const y0 = 11;
  const size = 40;
  for (let y = y0; y < y0 + size; y += 1) {
    for (let x = x0; x < x0 + size; x += 1) {
      const plank = Math.floor((y - y0) / 8);
      const inPlank = (y - y0) % 8;
      const t = (x - x0) / size;
      const level = Math.round(t * 2 + inPlank / 8);
      let ink: Ink = inPlank === 7 ? WOOD(1) : bayer2(x, y) < level ? WOOD(2) : WOOD(3);
      if (inPlank === 0) ink = WOOD(4);
      if (plank % 2 === 0 && inPlank === 3 && (x - x0) % 11 === 5) ink = WOOD(2);
      bitmap.put(x, y, ink);
    }
  }
  bitmap.outline(x0, y0, size, size, WOOD(1));
  bitmap.hLine(x0, x0 + size - 1, y0, WOOD(5));
  bitmap.vLine(x0, y0, y0 + size - 1, WOOD(5));
  for (const [cx, cy] of [[x0, y0], [x0 + size - 6, y0], [x0, y0 + size - 6], [x0 + size - 6, y0 + size - 6]] as const) {
    bitmap.rect(cx, cy, 6, 6, METAL(2));
    bitmap.rect(cx + 1, cy + 1, 4, 4, METAL(3));
    bitmap.put(cx + 2, cy + 2, METAL(5));
  }
}

function paintPillar(bitmap: Bitmap): void {
  bitmap.disc(35, 36, 23, shade(neutral(0), 120));
  bitmap.disc(32, 32, 23, STONE(1));
  for (let y = 9; y <= 55; y += 1) {
    for (let x = 9; x <= 55; x += 1) {
      const dx = x - 32;
      const dy = y - 32;
      if (dx * dx + dy * dy > 21 * 21) continue;
      const t = (dx + dy) / 60 + 0.5;
      const level = Math.round(t * 4);
      bitmap.put(x, y, bayer2(x, y) < level ? STONE(2) : STONE(4));
    }
  }
  bitmap.ring(32, 32, 21, STONE(1));
  bitmap.ring(32, 32, 16, STONE(2));
  bitmap.disc(32, 32, 14, STONE(3));
  for (let y = 19; y <= 45; y += 1) {
    for (let x = 19; x <= 45; x += 1) {
      const dx = x - 32;
      const dy = y - 32;
      if (dx * dx + dy * dy > 13 * 13) continue;
      if (dx + dy < -8 && bayer2(x, y) < 3) bitmap.put(x, y, STONE(5));
      if (dx + dy > 8 && bayer2(x, y) < 3) bitmap.put(x, y, STONE(2));
    }
  }
}

function paintHazard(bitmap: Bitmap): void {
  for (let y = 4; y < 60; y += 1) {
    for (let x = 4; x < 60; x += 1) {
      const dx = (x - 32) / 26;
      const dy = (y - 32) / 26;
      const d = dx * dx + dy * dy;
      if (d > 1) continue;
      const level = d < 0.2 ? 4 : d < 0.45 ? 3 : d < 0.75 ? 2 : 1;
      if (bayer2(x, y) < level) bitmap.put(x, y, d < 0.3 ? WARM(5) : WARM(3));
    }
  }
  bitmap.disc(30, 31, 9, WARM(6));
  bitmap.disc(31, 32, 6, SKIN(6));
  const cracks: readonly (readonly [number, number, number, number])[] = [
    [30, 22, 22, 10], [22, 10, 14, 8], [38, 26, 50, 16], [50, 16, 56, 18], [26, 40, 16, 52],
    [16, 52, 12, 58], [38, 40, 48, 50], [48, 50, 56, 52], [40, 32, 54, 34],
  ];
  for (const [x0, y0, x1, y1] of cracks) {
    bitmap.line(x0, y0, x1, y1, neutral(0));
    bitmap.line(x0, y0 + 1, x1, y1 + 1, shade(WARM(6), 200));
  }
  for (const [x, y] of [[12, 20], [52, 44], [20, 46], [46, 12]] as const) bitmap.rect(x, y, 2, 2, WARM(6));
}

// ---------------------------------------------------------------------------
// Mechanical overlays (transparent tiles composited by CSS)
// ---------------------------------------------------------------------------

function edgeSoftness(x: number, y: number, band: number): number {
  const edge = Math.min(x, y, TILE_SIZE - 1 - x, TILE_SIZE - 1 - y);
  return edge < band ? Math.floor((edge / band) * 4) : 4;
}

function paintVeil(bitmap: Bitmap, ink: Ink, coverage: number, softBand: number): void {
  for (let y = 0; y < TILE_SIZE; y += 1) {
    for (let x = 0; x < TILE_SIZE; x += 1) {
      const level = Math.min(coverage, edgeSoftness(x, y, softBand));
      if (bayer2(x, y) < level) bitmap.blend(x, y, ink);
    }
  }
}

function paintDifficult(bitmap: Bitmap): void {
  // A faint earth wash so a region reads as one tint at a glance; then a few broken slabs and rubble.
  paintVeil(bitmap, shade(EARTH(2), 70), 1, 0);
  const outlines = [
    [6, 8, 30, 24], [36, 30, 58, 50], [10, 38, 26, 56],
  ] as const;
  for (const [x0, y0, x1, y1] of outlines) {
    bitmap.line(x0, y0, x1 - 6, y0, shade(EARTH(1), 150));
    bitmap.line(x1 - 6, y0, x1, y0 + 4, shade(EARTH(1), 150));
    bitmap.line(x1, y0 + 4, x1, y1, shade(EARTH(1), 150));
    bitmap.line(x0, y0, x0, y1 - 3, shade(EARTH(1), 150));
    bitmap.line(x0, y1 - 3, x0 + 8, y1, shade(EARTH(1), 150));
    bitmap.line(x0 + 8, y1, x1, y1, shade(EARTH(1), 150));
    bitmap.line(x0 + 1, y0 + 1, x1 - 7, y0 + 1, shade(EARTH(4), 90));
  }
  for (let index = 0; index < 8; index += 1) {
    const x = Math.floor(hashNoise(index, 1, 21) * 58) + 2;
    const y = Math.floor(hashNoise(index, 2, 21) * 58) + 2;
    const w = 2 + Math.floor(hashNoise(index, 3, 21) * 3);
    const h = 2 + Math.floor(hashNoise(index, 4, 21) * 2);
    bitmap.rect(x, y + 1, w, h, shade(neutral(0), 120));
    bitmap.rect(x, y, w, h, EARTH(2));
    bitmap.put(x, y, EARTH(4));
  }
}

function paintBlocked(bitmap: Bitmap): void {
  bitmap.disc(34, 36, 19, shade(neutral(0), 130));
  bitmap.disc(32, 33, 18, STONE(1));
  for (let y = 15; y <= 51; y += 1) {
    for (let x = 14; x <= 50; x += 1) {
      const dx = x - 32;
      const dy = y - 33;
      if (dx * dx + dy * dy > 16 * 16) continue;
      const t = (dx + dy) / 44 + 0.5;
      const level = Math.round(t * 4);
      bitmap.put(x, y, bayer2(x, y) < level ? STONE(2) : STONE(4));
    }
  }
  bitmap.ring(32, 33, 16, STONE(1));
  bitmap.line(24, 26, 36, 40, STONE(1));
  bitmap.line(36, 40, 30, 46, STONE(1));
  for (const [x, y, w, h] of [[6, 44, 10, 7], [50, 40, 9, 7], [46, 8, 8, 6], [8, 10, 7, 6], [26, 52, 9, 6]] as const) {
    paintChunk(bitmap, x, y, w, h, 'stone');
  }
}

function paintLightSource(bitmap: Bitmap): void {
  for (let y = 0; y < TILE_SIZE; y += 1) {
    for (let x = 0; x < TILE_SIZE; x += 1) {
      const dx = (x - 32) / 30;
      const dy = (y - 30) / 30;
      const d = dx * dx + dy * dy;
      if (d > 1) continue;
      const level = d < 0.15 ? 4 : d < 0.4 ? 3 : d < 0.7 ? 2 : 1;
      if (bayer2(x, y) < level) bitmap.blend(x, y, shade(WARM(6), 90));
    }
  }
  bitmap.ellipse(32, 44, 9, 4, METAL(1));
  bitmap.ellipse(32, 42, 9, 4, METAL(2));
  bitmap.ellipse(32, 41, 7, 3, METAL(3));
  bitmap.ellipse(32, 32, 7, 10, WARM(4));
  bitmap.ellipse(31, 30, 5, 8, WARM(5));
  bitmap.ellipse(31, 28, 3, 6, WARM(6));
  bitmap.ellipse(31, 26, 2, 3, SKIN(6));
  bitmap.rect(31, 44, 3, 8, METAL(2));
  bitmap.rect(29, 52, 7, 2, METAL(1));
}

function paintOverlay(bitmap: Bitmap, effect: OverlayEffect): void {
  switch (effect) {
    case 'difficult': paintDifficult(bitmap); return;
    case 'obscurement-light': paintVeil(bitmap, shade(neutral(6), 150), 2, 0); return;
    case 'obscurement-heavy': paintVeil(bitmap, shade(neutral(5), 200), 3, 0); return;
    case 'magical-darkness':
      paintVeil(bitmap, shade(neutral(0), 235), 4, 0);
      paintVeil(bitmap, shade(ramp('cloth-cool', 0), 120), 2, 0);
      return;
    case 'light-bright':
      paintVeil(bitmap, shade(WARM(6), 70), 4, 6);
      paintVeil(bitmap, shade(SKIN(6), 60), 2, 12);
      return;
    case 'light-dim': paintVeil(bitmap, shade(WARM(5), 55), 2, 6); return;
    case 'light-darkness': paintVeil(bitmap, shade(neutral(0), 175), 4, 4); return;
    case 'blocked': paintBlocked(bitmap); return;
    case 'light-source': paintLightSource(bitmap); return;
  }
}

// ---------------------------------------------------------------------------
// Fog and UI marks
// ---------------------------------------------------------------------------

function paintFog(bitmap: Bitmap, state: FogState): void {
  switch (state) {
    case 'hidden':
      bitmap.dither(0, 0, TILE_SIZE, TILE_SIZE, neutral(1), neutral(0), 2);
      return;
    case 'unexplored':
      bitmap.dither(0, 0, TILE_SIZE, TILE_SIZE, neutral(0), neutral(1), 1);
      return;
    case 'revealed':
      for (let x = 1; x < TILE_SIZE; x += 4) {
        bitmap.put(x, 0, shade(neutral(5), 120));
        bitmap.put(x + 2, TILE_SIZE - 1, shade(neutral(5), 120));
      }
      return;
  }
}

const PLATE_CENTER_X = 32;
const PLATE_CENTER_Y = 34;
const PLATE_RADIUS = 26;

function paintFocus(bitmap: Bitmap, mark: 'active' | 'hidden'): void {
  if (mark === 'active') {
    for (let y = 0; y < TILE_SIZE; y += 1) {
      for (let x = 0; x < TILE_SIZE; x += 1) {
        const dx = x - PLATE_CENTER_X;
        const dy = y - PLATE_CENTER_Y;
        const d = Math.sqrt(dx * dx + dy * dy);
        if (d >= PLATE_RADIUS + 1 && d < PLATE_RADIUS + 3) bitmap.put(x, y, MOSS(6));
        else if (d >= PLATE_RADIUS + 3 && d < PLATE_RADIUS + 5 && bayer2(x, y) < 2) bitmap.put(x, y, shade(MOSS(5), 200));
      }
    }
    return;
  }
  for (let y = 0; y < TILE_SIZE; y += 1) {
    for (let x = 0; x < TILE_SIZE; x += 1) {
      const dx = x - PLATE_CENTER_X;
      const dy = y - PLATE_CENTER_Y;
      const d = Math.sqrt(dx * dx + dy * dy);
      if (d < PLATE_RADIUS + 1 || d >= PLATE_RADIUS + 3) continue;
      const angle = Math.atan2(dy, dx);
      const dash = Math.floor(((angle + Math.PI) / (2 * Math.PI)) * 16) % 2 === 0;
      if (dash) bitmap.put(x, y, neutral(8));
    }
  }
}

function paintAdjudicated(bitmap: Bitmap): void {
  for (let y = 0; y < TILE_SIZE; y += 1) {
    for (let x = 0; x < TILE_SIZE; x += 1) {
      const dx = x - PLATE_CENTER_X;
      const dy = y - PLATE_CENTER_Y;
      const d = Math.sqrt(dx * dx + dy * dy);
      if (d >= PLATE_RADIUS + 1 && d < PLATE_RADIUS + 3) bitmap.put(x, y, WARM(6));
    }
  }
  for (const [x, y] of [[32, 3], [32, 62], [3, 34], [61, 34]] as const) {
    bitmap.rect(x - 1, y - 1, 3, 3, WARM(6));
    bitmap.put(x, y, SKIN(6));
  }
}

// ---------------------------------------------------------------------------
// Tokens: base plate + three-quarter bust with selective outline
// ---------------------------------------------------------------------------

function paintPlate(bitmap: Bitmap, plateRamp: PaletteRamp | 'neutral', desaturated: boolean): void {
  bitmap.disc(PLATE_CENTER_X + 1, PLATE_CENTER_Y + 1, PLATE_RADIUS, shade(neutral(0), 100));
  const step = (value: number): Ink => plateRamp === 'neutral'
    ? neutral(Math.min(8, Math.max(0, value + 1)) as 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8)
    : ramp(plateRamp, Math.min(6, Math.max(0, value)) as RampStep);
  for (let y = PLATE_CENTER_Y - PLATE_RADIUS; y <= PLATE_CENTER_Y + PLATE_RADIUS; y += 1) {
    for (let x = PLATE_CENTER_X - PLATE_RADIUS; x <= PLATE_CENTER_X + PLATE_RADIUS; x += 1) {
      const dx = x + 0.5 - PLATE_CENTER_X;
      const dy = y + 0.5 - PLATE_CENTER_Y;
      if (dx * dx + dy * dy > (PLATE_RADIUS + 0.5) * (PLATE_RADIUS + 0.5)) continue;
      const t = (dx + dy) / (PLATE_RADIUS * 2) + 0.5;
      const level = Math.round(t * 4);
      const upper = desaturated ? step(3) : step(4);
      const lower = desaturated ? step(2) : step(2);
      bitmap.put(x, y, bayer2(x, y) < level ? lower : upper);
    }
  }
  bitmap.ring(PLATE_CENTER_X, PLATE_CENTER_Y, PLATE_RADIUS, step(0));
  for (let y = PLATE_CENTER_Y - PLATE_RADIUS; y <= PLATE_CENTER_Y; y += 1) {
    for (let x = PLATE_CENTER_X - PLATE_RADIUS; x <= PLATE_CENTER_X; x += 1) {
      const dx = x + 0.5 - PLATE_CENTER_X;
      const dy = y + 0.5 - PLATE_CENTER_Y;
      const d = Math.sqrt(dx * dx + dy * dy);
      if (d <= PLATE_RADIUS - 0.5 && d > PLATE_RADIUS - 1.5 && dx + dy < -PLATE_RADIUS * 0.7) {
        bitmap.put(x, y, step(6));
      }
    }
  }
}

interface BustPalette {
  readonly skin: PaletteRamp;
  readonly body: PaletteRamp;
}

function head(layer: Bitmap, cx: number, cy: number, rx: number, ry: number, ramps: BustPalette): void {
  layer.ellipse(cx, cy, rx, ry, ramp(ramps.skin, 3));
  for (let y = cy - ry; y <= cy + ry; y += 1) {
    for (let x = cx - rx; x <= cx + rx; x += 1) {
      if (layer.get(x, y).alpha === 0) continue;
      const nx = (x - cx) / rx;
      const ny = (y - cy) / ry;
      if (nx + ny > 0.6 && bayer2(x, y) < 3) layer.put(x, y, ramp(ramps.skin, 2));
      if (nx + ny > 1.1) layer.put(x, y, ramp(ramps.skin, 1));
      if (nx + ny < -0.9 && bayer2(x, y) < 2) layer.put(x, y, ramp(ramps.skin, 4));
    }
  }
}

function eyes(layer: Bitmap, cx: number, cy: number, ink: Ink, highlight: Ink | null): void {
  layer.rect(cx - 4, cy, 2, 2, ink);
  layer.rect(cx + 2, cy, 2, 2, ink);
  if (highlight !== null) {
    layer.put(cx - 4, cy, highlight);
    layer.put(cx + 2, cy, highlight);
  }
}

function shoulders(layer: Bitmap, top: number, ramps: BustPalette, widthHalf: number): void {
  for (let y = top; y <= 54; y += 1) {
    const grow = Math.min(widthHalf, 10 + (y - top) * 1.6);
    for (let x = Math.round(32 - grow); x <= Math.round(32 + grow); x += 1) {
      const t = ((x - 32) / grow + (y - top) / 16) / 2 + 0.5;
      const level = Math.round(Math.min(1, Math.max(0, t)) * 4);
      layer.put(x, y, bayer2(x, y) < level ? ramp(ramps.body, 2) : ramp(ramps.body, 3));
    }
    layer.put(Math.round(32 - grow), y, ramp(ramps.body, 4));
  }
  layer.rect(27, top - 5, 7, 6, ramp(ramps.skin, 2));
}

function bust(layer: Bitmap, archetype: TokenArchetype): void {
  switch (archetype) {
    case 'fighter': {
      const ramps: BustPalette = { skin: 'skin', body: 'metal' };
      shoulders(layer, 37, ramps, 19);
      layer.ellipse(15, 40, 6, 5, METAL(4));
      layer.ellipse(49, 41, 6, 5, METAL(3));
      layer.ellipseRing(15, 40, 6, 5, METAL(2));
      head(layer, 31, 25, 8, 9, ramps);
      eyes(layer, 31, 25, neutral(0), null);
      layer.ellipse(31, 20, 9, 7, METAL(3));
      layer.ellipse(30, 18, 7, 4, METAL(4));
      layer.rect(22, 20, 18, 2, METAL(2));
      layer.vLine(31, 21, 29, METAL(2));
      layer.line(44, 42, 53, 30, WOOD(3));
      layer.line(45, 42, 54, 30, WOOD(2));
      layer.rect(46, 34, 6, 2, METAL(5));
      layer.rect(50, 28, 3, 3, METAL(5));
      return;
    }
    case 'wizard': {
      const ramps: BustPalette = { skin: 'skin', body: 'cloth-cool' };
      shoulders(layer, 38, ramps, 18);
      layer.rect(31, 40, 2, 14, COOL(5));
      head(layer, 31, 27, 8, 9, ramps);
      eyes(layer, 31, 26, neutral(0), null);
      layer.ellipse(31, 34, 7, 6, neutral(7));
      layer.ellipse(31, 36, 5, 5, neutral(6));
      layer.ellipse(31, 23, 14, 3, COOL(2));
      for (let y = 5; y <= 22; y += 1) {
        const half = Math.round((y - 5) * 0.7) + 1;
        for (let x = 33 - half; x <= 33 + half; x += 1) {
          layer.put(x, y, x < 33 - half / 2 ? COOL(3) : bayer2(x, y) < 2 ? COOL(2) : COOL(3));
        }
      }
      layer.put(34, 5, COOL(4));
      layer.hLine(19, 46, 22, COOL(1));
      layer.rect(28, 18, 3, 3, SKIN(6));
      return;
    }
    case 'cleric': {
      const ramps: BustPalette = { skin: 'skin', body: 'cloth-warm' };
      shoulders(layer, 38, ramps, 18);
      head(layer, 31, 26, 8, 9, ramps);
      eyes(layer, 31, 26, neutral(0), null);
      for (let y = 15; y <= 36; y += 1) {
        for (let x = 21; x <= 42; x += 1) {
          const nx = (x - 31) / 9.5;
          const ny = (y - 26) / 11;
          const d = nx * nx + ny * ny;
          if (d <= 1 && d > 0.62 && !(y > 26 && x > 24 && x < 39)) layer.put(x, y, WARM(2));
        }
      }
      layer.disc(32, 46, 4, SKIN(6));
      layer.ring(32, 46, 4, METAL(5));
      layer.put(32, 46, METAL(6));
      return;
    }
    case 'rogue': {
      const ramps: BustPalette = { skin: 'skin', body: 'earth' };
      shoulders(layer, 38, ramps, 17);
      head(layer, 31, 27, 8, 9, ramps);
      layer.rect(23, 29, 17, 7, neutral(1));
      layer.rect(24, 29, 15, 1, neutral(2));
      eyes(layer, 31, 26, neutral(0), neutral(8));
      for (let y = 14; y <= 40; y += 1) {
        for (let x = 19; x <= 44; x += 1) {
          const nx = (x - 31) / 11;
          const ny = (y - 24) / 12;
          const d = nx * nx + ny * ny;
          if (d <= 1 && (d > 0.55 || y < 22)) layer.put(x, y, x < 28 ? COOL(1) : COOL(0));
        }
      }
      layer.line(44, 44, 50, 36, METAL(5));
      layer.line(45, 44, 51, 36, METAL(3));
      layer.rect(43, 44, 3, 3, WOOD(2));
      return;
    }
    case 'ranger': {
      const ramps: BustPalette = { skin: 'skin', body: 'earth' };
      shoulders(layer, 38, ramps, 18);
      for (let y = 38; y <= 54; y += 1) {
        for (let x = 34; x <= 50; x += 1) {
          if (layer.get(x, y).alpha !== 0) layer.put(x, y, bayer2(x, y) < 2 ? MOSS(2) : MOSS(3));
        }
      }
      head(layer, 31, 27, 8, 9, ramps);
      eyes(layer, 31, 26, neutral(0), null);
      layer.ellipse(31, 20, 10, 4, EARTH(2));
      layer.ellipse(30, 18, 8, 3, EARTH(3));
      layer.line(40, 16, 48, 8, MOSS(5));
      layer.line(41, 17, 49, 9, MOSS(4));
      for (let y = 10; y <= 46; y += 1) {
        const bow = Math.round(50 + Math.sin(((y - 10) / 36) * Math.PI) * 5);
        layer.put(bow, y, WOOD(3));
        layer.put(bow + 1, y, WOOD(2));
      }
      layer.vLine(50, 10, 46, shade(neutral(7), 200));
      return;
    }
    case 'brute': {
      const ramps: BustPalette = { skin: 'skin', body: 'skin' };
      shoulders(layer, 36, ramps, 22);
      for (let y = 36; y <= 54; y += 1) {
        for (let x = 10; x <= 54; x += 1) {
          if (layer.get(x, y).alpha !== 0 && bayer2(x, y) < 2) layer.put(x, y, SKIN(2));
        }
      }
      layer.line(16, 40, 44, 54, EARTH(2));
      layer.line(16, 41, 44, 55, EARTH(1));
      head(layer, 31, 24, 11, 11, ramps);
      for (let y = 13; y <= 35; y += 1) {
        for (let x = 20; x <= 42; x += 1) {
          if (layer.get(x, y).alpha !== 0 && bayer2(x, y) === 3) layer.put(x, y, SKIN(2));
        }
      }
      layer.rect(24, 21, 15, 2, SKIN(1));
      eyes(layer, 31, 24, neutral(0), null);
      layer.rect(28, 30, 8, 2, SKIN(1));
      layer.rect(27, 30, 2, 3, neutral(8));
      layer.rect(35, 30, 2, 3, neutral(8));
      return;
    }
    case 'beast': {
      const ramps: BustPalette = { skin: 'earth', body: 'earth' };
      shoulders(layer, 38, ramps, 20);
      for (let y = 38; y <= 54; y += 1) {
        for (let x = 12; x <= 52; x += 1) {
          if (layer.get(x, y).alpha !== 0 && bayer2(x, y) < 2 && (x + y) % 3 === 0) layer.put(x, y, EARTH(2));
        }
      }
      head(layer, 31, 26, 10, 9, ramps);
      layer.ellipse(36, 30, 6, 4, EARTH(4));
      layer.rect(38, 28, 3, 2, neutral(0));
      for (const ear of [[22, 17], [40, 17]] as const) {
        for (let dy = 0; dy < 7; dy += 1) {
          layer.rect(ear[0] - dy + 3, ear[1] - 6 + dy, 1 + dy, 1, EARTH(3));
        }
        layer.rect(ear[0] + 1, ear[1] - 3, 2, 3, SKIN(4));
      }
      eyes(layer, 31, 24, SKIN(6), null);
      layer.put(27, 24, neutral(0));
      layer.put(33, 24, neutral(0));
      return;
    }
    case 'undead': {
      const ramps: BustPalette = { skin: 'metal', body: 'stone' };
      shoulders(layer, 39, ramps, 16);
      for (let x = 20; x <= 44; x += 4) layer.vLine(x, 44, 54, neutral(1));
      for (const [x, y] of [[22, 46], [40, 50], [30, 52]] as const) layer.clear(x, y);
      layer.ellipse(31, 25, 8, 9, neutral(7));
      layer.ellipse(31, 24, 7, 7, neutral(8));
      layer.rect(24, 22, 4, 4, neutral(0));
      layer.rect(32, 22, 4, 4, neutral(0));
      layer.put(25, 23, COOL(6));
      layer.put(33, 23, COOL(6));
      layer.rect(30, 27, 2, 3, neutral(1));
      layer.rect(26, 31, 10, 3, neutral(6));
      for (let x = 26; x <= 35; x += 2) layer.put(x, 32, neutral(2));
      return;
    }
    case 'fiend': {
      const ramps: BustPalette = { skin: 'cloth-warm', body: 'cloth-warm' };
      shoulders(layer, 37, ramps, 19);
      for (let y = 37; y <= 54; y += 1) {
        for (let x = 12; x <= 52; x += 1) {
          if (layer.get(x, y).alpha !== 0 && bayer2(x, y) < 2) layer.put(x, y, WARM(1));
        }
      }
      for (const spike of [[15, 38], [49, 39]] as const) {
        for (let dy = 0; dy < 5; dy += 1) layer.rect(spike[0] - 2 + dy, spike[1] - 6 + dy, 5 - dy * 2 + 1, 1, METAL(2));
      }
      head(layer, 31, 26, 8, 9, ramps);
      for (let y = 17; y <= 35; y += 1) {
        for (let x = 22; x <= 40; x += 1) {
          if (layer.get(x, y).alpha !== 0 && bayer2(x, y) === 3) layer.put(x, y, WARM(1));
        }
      }
      layer.line(25, 18, 20, 8, neutral(2));
      layer.line(26, 18, 21, 8, neutral(3));
      layer.line(37, 18, 42, 8, neutral(2));
      layer.line(38, 18, 43, 8, neutral(3));
      eyes(layer, 31, 25, SKIN(6), null);
      layer.rect(27, 31, 8, 1, neutral(0));
      layer.put(27, 32, neutral(8));
      layer.put(34, 32, neutral(8));
      return;
    }
    case 'ooze': {
      layer.ellipse(32, 37, 18, 14, shade(MOSS(3), 235));
      layer.ellipse(29, 33, 12, 9, shade(MOSS(4), 235));
      layer.ellipse(26, 30, 5, 4, shade(MOSS(5), 235));
      layer.ellipse(24, 29, 2, 2, shade(MOSS(6), 235));
      for (let y = 24; y <= 51; y += 1) {
        for (let x = 14; x <= 50; x += 1) {
          if (layer.get(x, y).alpha !== 0 && (x - 32) + (y - 37) > 14 && bayer2(x, y) < 2) layer.put(x, y, shade(MOSS(2), 235));
        }
      }
      layer.ring(40, 40, 3, MOSS(2));
      layer.ring(36, 46, 2, MOSS(2));
      layer.ellipse(22, 50, 3, 4, shade(MOSS(3), 235));
      layer.ellipse(44, 51, 2, 3, shade(MOSS(3), 235));
      layer.ellipse(33, 53, 2, 2, shade(MOSS(3), 235));
      return;
    }
    case 'construct': {
      layer.rect(12, 38, 40, 16, METAL(2));
      for (let y = 38; y <= 53; y += 1) {
        for (let x = 12; x <= 51; x += 1) {
          if (bayer2(x, y) < Math.round(((x - 12) / 40) * 4)) layer.put(x, y, METAL(1));
        }
      }
      layer.hLine(12, 51, 38, METAL(4));
      layer.vLine(12, 38, 53, METAL(4));
      for (const x of [16, 26, 36, 46]) layer.put(x, 42, METAL(5));
      layer.rect(28, 33, 8, 6, STONE(2));
      layer.rect(20, 14, 24, 20, STONE(3));
      for (let y = 14; y <= 33; y += 1) {
        for (let x = 20; x <= 43; x += 1) {
          if (bayer2(x, y) < Math.round((((x - 20) / 24) + ((y - 14) / 20)) * 2)) layer.put(x, y, STONE(2));
        }
      }
      layer.hLine(20, 43, 14, STONE(5));
      layer.vLine(20, 14, 33, STONE(5));
      layer.rect(24, 22, 16, 3, neutral(0));
      layer.rect(25, 23, 14, 1, WARM(6));
      layer.rect(26, 30, 12, 1, STONE(1));
      return;
    }
  }
}

/**
 * Selective outline: the silhouette's shadow side gets the ramp's dark step,
 * the lit side its mid step. No black ring anywhere.
 */
function outlineLayer(layer: Bitmap, dark: Ink, lit: Ink): void {
  const opaque = (x: number, y: number): boolean => layer.get(x, y).alpha > 0;
  const outline: { x: number; y: number; ink: Ink }[] = [];
  for (let y = 0; y < TILE_SIZE; y += 1) {
    for (let x = 0; x < TILE_SIZE; x += 1) {
      if (opaque(x, y)) continue;
      const left = opaque(x - 1, y);
      const up = opaque(x, y - 1);
      const right = opaque(x + 1, y);
      const down = opaque(x, y + 1);
      if (!left && !up && !right && !down) continue;
      outline.push({ x, y, ink: left || up ? dark : lit });
    }
  }
  for (const pixel of outline) layer.put(pixel.x, pixel.y, pixel.ink);
}

function outlineRamps(archetype: TokenArchetype): { readonly dark: Ink; readonly lit: Ink } {
  switch (archetype) {
    case 'fighter': return { dark: METAL(0), lit: METAL(2) };
    case 'wizard': return { dark: COOL(0), lit: COOL(2) };
    case 'cleric': return { dark: WARM(0), lit: WARM(2) };
    case 'rogue': return { dark: COOL(0), lit: EARTH(2) };
    case 'ranger': return { dark: EARTH(0), lit: EARTH(2) };
    case 'brute': return { dark: SKIN(0), lit: SKIN(2) };
    case 'beast': return { dark: EARTH(0), lit: EARTH(2) };
    case 'undead': return { dark: neutral(1), lit: neutral(4) };
    case 'fiend': return { dark: WARM(0), lit: WARM(2) };
    case 'ooze': return { dark: MOSS(0), lit: MOSS(2) };
    case 'construct': return { dark: METAL(0), lit: STONE(2) };
  }
}

function paintToken(bitmap: Bitmap, archetype: TokenArchetype, side: TokenSide): void {
  paintPlate(bitmap, side === 'party' ? 'cloth-cool' : 'cloth-warm', false);
  const layer = new Bitmap(TILE_SIZE, TILE_SIZE);
  bust(layer, archetype);
  const rims = outlineRamps(archetype);
  outlineLayer(layer, rims.dark, rims.lit);
  compositeResolved(bitmap, layer);
}

function paintDeadToken(bitmap: Bitmap): void {
  paintPlate(bitmap, 'neutral', true);
  const layer = new Bitmap(TILE_SIZE, TILE_SIZE);
  layer.ellipse(34, 38, 17, 7, neutral(4));
  layer.ellipse(33, 36, 15, 5, neutral(5));
  layer.disc(14, 36, 6, neutral(5));
  layer.disc(13, 35, 4, neutral(6));
  layer.rect(24, 30, 3, 8, neutral(4));
  layer.rect(44, 42, 8, 3, neutral(4));
  layer.rect(46, 30, 7, 3, neutral(4));
  outlineLayer(layer, neutral(1), neutral(3));
  compositeResolved(bitmap, layer);
}

function compositeResolved(target: Bitmap, layer: Bitmap): void {
  for (let y = 0; y < TILE_SIZE; y += 1) {
    for (let x = 0; x < TILE_SIZE; x += 1) {
      const pixel = layer.get(x, y);
      if (pixel.alpha === 0) continue;
      target.blendRgba(x, y, pixel);
    }
  }
}

// ---------------------------------------------------------------------------
// Entry points
// ---------------------------------------------------------------------------

export function paintRecipe(recipe: ArtRecipe): Bitmap {
  const bitmap = new Bitmap(TILE_SIZE, TILE_SIZE);
  switch (recipe.kind) {
    case 'floor': paintFloor(bitmap, recipe.variant); break;
    case 'wall': paintWall(bitmap, recipe.piece); break;
    case 'door': paintDoor(bitmap, recipe.side, recipe.state); break;
    case 'shade': paintShade(bitmap, recipe.side); break;
    case 'terrain':
      switch (recipe.object) {
        case 'rubble': paintRubble(bitmap); break;
        case 'crate': paintCrate(bitmap); break;
        case 'pillar': paintPillar(bitmap); break;
        case 'hazard': paintHazard(bitmap); break;
      }
      break;
    case 'overlay': paintOverlay(bitmap, recipe.effect); break;
    case 'fog': paintFog(bitmap, recipe.state); break;
    case 'focus': paintFocus(bitmap, recipe.mark); break;
    case 'event': paintAdjudicated(bitmap); break;
    case 'token': paintToken(bitmap, recipe.archetype, recipe.side); break;
    case 'token-dead': paintDeadToken(bitmap); break;
  }
  return bitmap;
}

export function renderPixelArtPng(recipe: ArtRecipe): Uint8Array {
  const bitmap = paintRecipe(recipe);
  return encodePng(bitmap.width, bitmap.height, bitmap.data);
}
