export interface FrozenContentIdentityFeature {
  readonly name: string;
  readonly text: string;
}

export interface FrozenContentIdentityAggregate {
  readonly kind: 'feat' | 'species' | 'spell' | 'subclass';
  readonly edition: string;
  readonly name: string;
  readonly description?: string;
  readonly minimumLevel?: number | null;
  readonly repeatable?: boolean;
  readonly tags?: readonly string[];
  readonly traits?: readonly string[];
  readonly features?: readonly FrozenContentIdentityFeature[];
}

export interface FrozenContentIdentityVector {
  readonly label: string;
  readonly aggregate: FrozenContentIdentityAggregate;
  readonly equivalentAggregates?: readonly FrozenContentIdentityAggregate[];
  readonly canonicalJson: string;
  readonly sha256: string;
  readonly derivedKey: string;
}

/**
 * HAND-PINNED CONTENT-V1 ORACLES.
 *
 * The canonical strings below were written from design §2.2, not copied from
 * production output. During authoring, each literal was independently hashed
 * with:
 *
 * node -e "const {createHash}=require('node:crypto');const s=process.argv[1];console.log(createHash('sha256').update(s,'utf8').digest('hex'))" '<canonical literal>'
 *
 * Do not replace these literals with values generated by the implementation.
 */
export const frozenContentIdentityV1Vectors: readonly FrozenContentIdentityVector[] =
  [
    {
      label: 'ASCII name and explicit null/empty collection',
      aggregate: {
        kind: 'feat',
        edition: '2024',
        name: 'Iron Will',
        description: 'Stand firm.',
        minimumLevel: null,
        repeatable: false,
        tags: [],
      },
      canonicalJson:
        '{"edition":"2024","kind":"feat","normalizedName":"ironwill","payload":{"description":"Stand firm.","minimumLevel":null,"repeatable":false,"tags":[]},"scheme":"content-v1"}',
      sha256:
        'd334236f1f1190cd326854b0bdee3fd7d1eeafd527367062aa7f93b2b491e6b7',
      derivedKey:
        '2024:content.v1:d334236f1f1190cd326854b0bdee3fd7d1eeafd527367062aa7f93b2b491e6b7',
    },
    {
      label: 'combining-mark name with pinned NFKD folding',
      aggregate: {
        kind: 'spell',
        edition: '2024',
        name: "E\u0301lan's Aegis",
        description: 'A ward of light.',
        tags: ['abjuration'],
      },
      equivalentAggregates: [
        {
          kind: 'spell',
          edition: '2024',
          name: "Élan's Aegis",
          description: 'A ward of light.',
          tags: ['abjuration'],
        },
      ],
      canonicalJson:
        '{"edition":"2024","kind":"spell","normalizedName":"elansaegis","payload":{"description":"A ward of light.","tags":["abjuration"]},"scheme":"content-v1"}',
      sha256:
        'e02e3b4b683e8fca7b65f2b0d81c4071eeb4abfd74ba1216a7c706a46ec87c6c',
      derivedKey:
        '2024:content.v1:e02e3b4b683e8fca7b65f2b0d81c4071eeb4abfd74ba1216a7c706a46ec87c6c',
    },
    {
      label: 'non-ASCII name retains Unicode letters',
      aggregate: {
        kind: 'species',
        edition: '2024',
        name: '日本語',
        description: '古い守り。',
        traits: [],
      },
      canonicalJson:
        '{"edition":"2024","kind":"species","normalizedName":"日本語","payload":{"description":"古い守り。","traits":[]},"scheme":"content-v1"}',
      sha256:
        '638d8ad59816cf9d0a599828a355dc5af0b55cbf2e17d287d54fde984e7ef805',
      derivedKey:
        '2024:content.v1:638d8ad59816cf9d0a599828a355dc5af0b55cbf2e17d287d54fde984e7ef805',
    },
    {
      label: 'set-like tags ignore order and duplicates',
      aggregate: {
        kind: 'spell',
        edition: '2024',
        name: 'Prismatic Ward',
        description: 'Choose a ward.',
        tags: ['lightning', 'cold', 'fire', 'cold'],
      },
      equivalentAggregates: [
        {
          kind: 'spell',
          edition: '2024',
          name: 'Prismatic Ward',
          description: 'Choose a ward.',
          tags: ['fire', 'lightning', 'cold'],
        },
      ],
      canonicalJson:
        '{"edition":"2024","kind":"spell","normalizedName":"prismaticward","payload":{"description":"Choose a ward.","tags":["cold","fire","lightning"]},"scheme":"content-v1"}',
      sha256:
        'c0a7185d8d77dba7d87e827638135e3f1e668d56867f1316a4ef6400f021fe9a',
      derivedKey:
        '2024:content.v1:c0a7185d8d77dba7d87e827638135e3f1e668d56867f1316a4ef6400f021fe9a',
    },
    {
      label: 'sequence-like features retain first ordering',
      aggregate: {
        kind: 'subclass',
        edition: '2024',
        name: 'Two-Step Adept',
        features: [
          { name: 'First Step', text: 'Advance.' },
          { name: 'Second Step', text: 'Hold.' },
        ],
      },
      canonicalJson:
        '{"edition":"2024","kind":"subclass","normalizedName":"twostepadept","payload":{"features":[{"name":"First Step","text":"Advance."},{"name":"Second Step","text":"Hold."}]},"scheme":"content-v1"}',
      sha256:
        '26c524fac1ee570b77fa7fed332251e95f493a561dcdf8cd99b451604b548061',
      derivedKey:
        '2024:content.v1:26c524fac1ee570b77fa7fed332251e95f493a561dcdf8cd99b451604b548061',
    },
    {
      label: 'sequence-like features retain reversed ordering',
      aggregate: {
        kind: 'subclass',
        edition: '2024',
        name: 'Two-Step Adept',
        features: [
          { name: 'Second Step', text: 'Hold.' },
          { name: 'First Step', text: 'Advance.' },
        ],
      },
      canonicalJson:
        '{"edition":"2024","kind":"subclass","normalizedName":"twostepadept","payload":{"features":[{"name":"Second Step","text":"Hold."},{"name":"First Step","text":"Advance."}]},"scheme":"content-v1"}',
      sha256:
        'd9d86eaeff02e7eab817b7e5d99628d03f157fb23c1152cc0b81068ed05368c2',
      derivedKey:
        '2024:content.v1:d9d86eaeff02e7eab817b7e5d99628d03f157fb23c1152cc0b81068ed05368c2',
    },
  ];
